### ISSUE TITLE
More custom circles? 

### ISSUE THREAD

**Issue by o0shojo0o** [SKB-CGN/ioBroker.energiefluss#10]
Is it possible to add more than one "custom circle"?

**Comment by SKB-CGN** [comment]
There are more to come after some time.

**Comment by SKB-CGN** [comment]
Solved with -> https://github.com/SKB-CGN/ioBroker.energiefluss#100-2022-08-18.

Now we have 4 circles possible. This will be the current maximum, as we are running out of space.
Or do you have some suggestions?
