### ISSUE TITLE
Dritter Erzeugungspunkt für PV?

### ISSUE THREAD

**Issue by nicomania** [SKB-CGN/ioBroker.energiefluss#101]
Hallo,

erstmal recht herzlichen Dank für diesen schicken Adapter. Das wertet die Vis deutlich auf!

Ich wollte fragen, ob es möglich ist, einen dritten Erzeugungspunkt hinzuzufügen. Ich kenne viele Leute (mich eingeschlossen), die eine PV Anlage mit drei Ausrichtungen haben: Ost, süd, west. Dann könnte man diese auch getrennt darstellen. Aktuell sind ja lediglich zwei möglich. Der großzügige Abstand zwischen den Erzeugungspunkten dürfte übrigens gerne geringer sein. Evtl. konfigurierbar?

Danke und VG

![image](https://user-images.githubusercontent.com/35151132/216928673-b072c050-b8f1-4f1d-b72e-93897abfebd2.png)

**Comment by SKB-CGN** [comment]
Hallo,
danke für die Rückmeldung. Aktuell sind 2 Elemente für die Produktion möglich, da das 3. Element nicht dazwischen passt. Es würde zwar passen, aber man sieht dann keine Linie mehr.
Vielleicht wird es in baldiger Zukunft noch einen 3. Punkt geben, wenn ich das Design überarbeite.

**Comment by nicomania** [comment]
Na das klingt doch schon positiv :-)
Ich weiß natürlich nicht, was da im Hintergrund für Abhängigkeiten und Restriktionen bestehen, aber so wie du es beschreibst könnte ich prima damit leben. Ich habe das mal gephotoshoppt:

![image](https://user-images.githubusercontent.com/35151132/216953610-1a7be51d-7cb3-4713-99bf-3f09dab51375.png)

Ich finde es nicht schlimm, dass die Linien zwischen den Erzeugungspunkten wenig sichtbar sind. Ich finde es sogar sehr gut, dass die drei Solaranlagen schön kompakt beieinander stehen. Wenn man die Nummerierung so wie dargestellt umsetzt, könnte jeder, der einen dritten Bezugspunkt braucht, selbst entscheiden ob er die verkürzten Linien in Kauf nimmt. Ich würde mich freuen, wenn du das so umsetzen könntest.

**Comment by ThorstenBoettler** [comment]
Wäre es auch möglich evtl. noch mehr Verbrauchspunkte zu konfigurieren?

**Comment by SKB-CGN** [comment]
> Wäre es auch möglich evtl. noch mehr Verbrauchspunkte zu konfigurieren?

Bitte nicht in andere Beiträge Themen vermischen.
Reichen 11 Verbrauchspunkte nicht aus?
Die Oberfläche bietet leider nicht mehr Platz.

**Comment by SKB-CGN** [comment]
Öffne bitte ein neues Issue - dann kann ich es Dir erläutern und entferne die Beiträge hier.

**Comment by SKB-CGN** [comment]
Aktuell ist der 3. Punkt in Arbeit.

**Comment by SKB-CGN** [comment]
Bei aktueller Version 3.5.0 wurde dies mit eingebaut. Bitte testen und bei Erfolg das Issue schließen.
Bei Misserfolg natürlich eine Rückmeldung ;)

**Comment by nicomania** [comment]
Uii! Dankeschön! Wie bekomme ich die Version denn installiert? Ich sehe die Version in den Github releases. Aber im iobroker _beta_ oder _online_ Repo wird sie mir nicht angezeigt. und mit _bestimmte Version installieren_ wird sie mir auch nicht angeboten. Kannst du mir einen Hinweis geben?

**Comment by SKB-CGN** [comment]
So, wie Du Die Version aktuell auch installiert hast. Github Katze -> benutzerdefiniert -> Adresse von hier.

Allerdings hat die Version hier aktuell ein Problem mit Animationen - die laufen nicht richtig.

**Comment by nicomania** [comment]
Mega! Sieht klasse aus! Vielen Dank! 
Allerdings skaliert es nun etwas anders und ich habe in meinem Jarvis Widget scrollbalken. Wurde da etwas geändert? Ich spiele noch etwas mit den Einstellungen. Die Animationen funktionieren bei mir aber problemlos.

![image](https://user-images.githubusercontent.com/35151132/218251456-902744aa-f6be-4dc2-9c9f-89dd64ae0432.png)

**Comment by SKB-CGN** [comment]
Der Punkt muss ja weiter links.
Daher rutscht alles nach rechts. 

Normal ist die Batterie ja noch darunter, die Du nicht nutzt.

**Comment by nicomania** [comment]
Also ich habe jetzt viel mit den Einstellungen gespielt und das Problem ist die Höhe, nicht die Breite. Ich müsste nur die Höhe des Widgets vergrößern, weil der Energiefluss nicht mehr so klein skaliert werden kann, wie früher. Die Größe, welche noch ohne scrollbalken möglich ist, sieht für meinen Geschmack aber recht klobig und viel zu groß aus. Ich habe schon die Schriftgrößen verkleinert, aber das ändert nichts an den Abständen oder den Elementgrößen. Man kann das prima nachvollziehen, wenn man den Energiefluss in einem eigenen Browserfenster öffnet und dann das Fenster per Hand skaliert. So ca. ab 400px Höhe kommen unweigerlich scrollbalken, obwohl noch jede Menge Platz in der Breite vorhanden ist.
Aber das ist Meckern auf hohem Niveau ;-) Nochmal danke!

![image](https://user-images.githubusercontent.com/35151132/218252704-fe3315e2-e4a0-4703-9b92-536f02115401.png)
