### ISSUE TITLE
FeatureRequest: Multiplikator für die Benutzerdefinierten Werte (Umrechnung Watt<->kiloWatt)

### ISSUE THREAD

**Issue by kschaumann** [SKB-CGN/ioBroker.energiefluss#102]
Ich würde gerne weitere "Geräte" (Grossverbraucher) in mein Energiefluss-Diagramm aufnehmen (Waschmaschine, Trocker) diese Daten habe ich aber jeweils in Watt, nicht Kilowatt. Die meisten anderen (Powermeter) habe ich aber in kW. 

Somit kann ich die nicht zusammen in ein Diagramm aufnehmen, weil die Einheiten nicht passen. 

Daher wäre es toll, wenn statt des allgemeinen Schalters "Rechne alle von Watt in kiloWatt um" ein "Faktor" pro benutzerdefiniertem Gerät ergänzt werden würde, mit dem der ursprüngliche multipliziert wird um auf Watt oder eben kilowatt zu kommen. 

Beispiel: Meine Waschmaschine meldet einen aktuellen Verbrauch von 360W. Dies rechne ich per Faktor 0,001 auf 0,36kW um und kann diesen dann in mein Diagramm aufnehmen. Oder eben andere, die das Diagramm in Watt haben und Werte in kilowatt geben dort den Faktor 1000 an: 0,36kw *1000 = 360W

**Comment by SKB-CGN** [comment]
Aktuell kannst Du dich mit Hilfsdatenpunkten behelfen und selbst berechnen.

**Comment by SKB-CGN** [comment]
Umrechnung für alle Datenpunkte ist derzeit in Arbeit.

**Comment by SKB-CGN** [comment]
Bei aktueller Version 3.5.0 wurde dies mit eingebaut. Bitte testen und bei Erfolg das Issue schließen.
Bei Misserfolg natürlich eine Rückmeldung ;)

**Comment by kschaumann** [comment]
Läuft bei mir gut, ich habe die Werte im Diagramm nun in W und lasse die in kW umrechnen. Das klappt!

Danke für die schnelle Reaktion!

**Comment by SKB-CGN** [comment]
Hallo,
tut mir Leid, wenn der aktuelle "Energiefluss" Adapter deine Wünsche nicht berücksichtigen konnte.

Ich habe einen neuen Adapter, den "Energiefluss-erweitert", entwickelt, der möglicherweise Deinen Wünsche bereits berücksichtigt bzw. noch berücksichtigen wird.

Du kannst Ihn gerne ausprobieren.

Forum:
https://forum.iobroker.net/topic/64734/test-adapter-energiefluss-erweitert-v0-0-x-github-latest

Github Link:
https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert

Schau mal rein ;)
