### ISSUE TITLE
Verbindung Netz <-> Solar

### ISSUE THREAD

**Issue by heckmic** [SKB-CGN/ioBroker.energiefluss#105]
Ich habe eine Solarinsel. Die Anlage speist nicht ein. Kann man das so einstellen, dass Netz mit Haus aber nicht mit Solar verbunden ist?

**Comment by SKB-CGN** [comment]
Hm, das müsste ich mir anschauen.
Aktuell wurde die Linie bestehen bleiben, auch wenn keine Einspeisung erfolgt.

**Comment by heckmic** [comment]
Habe das jetzt so gelöst das ich Öffentliche Netzeinspeisung und Verbrauch des öffentlichen Netzes auf den gleichen Datenpunkt (Bezug Netz) gesetzt habe und zusätzlich den Haken "Verwenden Sie positiv für den Verbrauch und negativ für die öffentliche Netzeinspeisung" gesetzt habe. Damit die unnötige Linie nicht angezeigt wird habe ich zudem dann nur die aktiven Linien aktiviert. - Das ist zwar nicht 100% was ich gerne möchte, aber so wird es richtig dargestellt.

**Comment by SKB-CGN** [comment]
Immerhin ein Workaround. 

Du hast also keine Netzeinspeisung?
Was passiert denn mit der Energie, die nicht genutzt wird?

Verpufft die?

**Comment by heckmic** [comment]
Wir haben 2 E-Autos. Eines steht eigentlich immer an der Ladung. Zumdem habe ich nun 50 kWh DIY Speicher. Dazu noch zwei Klimaanlagen die Heizen / Kühlen können. Also wenn der Speicher voll, die Autos voll oder nicht da, und die Klimas auch nichts mehr ausrichten können, dann würde der Rest verpuffen. - Das ist noch nie passiert.

**Comment by SKB-CGN** [comment]
Ah ok, also keine etwas größere Konstellation. 

Ist auch kein Balkonkraftwerk, ja?

Die kommen in der nächsten Version.

Dann könntest Du diese nehmen - die speisen halt nur ein und haben eine Einspeisung zum Haus.

**Comment by heckmic** [comment]
9 kWp zur Zeit. Nein, kein Balkonkraftwerk.

**Comment by SKB-CGN** [comment]
Ok, aber das Element könntest Du nutzen - das hat nur eine Verbindung zum Haus.

Gut, es fehlt dann ein Verbrauchs-Element, aber besser als nichts ;)

**Comment by heckmic** [comment]
Kannst du bei dem Erzeugungselement nicht einfach noch eine Option / Haken setzen "Nulleinspeisung" und damit bleibt die Linie weg?

**Comment by SKB-CGN** [comment]
Ich lasse das Issue mal stehen und schaue es mir an, wenn ich die anderen fertig habe.

Aktuell sind einige Wünsche offen.

**Comment by heckmic** [comment]
Hast ja auch ne coole Sache gebaut ;) Meine Visualisierung habe ich mit HTML von Hand gebastelt in Vis. So gehts natürlich schön fix.

**Comment by SKB-CGN** [comment]
Danke, freut mich natürlich, wenn es vielen gefällt 😉

**Comment by SKB-CGN** [comment]
Sowas wäre es, wie Du meintest, ja?

![2023-02-10 15_03_07-Window](https://user-images.githubusercontent.com/58603329/218111161-a01d8018-a385-473c-8a71-05fefe31f93c.png)
![2023-02-10 15_03_19-Energiefluss](https://user-images.githubusercontent.com/58603329/218111164-c3069b02-3e80-498a-92f4-1b88e78e5d41.png)

**Comment by SKB-CGN** [comment]
Bei aktueller Version 3.5.0 wurde dies mit eingebaut. Bitte testen und bei Erfolg das Issue schließen.
Bei Misserfolg natürlich eine Rückmeldung ;)

**Comment by heckmic** [comment]
Super! Mache ich nachher wenn ich zu Hause bin 👍

SKB-CGN ***@***.***> schrieb am Fr., 10. Feb. 2023, 15:29:

**Comment by heckmic** [comment]
Perfekt!
