### ISSUE TITLE
Animation der Linien

### ISSUE THREAD

**Issue by TerminatorAK** [SKB-CGN/ioBroker.energiefluss#107]
In der Version 3.5.0 werden bei mir alle Linie mit Animation dargestellt, auch wenn der Verbrauch bei 0 Watt liegt. Sollten nicht die Linien ohne Verbrauch ohne Animation, also als einfache feste Linie dargestellt werden ?

**Comment by TerminatorAK** [comment]
Kann es sein, dass beim neu Anlegen eines Verbrauchers, die Linien erst einmal animiert dargestellt werden und erst wenn die Leistungswerte sich einmal geändert haben, die Darstellung der Linie dann erst korrekt ist ?

**Comment by SKB-CGN** [comment]
Es wird beim Starten der aktuelle Wert abgefragt. Wenn dieser animiert werden soll, wird animiert - sonst nicht.

Ist dies nicht der Fall, bitte auf der Konsole

~~
 /opt/iobroker
iobroker upload energiefluss
~~

Und natürlich danach das Browser Fenster aktualisieren.

**Comment by christoph-spielmann** [comment]
<img width="908" alt="Bildschirm­foto 2023-02-10 um 19 28 13" src="https://user-images.githubusercontent.com/83490591/218169175-8de86f1b-d491-4a0c-9b1f-e314f5aa68d3.png">

Bei mir werden von "Ost/West" und "Süd" Animationen angezeigt, obwohl die Leistung "0" ist. Die Einstellung "Automatisch Animation" scheint nicht zu funktionieren. Die Animationsgeschwindigkeit ist bei allen Flüsse indisch, auch bei 0 Watt.

**Comment by SKB-CGN** [comment]
Habe ich gerade im Test einmal nachgestellt.

Hier läuft keine Animation.

Habt ihr denn zusätzlich nochmal:

```
/opt/iobroker
iobroker upload energiefluss
```
ausgeführt?

![2023-02-10 19_36_48-Energiefluss](https://user-images.githubusercontent.com/58603329/218171132-941f4e17-4377-4f4b-acbe-bd61055dd0a2.png)

**Comment by christoph-spielmann** [comment]
> Habt ihr denn zusätzlich nochmal:
> /opt/iobroker
> iobroker upload energiefluss

Ja, habe ich gemacht.

**Comment by SKB-CGN** [comment]
Und keine Änderung, vermute ich?

Browser Fenster aber schon neu geladen, ja?

Mit Strg + F5

**Comment by christoph-spielmann** [comment]
Wenn ich eine Schwellenwert > 0 einstelle, sind die Animationen der 0-Watt-Linien verschwunden. Die Einstellung "Automatisch Animation" wirkt sich aber weiterhin nicht aus.

**Comment by SKB-CGN** [comment]
Automatische Animation greift nur für die Linien, die vom Haus abgehen.

Für alle anderen Linien gilt die eingestellte Geschwindigkeit. 

Du hast nicht zufällig Quelle ist kW bei den Produktionen angeklickt und als Zeichen W eingetragen?

**Comment by TerminatorAK** [comment]
Bei mir ist es auch so, dass wenn ich eine Schwellenwert > 0 einstelle, sind die Animationen der 0-Watt-Linien verschwunden. Wenn das der Workaround ist, könnte ich damit leben.

**Comment by SKB-CGN** [comment]
Welchen Wert haben denn Eure Datenpunkte?

Ganz klar 0 oder 0.1 oder ähnliches?

**Comment by aquapro** [comment]
Bei mir gleiche Problem. Neu frische Installation, ich teste immer, bevor ich einen github Adapter in meine normale Umgebung nehme. heute installiert. Datenpunkte 0. Wenn die 0 sind haben die Linien einen Fluss. Gebe ich 0.1 als Schwellwert ein hört es auf. Beim Adapter wird aber als Eingabebeispiel 0**,**01 gezeigt, also mit Komma. Mache ich das, ist auch ein Fluss zu sehen erst bei 1 hört es auf. 
Auch passt Verbrauch nicht. Test mit Verbrauchsberechnung  über Erzeugung + öffentliches Netz. Ist immer 0 bzw. nach paar Sekunden auf NaN.
![image](https://user-images.githubusercontent.com/16852170/218193986-34841588-3079-40d4-9368-f04705754a27.png)
![image](https://user-images.githubusercontent.com/16852170/218194112-baed86fc-15a5-4221-a62b-d274b84eba2b.png)

**Comment by christoph-spielmann** [comment]
> Welchen Wert haben denn Eure Datenpunkte?
> 
> Ganz klar 0 oder 0.1 oder ähnliches?

Ganz klar 0.0

**Comment by christoph-spielmann** [comment]
> Automatische Animation greift nur für die Linien, die vom Haus abgehen.
> Für alle anderen Linien gilt die eingestellte Geschwindigkeit.

Ok, danke für die Info., Gibt es dafür einen speziellen Grund? Wenn beispielsweise die PV den Akku lädt, geht die Linie nicht vom Haus ab. Anhand der Geschwindigkeit der Animation könnte man trotzdem erkennen, ob viel oder wenig geladen wird.

Ideal wäre eine globale Einstellung als Maximum (z.B. 15kW = 500ms). Alle Linien können dass ausgehend von diesem Wert entsprechend langsamere Animationen anzeigen.

**Comment by SKB-CGN** [comment]
Gibt es. Es war die Idee eines Users, um die Verbräuche besser zu identifizieren. 

Dies könnte man natürlich noch ausweiten.

**Comment by SKB-CGN** [comment]
Ich habe gerade noch einmal etwas geändert.

Würdet Ihr die Version einfach nocheinmal drüber installieren und zurückmelden. Hier lag eine Konvertierung nicht richtig, daher wurde der Schwellenwert als String behandelt, der immer 10 war. Sobald aber etwas anderes eingegeben wurde, schien es zu funktionieren.

Also, bitte einfach nochmal drüber, einmal in die Konfig, die Schwelle auf 0 setzen, dann speichern.
Danke im Voraus!

**Comment by TerminatorAK** [comment]
Könnte das mal ausprobieren. Was muss ich tun, um noch einmal drüber zu installieren ?

**Comment by TerminatorAK** [comment]
Hi, ich habe noch einmal drüber installiert und den Schwellenwert wieder zurück auf 0 gesetzt. Jetzt scheint es zu funktionieren, da die Linie nicht mehr animiert werden, wenn der Verbrauch gleich 0 ist. Denke das war die Lösung.

**Comment by SKB-CGN** [comment]
Wie sieht es bei den Anderen aus?

@aquapro @christoph-spielmann ?

**Comment by aquapro** [comment]
Glaub es geht jetzt mit der Animation. Die ersten Minuten sah es so aus als wär keine Änderung da, bisschen hin und her geklickt dann sah es besser aus. Wo sehe ich ob überhaupt die neuere Version zieht? Steht überall noch 3.5.0.
Ich hab jetzt mal 10 Minuten auf den Bildschirm geschaut, schön mich von der Animation einlullen lassen. Dann sprang auch die verbrauchanzeige von ihren NaN auf den richtigen Wert. Hat Deine Änderung damit auch was zutun?

**Comment by aquapro** [comment]
Kommando zurück, Verbrauch passt doch nicht. Aus der Verbrauchsanzeige werde ich bei der Version nicht schlau. Sobald ich zweiten Solarerzeige hinzufüge geht der Verbrauch auf 0. Nehme ich den wieder raus kommt nach kurzer Zeit ein Wert aber der passt nicht, Faktor 10 zu groß. Neuen issue aufmachen @SKB-CGN, wie hättest Du es gern. Und danke für Deine Hilfe.
![image](https://user-images.githubusercontent.com/16852170/218269869-1bd1e599-96e1-4b62-a2c8-1a6e86eb42d2.png)
Backofen ist gerade an. :)
![image](https://user-images.githubusercontent.com/16852170/218269930-c07f1a07-b4e5-4248-b65c-9c520601c601.png)

**Comment by SKB-CGN** [comment]
Da das ein anderes Problem zu sein scheint, würde ich ein neues Issue bevorzugen, da die Änderung bei @TerminatorAK ja funktioniert.

**Comment by christoph-spielmann** [comment]
> Wie sieht es bei den Anderen aus?

Das Problem ist gelöst, vielen Dank!

Bei mir sind aber die Animationen immer noch gleich schnell und verändern sich nicht abhängig von der Leistung, obwohl ich die Option "Automatische Animation" aktiviert habe.

**Comment by SKB-CGN** [comment]
Automatische Animation greift nur auf der Verbraucher Seite.
