### ISSUE TITLE
Erzeuger für den Akku Einstellen ?

### ISSUE THREAD

**Issue by New-three** [SKB-CGN/ioBroker.energiefluss#108]
Hallo,

erstmal vielen dank für den Adapter. Genau so etwas habe ich schon lange gesucht.
Aktuell habe ich drei Erzeuge as AC und drei als DC.
Wird es ein Möglichkeit geben mehrere Erzeuger als drei einzustellen und dazu noch die Möglichkeit DC Lader anzugeben die direkt in den Akku Laden?

**Comment by SKB-CGN** [comment]
Hallo,
die maximal 3 Erzeuger laden doch direkt in den Akku.

**Comment by New-three** [comment]
Ich habe drei AC Wechselrichter und drei DC Laderegler.
Die DC Laderegler laden natürlich direkt das Akku.
Im Grunde wäre eine Darstellung schön die, die Laderegler als Verbraucher oder Erzeuger nur für den Akku zeigen würde.
Aktuell würden die werte des DC Laderegler dann auch als Erzeuger in den Verbrauch vom Haus mit eingerechnet werden.

**Comment by SKB-CGN** [comment]
Da Du bei mehr als 1000 Installationen der Erste bist, der das anfragt, mutmaße ich, das dies sehr benutzerspezifisch ist.

De Adapter is soweit, wie es möglich ist, allgemein gehalten und deckt maximal 3 Erzeuger und einen Akku ab.

**Comment by New-three** [comment]
Das wundert mich, da es nicht außergewöhnlich ist mit einem PV Laderegler in den Akku direkt zu laden :) 
Wenn man natürlich einen Hybrid Wechselrichter hat der alles in einem Gerät ist, kommt das nicht zum tragen. 
Ich habe ein Victron System und das hat die Laderegler separat :)

Ich habe gerade ein anderes sicherlich kleines Problem.
Habe von meinem Smartmeter den Netzbezug in Netz eingetragen. (Öffentliche Netzeinspeisung und öffentlicher Netzverbrauch)
Ganz oben bei Erzeuger habe ich bei (Verbrauchsberechnung über 'Erzeugung' + 'öffentliches Netz) einen Haken gesetzt.

Doch wird mir der Verbrauch nur als NaN W angezeigt.
Habe ich da einen Gedankenfehler?

**Comment by SKB-CGN** [comment]
Glaube ich gerne - bisher kam da jedoch nichts zu. DIY Batterien?

Aktuell hat die Version wohl einen kleinen Fehler. Das muss ich mir nochmal anschauen.

Manche haben auch Animationen, wo keine sein sollten...

**Comment by New-three** [comment]
Nein keine DIY Batterie. 
Ein normales Victron System mit Pylontech Akkus :) 

Im Grunde müssten die Laderegler als Verbrauche für die Batterie Angezeigt werden wie bei den Verbrauchern(Haus).
Somit wäre auch eine Visualisierung möglich wenn man einen Generator zum Laden der Batterie benutzt. 
Das wäre allerdings sicherlich etwas spezielleres.

**Comment by SKB-CGN** [comment]
Ich kenne das System nicht.

Klingt aber schon sehr speziell, wenn dort noch externe Laderegler angezeigt werden sollen.

Wie bereits geschrieben, kam so eine Anfrage bisher nicht und klingt für mich auch so, als wenn es vom Platz her nicht machbar ist.

**Comment by xiubu-mk** [comment]
Hallo SKB-CGN,

danke für deine Arbeit! Ich habe so ein ähnliches System. Habe Victron Solarladeregler die von den Solarmodulen in die Batterie einspeisen und von der Batterie produziert dann ein Einspeisewechselrichter die benötigte Menge Strom für den Hausverbrauch. Die Verbindung vom PV zu Hausverbrsuch gibt es bei mir nicht

![grafik](https://user-images.githubusercontent.com/38176993/218312466-a3ba57cb-29d7-410f-afa8-5ed3352a1d8f.png)

Ich habe auch keine Möglichkeit gefunden den Einspeisewechselrichter einzubinden, habe hier die DC-seitige Watt, sowie auch die AC-seitige Watt. Das er aus der Batterie zieht und in den Hausverbrauch einspeist.

Siehst du hier eine Möglichkeit das abzubilden?

Gruß xiubu-mk

**Comment by SKB-CGN** [comment]
Hier greift auch meine vorherige Antwort.

Empfinde ich als zu speziell.

**Comment by xiubu-mk** [comment]
Naja so speziell finde ich das gar nicht, hat ja nicht jeder ein Haus mit Dachfläche für ne große Anlage.
Aber trotzdem Danke.

**Comment by bibabuz** [comment]
Hi, super Arbeit, echt genial. Ich habe übrigens das gleiche Problem, wie meine Vorredner. DC-seitig eingebundener Akku, der zusätzlich durch ein Ladegerät geladen wird. Vielleicht speziell, aber falls es Deine Zeit hergibt, würden sich schon drei Leute freuen. 
Außerdem funktioniert die wertabhängige Animationsgeschwindigkeit bei mir nicht... Angezeigte Werte passen aber. 
DANKE für deine Mühe!!

**Comment by SKB-CGN** [comment]
Ich lasse das Thema mal offen. Mal schauen, was Andere sagen.

Die Werte abhängige Animation funktioniert problemlos - auf der Verbraucherseite.

**Comment by incase** [comment]
Wir haben auch ein Victron-System (Batterie BYD-LVL, 3x 5kW einphasiger Wechselrichter, 1x MPPT 450/200 RS 4-Kanal MPPT/DC-Laderegler). Dazu noch unser Altsystem (Plenticore Hybrid-Wechselrichter mit BYD HVL Batterie). Mit anderen Worten: Wir haben zwei unabhängige PV-Systeme.
Der Plenticore lädt den HVL Akku direkt per DC und/oder arbeitet als Wechselrichter um das Haus zu versorgen oder auch (bei vollem Akku) einzuspeisen. Anhand der verfügbaren Daten könnten wir ihn ebenso wie das Victron-System 
betrachten: 2-Kanal MPPT auf DC, Batterie an DC, Wechselrichter an DC->AC. Oder man "vereinfacht" die Betrachtung und betrachtet es als ein PV-System, dass entweder Haus und Batterie versorgt (Überschuss ins Netz) oder aus der Batterie das Haus versorgt. Persönlich finde ich 

`PV -> DC -> AC -> Haus`
`       ^                         `
`       |                         `
`       v                         `
`      BAT                     `

Allerdings aufschlussreicher als die aktuelle Visualisierung.

Wobei beim Victron System der Wechselrichter auch als Ladegerät fungieren kann (wir laden, da am Victron MPPT noch keine Module hängen, die LVL-Batterie aktuell ausschließlich aus dem Überschuss des Plenticore-Systems, also aus dem, was normalerweise ins Netz gehen würde. Hier mal ein "Overview" unseres Systems:

![image](https://user-images.githubusercontent.com/953468/219652795-5dffb692-ab3f-45a3-9d25-78801504248b.png)

Wie man sieht, speisen beide Wechselrichter auf der Haus-Seite ein, wobei aber die Victrons den Netzbezugspunkt auf 0 regeln, während der Kostal Plenticore den Hauszähler auch 0 regelt, soweit möglich.

Die Visualisierung mit dem Energiefluss würde ich gerne so hinbekommen, dass ich sehe:
Summe Produktion String1/String2
Ladung/Entladung HVL-Batterie
Energiefluss Plenticore -> Haus
Energiefluss zur Wärmepumpe
Energiefluss zu ein paar Verbrauchern (hauptsächlich unsere beiden Wallboxen, gerne als Summe)
Restverbrauch Gesamt (nach Abzug Wärmepumpe/Wallboxen)
Energiefluss Victron Multiplus(es) <-> Haus (als Summe)
Energiefluss Victron MPPT -> DC
Energiefluss DC <-> LVL-Batterie
Energiefluss DC <-> Victron Multiplus

Das ist eine ganze Menge, um ehrlich zu sein, aber ich denke, es ist möglich. Die letzten drei kann man evtl. etwas reduzieren, wenn man den MPPT an LVL-Batterie *und* Multiplus anbindet, statt ein virtuelles "DC-Bus"-Gerät dazwischen zu schalten. Ebenso ist es OK, wenn beim Plenticore-Teil "nur" Plenticore<->Batterie und Plenticore<->AC-System/Haus sichtbar ist. Die einfachste Version nochmal grafisch:

**Comment by SKB-CGN** [comment]
@incase und ich soll den Adapter jetzt passend zu Deinem System erstellen? 😃

Ich denke, Du hast Dir den Adapter noch gar nicht richtig angeschaut.

Mach' Dir erstmal ein Bild, stelle ein, was möglich und nötig ist - dann sehen wir weiter.

Um ehrlich zu sein, steige ich anhand deiner Beschreibungen nicht durch.

**Comment by incase** [comment]
Das hier ist Dein Hobby-Projekt, soweit ich das sehe. Ich wollte mit der Darstellung meines Systems lediglich zeigen, dass DC-seitige Akkus mit getrenntem Laderegler nicht selten sind.

Und spätestens wenn Leute ein bestehendes System erweitern wird es kompliziert. Ob Du Lust hast, hier Support für einzubauen, sei es für komplexe Systeme wie unseres oder zumindest für den DC-angebundenen Akku, wie es xiubu-mk weiter oben beschrieb, ist Deine Sache. Ich finde das Teil so wie es ist jedenfalls schon Klasse - es passt aber halt nicht für jeden und muss es auch nicht.

**Comment by SKB-CGN** [comment]
Hallo,
tut mir Leid, wenn der aktuelle "Energiefluss" Adapter deine Wünsche nicht berücksichtigen konnte.

Ich habe einen neuen Adapter, den "Energiefluss-erweitert", entwickelt, der möglicherweise Deinen Wünsche bereits berücksichtigt bzw. noch berücksichtigen wird.

Du kannst Ihn gerne ausprobieren.

Forum:
https://forum.iobroker.net/topic/64734/test-adapter-energiefluss-erweitert-v0-0-x-github-latest

Github Link:
https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert

Schau mal rein ;)

**Comment by bibabuz** [comment]
Danke ;-)

27.04.2023 16:13:41 SKB-CGN ***@***.***>:
