### ISSUE TITLE
Safari Restzeit Position falsch

### ISSUE THREAD

**Issue by Tomi05-k** [SKB-CGN/ioBroker.energiefluss#109]
Hallo,
ich habe den Energiefluss Adapter erfolgreich eingebunden.
Die Objekte verteilen sich eigentlich gut.
Das Problem ist, dass der Restzeit Wert der Batterie im Safari Browser außerhalb des Fensters ist.
Im Chrome Browser klappt es. Kann man das anpassen?

Viele Grüße Tom! 

<img width="1440" alt="Bildschirmfoto 2023-02-11 um 09 10 29" src="https://user-images.githubusercontent.com/67387810/218248010-8ed4a668-75f5-414e-8750-d757d8155c46.png">
<img width="1440" alt="Bildschirmfoto 2023-02-11 um 09 10 12" src="https://user-images.githubusercontent.com/67387810/218248019-07110692-78b6-4422-bdeb-623e5476955a.png">

**Comment by christoph-spielmann** [comment]
Bei mir tritt das Problem ebenfalls mit Safari auf.

**Comment by HJS72** [comment]
Kann ich nur bestätigen - Safari: Restzeit hängt über der Produktion; Firefox: Position ist OK

**Comment by SKB-CGN** [comment]
Liegt an Safari. Der Browser kann verschiedene Dinge einfach nicht.
