### ISSUE TITLE
Schwellwerte für custom Stromkreise

### ISSUE THREAD

**Issue by rotodt** [SKB-CGN/ioBroker.energiefluss#11]
Wäre vorteilhaft wenn ein Minimum Schwellwert für jeden der 4 custom Stromkreise einstellbar ist. Zum Definieren ab wann der Stromkreis als Verbrauch visuell angezeigt werden soll.
Hintergrund: Obwohl zum Beispiel die Klimaanlage ausgeschaltet ist, führt der StandBy Verbrauch von 1 Watt bereits dazu, dass die Flussrichtung visuell dargestellt wird.

**Comment by SKB-CGN** [comment]
Hallo, es ist aktuell ein globaler Schwellwert für alle Kreise möglich.

**Comment by SKB-CGN** [comment]
In der neuen Version korrigiert. Schwellwert wurde nicht für alle Elemente benutzt.

**Comment by rotodt** [comment]
Hallo, du meinst den Schwellwert unter Haupteinstellung > Sonstiges?
Den habe ich bereits auf 10 gestellt aber der optische Energiefluss wird trotzdem bereits bei 1 Watt aktiviert.

![Screenshot](https://user-images.githubusercontent.com/96916716/186164285-1e1f45bf-7955-413d-89e3-fc1468d9652c.jpg)

**Comment by SKB-CGN** [comment]
Korrekt. Bitte die aktuelle, neue Version von Github drüber installieren. Dann greift der Schwellenwert und die Animation wird nicht aktiviert. Hier lag ein Fehler vor.

**Comment by rotodt** [comment]
Mit der Version 1.0.6 verschwinden die Stromkreise Klima, Waschmaschine und Trockner aus der view sobald ich einen Schwellwert definiere. Auch dann wenn Leistung über den eingetragenen Schwellwert gezogen werden.

**Comment by SKB-CGN** [comment]
Hättest Du da mal einen Screenshot?

Verschwinden die Kreise komplett?

**Comment by rotodt** [comment]
Die Kreise verschwinden einschlißlich der Linien komplett. Inzwischen revidiere ich allerdings meine Aussage, es hat nicht ausschließlich was mit dem Schwellwert zu tun. Auch ohne Schwellwert fehlt mir ein Symbol. Mit Schwellwert fehlen mir die besagten drei Symbole. 

![Screenshot](https://user-images.githubusercontent.com/96916716/186181912-f536b96c-d298-43f1-8c9f-7ae51daea5b8.jpg)

**Comment by SKB-CGN** [comment]
Ich habe dies gerade einmal versucht, nachzustellen. An dem Schwellenwert wird es nicht liegen. Ich habe 10 als Schwelle eingetragen und die Kreise verschwinden nicht.
![2022-08-23 16_24_03-Energiefluss — Mozilla Firefox](https://user-images.githubusercontent.com/58603329/186183708-70a79b59-24bf-4b08-b857-2e6c22b6b20b.png)

**Comment by rotodt** [comment]
Hab die Instanz nochmal komplett neu erstellt und seitdem den Fehler nicht reproduzieren können.
Die Schwellwerteinstellung funktioniert wie gewünscht. Danke!

**Comment by SKB-CGN** [comment]
Dann ist ja alles prima. Sollte etwas sein - einfach melden :)

**Comment by SKB-CGN** [comment]
Hallo,
tut mir Leid, wenn der aktuelle "Energiefluss" Adapter deine Wünsche nicht berücksichtigen konnte.

Ich habe einen neuen Adapter, den "Energiefluss-erweitert", entwickelt, der möglicherweise Deinen Wünsche bereits berücksichtigt bzw. noch berücksichtigen wird.

Du kannst Ihn gerne ausprobieren.

Forum:
https://forum.iobroker.net/topic/64734/test-adapter-energiefluss-erweitert-v0-0-x-github-latest

Github Link:
https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert

Schau mal rein ;)
