### ISSUE TITLE
Safari Animation Batteriesymbol

### ISSUE THREAD

**Issue by HJS72** [SKB-CGN/ioBroker.energiefluss#110]
Version 3.5.0;
Bei Safari wird keine Animation des Batteriesymbols angezeigt (
Firefox funktioniert
<img width="636" alt="image" src="https://user-images.githubusercontent.com/41542201/218251110-066b26ba-3831-423c-888f-49e9dab8dfa8.png">

**Comment by SKB-CGN** [comment]
Sagte ich bereits:
Safari kann verschiedene Dinge nicht.

Wenn der Browser nicht HTML konform ist, wird er nicht besonders behandelt.
