### ISSUE TITLE
Einbindung in VIS

### ISSUE THREAD

**Issue by Mutanten** [SKB-CGN/ioBroker.energiefluss#111]
würde den Energiefluss gerne in die VIS einbinden, habe das über iFrame gemacht, jedoch blockiert Feierfox das öffnen eingebetteter Seiten. Habe ein wenig gegoogelt aber nicht wirklich fündig geworden wie man das umgehen kann. Hast du einen Tip.
<img width="468" alt="VIS" src="https://user-images.githubusercontent.com/116433119/218259583-99529c27-591d-40c7-b9be-cd2c82d1d296.png">

**Comment by SKB-CGN** [comment]
Als Frame kannst Du jede Seite einbinden. Da wird eigentlich nichts blockiert.

Es sei denn, die VIS erlaubt dies nicht - dann musst du mal schauen, was in den Optionen möglich ist.

Bei mir läuft der Adapter im iframe bei JarVIS problemlos.

**Comment by Mutanten** [comment]
Sehr seltsam, ich lasse mir aus der History Werte über iFrame anzeigen und das funktioniert einwandfrei.
Welchen link verwendest du, das ist doch direkt der link der aus dem Tab Energiefluss kommt, oder?
<img width="101" alt="Energie" src="https://user-images.githubusercontent.com/116433119/218266192-9090aacd-4901-43bd-8f05-9d799f7a29c2.png">

**Comment by SKB-CGN** [comment]
Ich nutze http://<ip-iob>:8082/energiefluss/

Der Instanzlink nimmt selber noch ein Frame.

Vielleicht liegt es daran.

**Comment by Mutanten** [comment]
Danke, das wars. 
Das muss man halt wissen

**Comment by SKB-CGN** [comment]
Wenn du den Link in der Instanz Ansicht klickst, öffnet sich auch die richtige Seite.

**Comment by Mutanten** [comment]
ah, das wusste ich noch nicht

Danke

**Comment by SKB-CGN** [comment]
Gern, wenn alles erledigt ist, dann bitte das Issue schließen.

**Comment by stmb-100** [comment]
Hi
ich versuche im iFrame diesen Link und bekomme es einfach nicht hin,

http://192.168.1.241:8081/#tab-energiefluss-0 (Link aus dem Menü)

Wo liegt mein Gedanken Fehler ?

**Comment by SKB-CGN** [comment]
Der Link für den iframe wäre in deinem Fall:

https://192.168.1.241:8082/energiefluss/
