### ISSUE TITLE
Erweiterungswunsch: Anzeige zusätzlicher Informationen/Felder

### ISSUE THREAD

**Issue by bicmac** [SKB-CGN/ioBroker.energiefluss#112]
Hi,
ich würde bei der Solarproduktion und beim Verbrauch gern zusätzlich jeweils einen Datenpunkt einzeigen wieviele kWh am aktuellem Tag produziert bzw aus dem Netz bezogen wurden und auch einen Datenpunkt was das in Euro bedeutet.
Nun kann ich zwar momentan einen zweiten Datenpunkt einbinden, diese bekommt aber immer automatisch die Einheit W oder kW (je nach Einstellung) verpasst.
Ich will sozusagen auf dem Energiefluss sehen:
1) Was habe ich am aktuellen Tag bisher ins public Netz geliefert (kWh) + Euro
2) Was habe ich am aktuellem Tag aus dem Netz bezogen (kWh) + Euro 
3) Was hat meine PV am aktuellen Tag bisher produziert (kWh) + Euro
4) Wie ist der aktuelle Zählerstand des Stromzähler zur Lieferung
5) Wie ist der aktuelle Zählerstand des Stromzählers zum Bezug
6) Wie ist der aktuelle Zählerstand des Stromzählers zur Produktion der PV
7) ggf was ist der aktuelle Zählerstand des Stromzählers der Wallbox

Evtl sogar noch erweitert um das aktuelle Jahr.

**Comment by SKB-CGN** [comment]
Da kann ich dich jetzt schon beruhigen:

Solche Dinge wird es nicht geben.

Es ist ein Energiefluss und keine Wertetabelle. Auch visualisiere ich hier keine Zählerstände oder ähnliches.

**Comment by aquapro** [comment]
Hi, ich will Dir ja nicht rein reden, ist Deine Entscheidung. Nur damit ich es verstehe. Ist die Batterie Prozent Anzeige nicht genau das, was sich bicmac bei den anderen Objekten wünscht. Dann halt keine Prozentzahl, sondern ein anderer Wert.

**Comment by bicmac** [comment]
ja das würde schonmal helfen um zumindest den Bezug/Produktion/Verbrauch des aktuellen Tages in kWh einzublenden Pro Objekt.

**Comment by SKB-CGN** [comment]
> Hi, ich will Dir ja nicht rein reden, ist Deine Entscheidung. Nur damit ich es verstehe. Ist die Batterie Prozent Anzeige nicht genau das, was sich bicmac bei den anderen Objekten wünscht. Dann halt keine Prozentzahl, sondern ein anderer Wert.

Nein, Du kannst inzwischen bei Produktion, Verbrauch und Netz Werte im Wechsel anzeigen.

Diese möchte er erweitern, damit auch seine Kosten für Jahr, Monat, Woche, Tag, Stunde und die letzten 6 Minuten angezeigt wird.

Das ist aber nicht der Grundgedanke dieses Adapters. Er bietet eine Erweiterung zur Visualisierung. Keine Visualisierung ansich wi3 VIS, JarVIS oder ähnliches.

**Comment by aquapro** [comment]
@SKB-CGN danke. Jetzt hab ich es verstanden.

**Comment by paba42** [comment]
Hi!
Ich würde mich der Anfrage zur Anzeige weiterer Felder anschließen wollen.
Konkret würde mich bei der Erzeugung die Tagesmenge (kWh) interessieren. Ich habe das als alternativen Datenpunkt eingatragen, aber es wird mir nicht angezeigt.
![grafik](https://user-images.githubusercontent.com/67841607/221793946-0bde343c-bd2f-4d8f-a421-c992a9477e47.png)

Weiter fände ich es gut, wenn ich beim Netz darstellen könnte, wie viel ich eingespeist und wie viel ich bezogen habe. Dafür würde man hat 2 Datenpunkte mit kWh benötigen.

**Comment by SKB-CGN** [comment]
Hast Du denn die Alternative Anzeige aktiviert?

Nur eintragen reicht nicht aus.

**Comment by paba42** [comment]
Nee, hatte ich nicht, danke für den Hinweis! 
Hab die Checkbox nicht gesehen, Werte- und Texttausch war für mich nicht intuitiv, hätte nach etwas mit Alternativ... erwartet.

Die Einheit W ist halt nicht intuitiv. Vielleicht hast Du mal Zeit / Lust das einzubauen. Mir würde ein Textfeld daneben reichen. Oder ein Balken der sich füllt, für den man einen Maximalwert konfigurieren kann.
Danke!

**Comment by SKB-CGN** [comment]
Welche Einheit W?

Welcher Balken soll sich füllen?

**Comment by paba42** [comment]
Wenn ich den bisher generierten Strom als Alternativtext eintrage, dann hat er die Einheit W. Richtig wäre, wenn er die Einheit Wh oder alternativ kWh hätte.
Siehe Beispiel:
![grafik](https://user-images.githubusercontent.com/67841607/221800506-ee688d4d-d1f8-4264-80c6-4142ca7c51a2.png)
Die Einheit im Datenpunkt ist in kWh, ich müsste es noch ausmultiplizieren, aber es werden halt 5W statt 5Wh angezeigt.

Ich schrieb ja, dass ich einen neuen Balken gut fände.

**Comment by SKB-CGN** [comment]
Alternative Datenpunkte können auch andere Einheiten haben.

Einfach mal lesen und nicht sagen "geht nicht".

Tab -> Andere seit Version 3.6

**Comment by SKB-CGN** [comment]
Alternative Datenpunkte können auch andere Einheiten haben.

Einfach mal lesen und nicht sagen "geht nicht".

Tab -> Andere seit Version 3.6

**Comment by paba42** [comment]
Habe 3.5 installiert, werde updaten.

**Comment by paba42** [comment]
Hi habe geupdated.
Funktioniert mit dem alternativem Datenpunkt und der anderen Einheit. Zieht es sich die Einheit aus dem Datenpunkt?

**Comment by SKB-CGN** [comment]
Nein, die gibst Du beim Tab Andere an.

**Comment by paba42** [comment]
Ich hab da nichts eingegeben:
![grafik](https://user-images.githubusercontent.com/67841607/221839519-fd70fd8a-cc1f-44d7-88a5-6e9a7b23ccdd.png)

Und ich sehe das:
![grafik](https://user-images.githubusercontent.com/67841607/221839698-a2cc9838-9110-4a8a-9523-53e746693569.png)
![grafik](https://user-images.githubusercontent.com/67841607/221839890-b4b554a5-812d-4e90-96a5-09dba4a68251.png)

Bzw. Das:
![grafik](https://user-images.githubusercontent.com/67841607/221839771-7a3c65ca-1bc2-4695-89be-390b871d48df.png)
![grafik](https://user-images.githubusercontent.com/67841607/221840035-84d9dd4e-5474-43e6-a1d2-8b6761392156.png)

Der Datenpunkt hat ne Einheit:
![grafik](https://user-images.githubusercontent.com/67841607/221840186-4cb269d9-3a56-4db7-abd3-0677b963bf52.png)

**Comment by SKB-CGN** [comment]
Du hast die falsche Konfigurationsseite zu der Version 3.6.0 - bitte richtig updaten oder manuell ein "iobroker upload energiefluss" im ioBroker Verzeichnis durchführen.

**Comment by paba42** [comment]
Ich Update gleich mal per Konsole. 
Mir ist auch grade aufgefallen, dass kW/h ja auch falsch ist.
Ich guck mal, was da nach dem Update zur Auswahl steht.

**Comment by SKB-CGN** [comment]
Hallo,
tut mir Leid, wenn der aktuelle "Energiefluss" Adapter deine Wünsche nicht berücksichtigen konnte.

Ich habe einen neuen Adapter, den "Energiefluss-erweitert", entwickelt, der möglicherweise Deinen Wünsche bereits berücksichtigt bzw. noch berücksichtigen wird.

Du kannst Ihn gerne ausprobieren.

Forum:
https://forum.iobroker.net/topic/64734/test-adapter-energiefluss-erweitert-v0-0-x-github-latest

Github Link:
https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert

Schau mal rein ;)
