### ISSUE TITLE
Verbrauch Summe stimmt nicht

### ISSUE THREAD

**Issue by aquapro** [SKB-CGN/ioBroker.energiefluss#113]
Neu frische Installation. Minimaltest. 1 Erzeuger und der Einspeisepunkt im Haus. Sobald man "Verbrauchsberechnung über 'Erzeugung' + 'öffenltiches Netz'" einstellt ist Netz und verbrauch Null. Wenn bei Netzt Haken bei "Verwenden Sie positiv für den Verbrauch und negativ für öffentliche Netzeinspeisung" gesetzt ist steht bei Netz der richtige Wert aber bei Verbrauch das 10fache. Nimmt man ein zweiten Solarpunkt dazu, geht verbrauch auf Null. Hier ein Bild mit Dummy Batterie und Wallbox, plus einen echten Verbraucher.
![image](https://user-images.githubusercontent.com/16852170/218272680-6bacc755-bb28-4d93-86bd-81330ac39f09.png)

Hier mit zweiten Solar Einspeiser.
![image](https://user-images.githubusercontent.com/16852170/218272726-68fd6333-cb55-47c5-879b-477f3b50914d.png)

Einstellungen im Adapter:
![image](https://user-images.githubusercontent.com/16852170/218272741-d784792f-b071-41cb-8a22-f5b6ef2b3ead.png)
![image](https://user-images.githubusercontent.com/16852170/218272757-f24e016c-fc09-4158-b384-93fd747cebdf.png)

**Comment by jenskaschub** [comment]
Kann ich bestätigen. Gleiches Phänomen hier: Wenn das Balknonkraftwerk liefert, dann stimmt Netzbezug/PV/Verbrauch. Nachts bei 0Watt "Erzeugung" wird der Verbrauch um Faktor 10 zu hoch angegeben.

**Comment by Lokverfuehrer** [comment]
Bei mir in einer äußerst simplen Konfiguration wird der Verbrauch auch falsch angezeigt. Der Verbrauch ist identisch mit der PV-Erzeugung obwohl aus dem Netz Leistung entnommen wird. 

Datenquellen: Inverterleistung sowie Discovergy-Zähler

![image](https://user-images.githubusercontent.com/18364992/218308623-618d4e6d-d514-4c09-89a6-28e5753b0da8.png)
<img width="1138" alt="image" src="https://user-images.githubusercontent.com/18364992/218308697-40f7e3a4-c30d-4fdb-8201-dfb69472ba26.png">
![image](https://user-images.githubusercontent.com/18364992/218308720-205aa72e-19b7-44a1-a11a-2d130eb9e16f.png)

**Comment by SKB-CGN** [comment]
Könnte ich dazu bitte noch die Werte aus dem Objekt Browser bekommen?

Danke!

**Comment by jenskaschub** [comment]
Also jetzt bei null Ertrag der PV ist das entpsrechende Objekt genau 0.
Verbrauch un Netz sind bei mir der gleiche Datenpunkt mit eben der aktuellen Wattzahl (aus einem ESP Stromzählerablesegerät).
![image](https://user-images.githubusercontent.com/59324885/218386183-246994cf-f893-4830-9ab3-22e9a432450c.png)

**Comment by SKB-CGN** [comment]
Wie ist der Adapter eingestellt? Bitte einen Screenshot der Konfig für Solar, Netz und Verbrauch.

**Comment by jenskaschub** [comment]
![image](https://user-images.githubusercontent.com/59324885/218396055-7320d2dc-05eb-45f6-9ddf-f9b2a44cf44c.png)
![image](https://user-images.githubusercontent.com/59324885/218396208-4b7a8a7d-7153-4701-bccd-86587426d8c0.png)
![image](https://user-images.githubusercontent.com/59324885/218396260-94342269-9696-4cc5-866f-985007a85e1b.png)

und jetzt erzeugt die PV:
![image](https://user-images.githubusercontent.com/59324885/218396388-f4aae216-12d6-47ec-b90c-e50cdba74edd.png)

**Comment by SKB-CGN** [comment]
Jetzt sieht es doch gut aus, soweit ich das beurteilen kann.

Ich habe noch einmal etwas angepasst - jetzt sollte es klappen. Die Zahlen wurden nicht addiert, sondern verkettet. Daher stand dort statt 561W eben 5610W, weil ein Wert 0 war/ist.

Also, einfach noch einmal drüber installieren und nochmal schauen, bitte.

**Comment by jenskaschub** [comment]
passt. Danke

**Comment by SKB-CGN** [comment]
Prima, danke.

@aquapro Wenn Du Zeit findest, bitte auch nochmal drüber installieren und schauen.

**Comment by aquapro** [comment]
@SKB-CGN sorry, ich war dienstlich unterwegs und hatte nicht die Zeit zu testen. Eben kurz installiert und es sieht auf den ersten Blick besser aus. Ich schau morgen, wenn die PV einspeist, ob es komplett funktioniert.
Jetzt wird auf jeden fall schon etwas angezeigt, auch wenn 2 PV vorhanden sind, was ja vorher nicht ging. Hier ein aktueller Screen:
![image](https://user-images.githubusercontent.com/16852170/219966279-038368db-77a7-412c-bbfd-ccaaaaaa0d34.png)

**Comment by aquapro** [comment]
@SKB-CGN sieht auch mit PV Einspeisung besser aus.

Danke!
