### ISSUE TITLE
Bekomme den Adapter nicht ans Laufen JS_CONTROLLER_STOPPED

### ISSUE THREAD

**Issue by paba42** [SKB-CGN/ioBroker.energiefluss#114]
Hallo!

Ich bekomme den Adapter nicht ans laufen.
Ich kann in der Konfiguration alle Datenpunkte erfassen, aber der Adapter startet nicht. 
Im Protokoll sehe ich folgendes:

`host.raspi4iobraspi | 2023-02-11 21:30:14.296 | error | instance system.adapter.energiefluss.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.raspi4iobraspi | 2023-02-11 21:30:14.296 | error | Caught by controller[0]:     at internal/main/run_main_module.js:17:47
host.raspi4iobraspi | 2023-02-11 21:30:14.296 | error | Caught by controller[0]:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
host.raspi4iobraspi | 2023-02-11 21:30:14.295 | error | Caught by controller[0]:     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
host.raspi4iobraspi | 2023-02-11 21:30:14.295 | error | Caught by controller[0]:     at Module.load (internal/modules/cjs/loader.js:863:32)
host.raspi4iobraspi | 2023-02-11 21:30:14.295 | error | Caught by controller[0]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
host.raspi4iobraspi | 2023-02-11 21:30:14.295 | error | Caught by controller[0]:     at Module._compile (internal/modules/cjs/loader.js:963:27)
host.raspi4iobraspi | 2023-02-11 21:30:14.294 | error | Caught by controller[0]:     at wrapSafe (internal/modules/cjs/loader.js:915:16)
host.raspi4iobraspi | 2023-02-11 21:30:14.294 | error | Caught by controller[0]: SyntaxError: Unexpected token '.'
host.raspi4iobraspi | 2023-02-11 21:30:14.294 | error | Caught by controller[0]: 		                ^
host.raspi4iobraspi | 2023-02-11 21:30:14.293 | error | Caught by controller[0]: 		if (this.config?.car_charge) {
host.raspi4iobraspi | 2023-02-11 21:30:14.293 | error | Caught by controller[0]: /opt/iobroker/node_modules/iobroker.energiefluss/main.js:760
host.raspi4iobraspi | 2023-02-11 21:30:13.925 | info | instance system.adapter.energiefluss.0 started with pid 29840
host.raspi4iobraspi | 2023-02-11 21:29:58.460 | info | Restart adapter system.adapter.energiefluss.0 because enabled`

`node -v
v12.22.12
npm -v
7.5.2
"js-controller": 4.0.24
lsb_release -a
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye
`

**Comment by SKB-CGN** [comment]
Js-Controller bitte updaten.

**Comment by paba42** [comment]
Hab ich, mehr geht aber nicht:

`iobroker upgrade self
Host    "raspi4iobraspi" is up to date.
`

**Comment by SKB-CGN** [comment]
Welche Version hast du denn?

**Comment by paba42** [comment]
"js-controller": 4.0.24

**Comment by SKB-CGN** [comment]
Ich kann da nur raten. Ich würde ioBroker mal neustarten und den Adapter nochmals installieren.

**Comment by paba42** [comment]
Ich habs jetzt zum laufen bekommen.
Habe Node.js auf 16 und npm auf 8 upgedated und es geht jetzt.

**Comment by paba42** [comment]
Nach Update auf
`node -v
v16.19.0
npm -v
8.19.3
`

**Comment by tilly001** [comment]
Ich habe auch das Problem das der Adapter nicht startet. 
Node.js = 16.19.0
NPM = 8.19.3

`URIError: Failed to decode param '%web_protocol%://192.168.178.:%web_port%/energiefluss/index.html'
    at decodeURIComponent (<anonymous>)
    at decode_param (/opt/iobroker/node_modules/express/lib/router/layer.js:172:12)
    at Layer.match (/opt/iobroker/node_modules/express/lib/router/layer.js:148:15)
    at matchLayer (/opt/iobroker/node_modules/express/lib/router/index.js:585:18)
    at next (/opt/iobroker/node_modules/express/lib/router/index.js:226:15)
    at compression (/opt/iobroker/node_modules/compression/index.js:220:5)
    at Layer.handle [as handle_request] (/opt/iobroker/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/opt/iobroker/node_modules/express/lib/router/index.js:328:13)
    at /opt/iobroker/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/opt/iobroker/node_modules/express/lib/router/index.js:346:12)`

Gibt es dazu eine Idee?
