### ISSUE TITLE
Restzeit - Akku Kapa als Datenpunkt

### ISSUE THREAD

**Issue by Mutanten** [SKB-CGN/ioBroker.energiefluss#115]
Könntest du zusätzlich die Akkukapazität als Datenpunkt ausweise?
Die Restkapa ändert sich laufend, da müsste man aktuell immer nachtragen um die genaue Restzeit zu erhalten.

**Comment by SKB-CGN** [comment]
Der Adapter berechnet nur die Zeit.

Was möchtest Du denn mit der Kapazität?

**Comment by Mutanten** [comment]
hm, entweder bin ich falsch oder du

Kapa in Wh : Leistung in W = Zeit in h
warum sollte man den sonst hier die Kapa des Speichers eintragen?
<img width="518" alt="Kapa" src="https://user-images.githubusercontent.com/116433119/218315329-4f5a7645-5f45-4bec-a1b1-5206107f2998.png">

**Comment by SKB-CGN** [comment]
Ja, die Kapazität trägt man dort ein, damit der Adapter die Zeit berechnen kann, wie lange der Akku mit dem aktuellen Verbrauch noch hält.

Wofür benötigst Du dann die Kapazität?

**Comment by Mutanten** [comment]
weine Frage war, ob man nicht genau das automaisieren könnte. Anstatt den Wert manuell einzutragen, da sich die tatsächlich verfügbare Kapa des Speichers sich täglich verringert, wäre es schön wenn das automatisch nachgeführt würde, eben genau über eine Datenpunkt. Ich glaube du hattest meine Anliegen nicht verstanden.

**Comment by SKB-CGN** [comment]
Verstehe ich auch immer noch nicht.

Hier ist die max Kapazität einzutragen, damit die Zeit berechnet werden kann.

**Comment by Mutanten** [comment]
Ein Speicher hat z.B. 10kwh nutzbare Kapa wenn er neu ist. Diese 10kWh verringern sich durch die normale Alterung des Speichers. Ich kann diese Alterung bei meinem System auslesen und dann eben die tatsächliche Restkapa berechnen. Diese würde ich dann gerne ganau dort über einen Datenpunkt eintragen wollen. Somit stimmt dann auch die errechnete Zeit.

**Comment by SKB-CGN** [comment]
Den Wert kannst Du ja dann neu eintragen.

Wenn Du dies jährlich machst, sollte das wohl ausreichend sein.

**Comment by Mutanten** [comment]
automatisch wäre halt schön gewsen
