### ISSUE TITLE
Vorschlag: Strommenge ebenfalls visualisieren

### ISSUE THREAD

**Issue by jenskaschub** [SKB-CGN/ioBroker.energiefluss#116]
Hallo,
ist es möglich die Menge ebenfalls zu visualisieren?
Also zum Beispiel über die Länge der "Snake" oder über die Farbe/Deckkraft je nach Höhe der Wattzahl.
Ein schneller Blick auf meinen Energiefluss suggeriert mir, Netzbezug und Erzeugung gleich sind, obwohl mein Balkonkraftwerk grade 5W liefert und der Netzbezug bei 2000W ist.

**Comment by SKB-CGN** [comment]
Aktuell ist dies über die automatische Animation anhand der Geschwindigkeit möglich.

**Comment by jenskaschub** [comment]
Auch auf Erzeugerseite? Ich sehe da nur einen Unterschied bei den Verbrauchern

**Comment by SKB-CGN** [comment]
Aktuell auf der Verbraucherseite.

**Comment by SKB-CGN** [comment]
Lasse ich mal so offen.
