### ISSUE TITLE
Anbindung PV-Speicher

### ISSUE THREAD

**Issue by SpitfireXP** [SKB-CGN/ioBroker.energiefluss#117]
Hi.
bei mir gibt es das Problem, das der Speicher wenn er durch die PV-Anlage geladen wird, den Bezug von Netzpunkt hat.
Da ich einen DC-Speicher habe, wäre eigentlich auch die Visualisierung nur mit einer Linie zur PV-Anlage richtiger.
Denn der Speicher entlädt sich auch über den Wechselrichter der PV-Anlage in das Haus.
Wäre eine Anpassung an DC oder AC-gekoppelte Speicher nicht vielleicht sinnvoller?

![image](https://user-images.githubusercontent.com/5896226/218314515-0b740970-b866-477b-b5e8-514dabd69e2e.png)

**Comment by christoph-spielmann** [comment]
Ich habe auch einen DC-Speicher (wie wohl alle hier). Der Speicher kann im Ausnahmefall auch aus dem Netz geladen werden und die Batterie kann sich auch in das Netz entladen. Daher ist die Verbindung zwischen Batterie und Netz aus meiner Sicht in Ordnung.

Dass bei Dir beim Laden der Batterie eine Animation zum Netz angezeigt wird, deutet auf ein Einstellungsproblem auf Deiner Seite hin. Bei mir wird das Laden der Batterie von den PV-Modulen korrekt dargestellt.

**Comment by SKB-CGN** [comment]
Du kannst auch den Datenpunkt des Wechselrichters im Akku-Element angeben, wenn Dir der Wert besser gefällt. Ein Hausverbrauch mit - im Vorzeichen ist deutet, wie @christoph-spielmann schon sagte, auf ein Konfigurationsproblem hin.

**Comment by riruf** [comment]
Hallo ich habe hier ein ähnliches Problem mit 2 PV Erzeugungen.
Sobald die Ladeleistung des Akkus größer ist als die max. Leistung einer Solaranlage zeigt er die Flussrichtung vom Netz zum Akku. 
Ist die Ladeleistung zum Akku kleiner als die erzeugte Leistung einer Solaranlage kommt der Fluss von der PV zum Akku. 

Ich denke das passt so nicht. 
Vielleicht kannst du das überprüfen und anpassen.
Grüße
![image](https://user-images.githubusercontent.com/66549456/218962933-37de582f-528f-46cd-ba62-5122c17f371b.png)

**Comment by SKB-CGN** [comment]
Und, was soll ich da anpassen?

Wie sieht denn die Ladung des Akkus aus? Wie sieht die Konfiguration aus?

**Comment by riruf** [comment]
Hi
die Konfiguration bei mir sieht so aus wie im Bild.  Ich hab 2 Wechselrichter an einen Gen24 der alles steuert ist ein DC Speicher angebunden. Der Wechselrichter ist ein Multiflow und bindet den anderen Wechselrichter AC seitig mit ein und lädt auch mit den Strom die Batterie.

Bei DC Anlagen wird generell der Speicher über den Wechselrichter geladen.  Da könnte man die Verbindung Speicher Netz sogar kappen. Denn wenn bei meiner Anlage mal "zwangsweise" über Netz geladen wird läufts über den Wechselrichter zuerst.

Mir würde hier schon eine Option "Hacken" reichen DC Speicher wo dann immer der Ladeflow  vom Wechselrichter kommt.

Dann gebe es auch keine Problem mit AC Speichern da würde dann alles beim alten bleiben.

Übrigends du machst de tolle Arbeit.

**Comment by SKB-CGN** [comment]
Der Adapter unterstützt generell PV's, Akkus, Autos, Balkonkraftwerke und und und.
Jeden kann und werde ich es nicht recht machen können - habe aber den Fehler mit der Ladung aus dem Netz gefunden.

Die Version geht am Nachmittag online. Weitere Dinge ändere ich aktuell nicht ab, weil nie jemand zufrieden sein würde, wo nun sein Wechselrichter ist. 

Eine Konfiguration des Adapters kann ich IM Bild nicht erkennen.

**Comment by riruf** [comment]
OK danke
ich versteh schon das man hier nicht alles abdecken kann.
Warte auf die neue Version.
GRüße

**Comment by SKB-CGN** [comment]
Es gibt ein Update. Bitte einfach mal drüber installieren.

**Comment by riruf** [comment]
funktioniert jetzt einwandfrei

**Comment by SKB-CGN** [comment]
Hallo,
tut mir Leid, wenn der aktuelle "Energiefluss" Adapter deine Wünsche nicht berücksichtigen konnte.

Ich habe einen neuen Adapter, den "Energiefluss-erweitert", entwickelt, der möglicherweise Deinen Wünsche bereits berücksichtigt bzw. noch berücksichtigen wird.

Du kannst Ihn gerne ausprobieren.

Forum:
https://forum.iobroker.net/topic/64734/test-adapter-energiefluss-erweitert-v0-0-x-github-latest

Github Link:
https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert

Schau mal rein ;)
