### ISSUE TITLE
Zukünftige Erweiterungen

### ISSUE THREAD

**Issue by SpitfireXP** [SKB-CGN/ioBroker.energiefluss#118]
Erstmal: Tolles Projekt.
Hätte hier noch ein paar Ideen die vielleicht sinnvoll wären:
Wenn es hier falsch ist, bitte löschen.

Es wäre super wenn man auch für andere Verbrauche eine Visualisierung der 0-100% hätte.
So könnte man bei einer Wärmepume anzeigen lassen wie viel Leistung sie gerade bringt.
Ebenso wäre es sehr cool, wenn man die einzelnen Knoten anklicken könnte um auch eine Historie der Punkte zu kommen.
Oder zu einem chart welches man selbst erstellen kann, oder Grafana oder oder oder.

**Comment by SKB-CGN** [comment]
Verstehe nicht, was eine prozentuale Anzeige der Leistung für Vorteile hat.

Weitere Verlinkungen sind aktuell nicht vorgesehen.

Es ist ein Energiefluss und kein History Adapter o.ä.

**Comment by SKB-CGN** [comment]
Das ist aber alles nicht Sinn des Adapters. Dieser zeigt Energieflüsse an und prozentuale Ladungen.

Prozentuale Verbräuche machen in meinen Augen auch wenig Sinn, denn ein Verbrauch wird in Watt oder kWatt gemessen - nicht in %.
Das wäre wieder Statistik, wofür der Adapter nicht gedacht ist.

Du kannst gerne eine Diskussion auf https://forum.iobroker.net eröffnen und schauen, was Andere dazu meinen.

Du möchtest also einen Link pro Element haben, der dich irgendwohin leitet?
Das ließe sich einbauen.

**Comment by SpitfireXP** [comment]
Ein Link würde genügen meine ich.
Der kann dann ja auf eine Seite in Grafana oder sonstwohin zeigen.
Evtl. so als Popupfenster das mir dann den Verlauf anzeigt und fertig.
Das könnte man dann auch für die Prozentuale anzeige nutzen.
Klickst auf die Wallbox und es kommt eine Grafanaseite die dir Verlauf und Auslastung zeigt.
Klickst auf das X bzw. zurück und du bist wieder auf deinem Adapter.

**Comment by SKB-CGN** [comment]
Könnte man so überlegen. Schaue ich mir an.

**Comment by SpitfireXP** [comment]
Vielen Dank schonmal das du dir das ansiehst.

Was mir gerade einfällt...
Die Auslastungsanzeige hast du im Grunde ja schon.
Die Batterie zeigt ja ihren Füllstand an, wenn man es möchte.
Das kann man ja eigentlich dafür genauso nutzen.
Bei Eine Wärmepumpe könnte ich so die Auslastung der Pumpe anhand Leistungsaufnahme oder Wärmeerzeugung anzeigen.
Den Prozentualen wert müsste man sich halt über einen Datenpunkt erzeugen wenn man ihn nicht direkt aus dem Gerät ziehen kann.
Oder die Ladeleistung eine PV-Überschussladung bi der Wallbox.
Da müsste man sich halt entscheiden was man will.
Akkustand des Autos, oder Ladeleistung in %

**Comment by SKB-CGN** [comment]
Hallo,
tut mir Leid, wenn der aktuelle "Energiefluss" Adapter deine Wünsche nicht berücksichtigen konnte.

Ich habe einen neuen Adapter, den "Energiefluss-erweitert", entwickelt, der möglicherweise Deinen Wünsche bereits berücksichtigt bzw. noch berücksichtigen wird.

Du kannst Ihn gerne ausprobieren.

Forum:
https://forum.iobroker.net/topic/64734/test-adapter-energiefluss-erweitert-v0-0-x-github-latest

Github Link:
https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert

Schau mal rein ;)
