### ISSUE TITLE
Feature Request: Hintergrundfarbe unter Farbeinstellungen + Unendlich definierbare Elemente ohne Watt Zwang

### ISSUE THREAD

**Issue by ckoeber83** [SKB-CGN/ioBroker.energiefluss#119]
Hi,

super Adapter 👍

Ich würde mir für das nächste Release die Möglichkeit wünschen, unter den Adapter Farbeinstellungen auch eine Hintergrundfarbe für den Instanz Link (e.g. http://iobroker:8082/energiefluss/index.html?instance=0) festlegen zu können. Nicht immer ist da Transparent und damit per default Weiß gewünscht. Die Farben der Beschriftung und der Symbole lassen sich ja auch anpassen.

Dies könnte man zwar auch in der style.css unter `/opt/iobroker/node_modules/iobroker.energiefluss/www/style.css` anpassen, wäre aber beim nächsten Adapter Update ggf. überschreiben.

---

Zudem würde ich mir wünschen, mehr als 10 oder 11 benutzerdefinierte Elemente zu haben. (_ggf. über Add Button weitere hinzufügen unter den Haupteinstellungen_).
Auch der Zwang nach der Watt/kW Einheit ist manchmal unglücklich.

Bsp. ich habe eine USV und würden den USV Akku gerne als Verbraucher darstellen mit % Akkuladung und Leistung/Last in Watt/kW.
Aktuell nutze ich dafür die "Akku laden und entladen" Funktion in den Haupteinstellungen. Aktuell kann ich da aber auch nur einen Akku anlegen, was bei mir aktuell kein Problem ist, da keine PV mit Batteriespeicher. (_ggf. über Add Button weitere hinzufügbar machen_)

![grafik](https://user-images.githubusercontent.com/52466072/218334026-fa676679-fc5e-4b1e-a628-372194a12b6e.png)

Auch wird mir der Stromfluss in die falsche Richtung angezeigt, da es sich ja hier nicht um einen PV-Speicher handelt mit positiv/negativ Werten, welcher mit Strom für alle meine Verbraucher bereitstellt: (_Sollte vom Verbraucher, zum Akku und nicht andersrum_)
![grafik](https://user-images.githubusercontent.com/52466072/218334594-93b457d0-4caa-431e-b738-78c75452f79c.png)

Also ein benutzerdefiniertes Element mit % Datenpunkt und Füllfarbe der Werte Box entsprechend des Ladezustandes + weiteren Datenpunkt mit Leistungsbezug in Watt oder kW und das alles als normaler Verbraucher ohne Verknüpfung zum Netzbetreiber.

Das wäre super 👍
VG

**Comment by SKB-CGN** [comment]
Die Hintergrundfarbe kann ich gerne anpassbar machen. Meist landet die Seite eh in einem Frame einer weiteren Visualisierung - daher war transparent das meist-geforderte.

Weitere Elemente kannst Du mit mehreren Instanzen selbst anlegen.

Aktuell sind 11 Elemente das Maximum, was auf einen Monitor/Tablet/Handy-Display passt.

Eine Darstellung für eine USV ist aktuell nicht vorgesehen.

**Comment by thorstenman** [comment]
Transparente Hintergrundfarbe wäre wirklich super. Danke vorab, dass du das aufgreifst!

**Comment by SKB-CGN** [comment]
> Transparente Hintergrundfarbe wäre wirklich super. Danke vorab, dass du das aufgreifst!

Die Farbe ist aktuell "transparent". In einem Frame dargestellt übernimmt dieser also den Hintergrund des Hauptseite. Wenn das nicht der Fall ist, Einstellungen des Frames überprüfen.

**Comment by SKB-CGN** [comment]
Bitte die neue Version einmal ausprobieren. Das geforderte Thema Deines Beitrags wurde hier berücksichtigt!

**Comment by thorstenman** [comment]
Welches Thema hast du adressieren können? Neue Version ist installiert: Stelle noch kein geändertes Verhalten fest hinsichtlich Transparent, Symbol oder Restanzeige. Danke dir!

**Comment by SKB-CGN** [comment]
Musst du ja auch einstellen.

Bei dir stand ja nur Transparenz.

**Comment by thorstenman** [comment]
Farbe habe ich hinterlegt. Meine Annahme davor war, dass bei "Transparenz" die Objektfarbe des Hintergrunds zieht. Der ist bei mir schwarz-grau. Es blieb (und bleibt aber weiterhin) weiß. Habe ich einen Denkfehler. 

Restanzeige am besten ans Objekt für die Batterie kleben?

**Comment by SKB-CGN** [comment]
Die Elemente haben eine eigene Füllfarbe, die man angeben kann.

Warum sollte der Text an das Element geklebt sein? Es ist dort positioniert, wo es ist.
Verstehe nicht, was gemeint ist.

**Comment by SKB-CGN** [comment]
Hallo,
tut mir Leid, wenn der aktuelle "Energiefluss" Adapter deine Wünsche nicht berücksichtigen konnte.

Ich habe einen neuen Adapter, den "Energiefluss-erweitert", entwickelt, der möglicherweise Deinen Wünsche bereits berücksichtigt bzw. noch berücksichtigen wird.

Du kannst Ihn gerne ausprobieren.

Forum:
https://forum.iobroker.net/topic/64734/test-adapter-energiefluss-erweitert-v0-0-x-github-latest

Github Link:
https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert

Schau mal rein ;)
