### ISSUE TITLE
Installation funktioniert nicht.

### ISSUE THREAD

**Issue by totocotonio** [SKB-CGN/ioBroker.energiefluss#12]
Hi,
ich kann es nicht inst. folgender Fehler kommt im Log.

`<html>
<body>

host.iobroker | 2022-08-21 17:35:09.592 | info | iobroker exit 25
-- | -- | -- | --
host.iobroker | 2022-08-21 17:35:08.576 | error | iobroker host.iobroker Cannot install SKB-CGN/ioBroker.energiefluss#0b8de315c689a081ae51b3455e92cdacdb673a93: 254
host.iobroker | 2022-08-21 17:35:08.556 | info | iobroker npm ERR! A complete log of this run can be found in:npm ERR! /home/iobroker/.npm/_logs/2022-08-21T15_35_08_544Z-debug.log
host.iobroker | 2022-08-21 17:35:08.539 | info | iobroker npm ERR! enoent ENOENT: no such file or directory, access '/opt/iobroker/node_modules/iobroker.javascript/node_modules/core-util-is'npm ERR! enoent This is related to npm not being able to find a file.npm ERR! enoent
host.iobroker | 2022-08-21 17:35:08.534 | info | iobroker npm ERR! syscall accessnpm ERR! path /opt/iobroker/node_modules/iobroker.javascript/node_modules/core-util-isnpm ERR! errno -2
host.iobroker | 2022-08-21 17:35:08.533 | info | iobroker npm ERR! code ENOENT
host.iobroker | 2022-08-21 17:35:08.528 | info | iobroker
host.iobroker | 2022-08-21 17:35:08.527 | info | iobroker npm WARN http-cookie-agent@1.0.4 requires a peer of tough-cookie@^4.0.0 but none is installed. You must install peer dependencies yourself.
host.iobroker | 2022-08-21 17:35:06.857 | info | iobroker NPM version: 6.14.16Installing SKB-CGN/ioBroker.energiefluss#0b8de315c689a081ae51b3455e92cdacdb673a93... (System call)
host.iobroker | 2022-08-21 17:35:06.825 | info | iobroker npm WARN checkPermissions Missing write access to /opt/iobroker/node_modules/iobroker.javascript/node_modules/core-util-isnpm WARN checkPermissions Missing write access to /opt/iobroker/node_modules/iobroker.javascript/node_modules/dewpointnpm WARN checkPermissions Missing write access to /opt/iobroker/node_modules/iobroker.javascript/node_modules/immediatenpm WARN checkPermissions Missing write access to /opt/iobroker/node_modules/iobroker.javascript/node_modules/inheritsnpm WARN checkPermissions Missing write access to /opt/iobroker/node_modules/iobroker.javascript/node_modules/moment-duration-formatnpm WARN checkPermissions Missing write access to /opt/iobroker/node_modules/iobroker.javascript/node_modules/node-wolnpm WARN checkPermissions Missing write access to /opt/iobroker/node_modules/iobroker.javascript/node_modules/pakonpm WARN checkPermissions Missing write access to /opt/iobroker/node_modules/iobroker.javascript/node_modules/process-nextick-argsnpm WARN checkPermissions Missing write access to /opt/iobroker/node_modules/iobroker.javascript/node_modules/safe-buffernpm WARN checkPermissions Missing write access to /opt/iobroker/node_modules/iobroker.javascript/node_modules/setimmediatenpm WARN checkPermissions Missing write access to /opt/iobroker/node_modules/iobroker.javascript/node_modules/util-deprecatenpm WARN checkPermissions Missing write access to /opt/iobroker/node_modules/iobroker.javascript/node_modules/yallistnpm WARN checkPermissions Missing write access to /opt/iobroker/node_modules/iobroker.javascript/node_modules/lru-

</body>
</html>`

**Comment by SKB-CGN** [comment]
Der Fehler steht doch schon dabei:
Missing write access

Im Verzeichnis darf iobroker selbst wohl nicht schreiben. Bitte hier mal schauen.

**Comment by totocotonio** [comment]
> Edit: Du musst wahrscheinlich die Abhängigkeit Cookie manuell installieren.

Was heisst das denn?

**Comment by SKB-CGN** [comment]
Schau dir doch die Fehlermeldung an. Dort steht, was fehlt.

**Comment by totocotonio** [comment]
Ok lass es einfach sein!

Tschau

**Comment by SKB-CGN** [comment]
Wo liegt denn die Schwierigkeit, zu befolgen, was in der Fehlermeldung liegt?

Das liegt sicherlich nicht an dem Adapter :-)
