### ISSUE TITLE
Feature Request: Visualisierung von Einzelwerten

### ISSUE THREAD

**Issue by menkej** [SKB-CGN/ioBroker.energiefluss#121]
Sehr schöner Adapter! Ich bin kein Freund von VIS und Co, aber eine Darstellung dieser Art hat sogar die Frau interessiert... ;-)

Nach erstem Test gingen mir zwei Dinge durch den Kopf:

1. Darstellung ist per Default sehr "ausladend". Kompakter geht nur indem die Batterie rangerückt wird. Schön wäre, wenn man den Abstand der Objekte insgesamt reduzieren könnte. Vielleicht habe aber nur eine Einstellung übersehen...
2. Cool wäre, wenn man Einzelwerte ähnlich konfigurativ mit einblenden könnte. Beispiele:
 * Erwartete PV Resterzeugungsmenge heute
 * Forecast für morgen/übermorgen (bekommt man ja z.B. über den pvforecast Adapter, oder in meinem Falle direkt aus dem Kostal Adapter
 * Stromverbrauch des heutigen Tages
 * Ertrag heute

Vielleicht ist ja ein Impuls dabei.

**Comment by SKB-CGN** [comment]
Danke für deine Rückmeldung.

Die linke Seite lässt sich ja durch das Slim-Design verkleinern - die rechte leider (noch) nicht, weil zwischen Produktion und den Elementen oberhalb vom Haus/Verbrauch noch Elemente sein können.
Dies könnte man ggf. Erweitern, wenn man die Elemente nicht nutzt.

Du kannst aktuell bei Produktion1-3, Verbrauch und Netzbezug einen weiteren Datenpunkt im Wechsel darstellen:

![2023-02-14 16_24_12-Window](https://user-images.githubusercontent.com/58603329/218781625-831672f0-5b10-469b-9e4a-e11b49191184.png)

**Comment by redseasix** [comment]
Vorschlag dazu:
die Möglichkeit zu schaffen, das wenn man auf ein Element anklickt z.B. das Netzelement, das man hinter dem klick eine Link legen kann, um ein Popup Fenster damit zu öffnen oder eine eine separate Seite. auf die man alle zusätzlichen Infos hinterlegen kann, wie  in dem Beispiel: Wirkleistung eingespeist/bezogen/ L1-L3/I1-I3/P1-P3 usw.

**Comment by SKB-CGN** [comment]
Hallo,
tut mir Leid, wenn der aktuelle "Energiefluss" Adapter deine Wünsche nicht berücksichtigen konnte.

Ich habe einen neuen Adapter, den "Energiefluss-erweitert", entwickelt, der möglicherweise Deinen Wünsche bereits berücksichtigt bzw. noch berücksichtigen wird.

Du kannst Ihn gerne ausprobieren.

Forum:
https://forum.iobroker.net/topic/64734/test-adapter-energiefluss-erweitert-v0-0-x-github-latest

Github Link:
https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert

Schau mal rein ;)
