### ISSUE TITLE
Linie von und zum Akku werden nicht mehr dargestellt

### ISSUE THREAD

**Issue by srwilli1** [SKB-CGN/ioBroker.energiefluss#122]
Die Animation zum Akku und weg vom Akku wird plötzlich nicht mehr dargestellt, Wert im Akku Kasten ist 0. Hat bis vorhin noch funktioniert. Ich habe nichts verändert. Hinterlegte Objekte geben jedoch Werte an.

![energiefluss](https://user-images.githubusercontent.com/91827670/218771426-6c70bd66-3fc0-4272-9e56-d3d1605d9dbe.JPG)

**Comment by srwilli1** [comment]
![akku](https://user-images.githubusercontent.com/91827670/218771988-02e01545-dddd-42d8-8ec4-d9d85ca0675f.JPG)
![akku2](https://user-images.githubusercontent.com/91827670/218771994-800a252a-8c55-46b2-bc6f-5fa91128a78c.JPG)

**Comment by SKB-CGN** [comment]
Bitte die Version noch einmal drüber installieren.

Ich denke, das wird helfen - in der Version von vor 2 Tagen war ein Fehler, sobald der Adapter neu startet oder die Konfiguration neu einliest.

**Comment by srwilli1** [comment]
Hat geklappt.

Übrigens vielen Dank für den tollen Adapter!

**Comment by SKB-CGN** [comment]
Prima, freut mich, wenn's gefällt 😉

Bitte das Issue dann schließen, wenn kein Fehler mehr vorliegt!
