### ISSUE TITLE
Adapter nicht (mehr) in der sources-dist.json

### ISSUE THREAD

**Issue by volkerrichert** [SKB-CGN/ioBroker.energiefluss#123]
Leider scheint der Adapter nicht mehr in den offiziellen Repositories (stable & beta) gelistet zu sein. Kann er wieder aufgenommen werden?

**Comment by SKB-CGN** [comment]
Ist derzeit beantragt. Weiss leider nicht, wie lange das dauert.

**Comment by volkerrichert** [comment]
Ah, ok. Habe das nur für deinen 2 Adapter gesehen. Und das war ne längere Diskussion ;-)

**Comment by SKB-CGN** [comment]
Die Wallbox? Ja, wegen dem Namen ... Nunja. Der wurde auch noch nicht aufgenommen - zumindest sind die PR noch offen.
