### ISSUE TITLE
Adapter startet nicht

### ISSUE THREAD

**Issue by octane321** [SKB-CGN/ioBroker.energiefluss#124]
Hallo,

leider bekomme ich den Adapter nicht zum laufen.
Im Log (silly) erscheint folgendes:

`host.iobroker | 2023-02-15 12:34:37.411 | info | Restart adapter system.adapter.energiefluss.0 because enabled
host.iobroker | 2023-02-15 12:34:37.411 | error | instance system.adapter.energiefluss.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.iobroker | 2023-02-15 12:34:37.410 | error | Caught by controller[0]:     at internal/main/run_main_module.js:17:47
host.iobroker | 2023-02-15 12:34:37.410 | error | Caught by controller[0]:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
host.iobroker | 2023-02-15 12:34:37.410 | error | Caught by controller[0]:     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
host.iobroker | 2023-02-15 12:34:37.410 | error | Caught by controller[0]:     at Module.load (internal/modules/cjs/loader.js:863:32)
host.iobroker | 2023-02-15 12:34:37.410 | error | Caught by controller[0]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
host.iobroker | 2023-02-15 12:34:37.410 | error | Caught by controller[0]:     at Module._compile (internal/modules/cjs/loader.js:963:27)
host.iobroker | 2023-02-15 12:34:37.410 | error | Caught by controller[0]:     at wrapSafe (internal/modules/cjs/loader.js:915:16)
host.iobroker | 2023-02-15 12:34:37.410 | error | Caught by controller[0]: SyntaxError: Unexpected token '.'
host.iobroker | 2023-02-15 12:34:37.410 | error | Caught by controller[0]: 		                ^
host.iobroker | 2023-02-15 12:34:37.409 | error | Caught by controller[0]: 		if (this.config?.car_charge) {
host.iobroker | 2023-02-15 12:34:37.409 | error | Caught by controller[0]: /opt/iobroker/node_modules/iobroker.energiefluss/main.js:760
host.iobroker | 2023-02-15 12:34:37.303 | info | instance system.adapter.energiefluss.0 started with pid 29049
host.iobroker | 2023-02-15 12:34:37.176 | info | "system.adapter.energiefluss.0" enabled`

Eine Idee wo ich ansetzen könnte?

**Comment by SKB-CGN** [comment]
https://github.com/SKB-CGN/ioBroker.energiefluss/issues/114

**Comment by tilly001** [comment]
Ich habe auch das Problem das der Adapter nicht startet.
Node.js = 16.19.0
NPM = 8.19.3

`URIError: Failed to decode param '%web_protocol%://192.168.178.:%web_port%/energiefluss/index.html' at decodeURIComponent (<anonymous>) at decode_param (/opt/iobroker/node_modules/express/lib/router/layer.js:172:12) at Layer.match (/opt/iobroker/node_modules/express/lib/router/layer.js:148:15) at matchLayer (/opt/iobroker/node_modules/express/lib/router/index.js:585:18) at next (/opt/iobroker/node_modules/express/lib/router/index.js:226:15) at compression (/opt/iobroker/node_modules/compression/index.js:220:5) at Layer.handle [as handle_request] (/opt/iobroker/node_modules/express/lib/router/layer.js:95:5) at trim_prefix (/opt/iobroker/node_modules/express/lib/router/index.js:328:13) at /opt/iobroker/node_modules/express/lib/router/index.js:286:9 at Function.process_params (/opt/iobroker/node_modules/express/lib/router/index.js:346:12)`

Gibt es dazu eine Idee?

**Comment by SKB-CGN** [comment]
Web Adapter installiert?

**Comment by tilly001** [comment]
Ah ... okay ... das macht jetzt auch Sinn ... läuft

**Comment by octane321** [comment]
Nach Update meines Systems läuft er nun auch bei mir und ich mach mich mal ans Anpassen ran.

Vielleicht könntest du noch in der Doku darauf hinweisen, das eine (laufende) web-Instanz Voraussetzung ist und das auch hier der Port definiert wird (war mir anfangs nicht klar).
Auch welche Version von node und jscontroller benötigt wird, wäre zukünftig sicher für viele hilfreich.

Lieben Dank für deine ganzen Mühen!
