### ISSUE TITLE
Symbol innerhalb des festen Elementes "Solarproduktion" ändern 

### ISSUE THREAD

**Issue by Guenter-1953** [SKB-CGN/ioBroker.energiefluss#125]
Ich habe zwei Solaranlagen und eine Brennstoffzelle. Drei Adapter sind ja vorhanden. Nur sind bei den 3 Solaranlagen die Symbole vorgegeben. Ich würde gerne ein Symbol ändern in ein " fuel-cell " Symbol. Andere vielleicht in ein anderes. Ist das machbar? Wenn ja wo und wie? Oder sollte man dem User auch hier die Wahl / Änderung eines Symbols freigeben? 

https://user-images.githubusercontent.com/75438387/219121637-5d574d47-d466-4a3f-bbfb-14a7368c4935.png

code: 

M6 3V5H4C2.9 5 2 5.9 2 7V17C2 18.1 2.9 19 4 19V20C4 21.1 4.9 22 6 22H7C8.1 22 9 21.1 9 20V19H15V20C15 21.1 15.9 22 17 22H18C19.1 22 20 21.1 20 20V19C21.1 19 22 18.1 22 17H11V5H8V3H6M16 3V5H13V7H22C22 5.9 21.1 5 20 5H18V3H16M7 7V11H9L6 17V13H4L7 7M13 9V11H22V9H13M13 13V15H22V13H13Z

**Comment by SKB-CGN** [comment]
Das könnte man tatsächlich einfließen lassen.

Nehme ich mal mit auf - danke für den Vorschlag!

**Comment by SKB-CGN** [comment]
Bitte die neue Version einmal ausprobieren. Das geforderte Thema Deines Beitrags wurde hier berücksichtigt!

**Comment by Guenter-1953** [comment]
Vielen Dank. Funktioniert Super!
