### ISSUE TITLE
Energieeinheit KW oder Watt pro Verbraucher

### ISSUE THREAD

**Issue by rabbit6984** [SKB-CGN/ioBroker.energiefluss#126]
Hi,

Geiler Adapter das ist das was ich gesucht habe. Dafür vielen Dann

Ich hab nur ein Problem ich bekomme je nach Datenpunkt KW oder Watt also nicht immer die gleiche Einheit.

Wäre es möglich das man das irgendwie Pro Verbraucher einstellen kann auch mit dem Watt in KW umrechnen anstatt nur global?

Vielen Dank

**Comment by SKB-CGN** [comment]
Gibt es doch - rechte Seite bei den Checkboxen. Dort ist wählbar, ob die Quelle W oder kW ist.

**Comment by rabbit6984** [comment]
Hi, ich kann da nur eingeben oder der vmVerbrqucher vom Hausverbrquch abgezogen wird.


V3.4.0

Übersehe ich das irgendwo? Ich finde es nur auf der Einstellungsseite global für alle Objekte aber eben nicht pro Verbraucher

**Comment by SKB-CGN** [comment]
3.5.0 (2023-02-10)
- added third production point. If used, the Slim-Design is deactivated (#101)
- All values can be in W or kW. The adapter converts the values appropriately (#102)
- ...

**Comment by rabbit6984** [comment]
Sorry, da hab ich garnet geschaut. Wurde mir net als update angeboten.

Jetzt Update drauf und los.

Danke für die schnelle Reaktion

**Comment by SKB-CGN** [comment]
Adapter von Git zeigen nie Updates an.

Da muss man selbst gucken oder eben im ioBroker Forum - dort steht es auch immer im Beitrag des Adapters.

**Comment by rabbit6984** [comment]
Jup habs gemerkt
Vielen Dank

**Comment by rabbit6984** [comment]
So habs mal eingestellt.

Z.b meine Wallbox liefert KW also setze ich die checkbox

Mein Wechselrichter liefert Watt, also checkbox deaktiviert.

Was stelle ich den nun auf dem Tab "andere" ein.
Ich hab dort jetzt W und umrechnen deaktiviert.

Aber in der Anzeige steht dan  auch bei den Verbrauchern wo ich KW aktiviert habe steht als Einheit W

Sorry danke

**Comment by SKB-CGN** [comment]
Ah, stimmt, die Einheiten.

Du kannst alles in KW rechnen.

**Comment by rabbit6984** [comment]
Ok also

Bei den Verbrauchern angeben welche Geräte KW nutzen und im Register Andere
KW  sowie  W in KW umrechnen aktivieren.

So richtig?

Wäre cool für 3.6 das vllt auch Geräte in Watt ausgegeben werden weil kein ganzes KW zusammenkommt aber das ist natürlich nur Kosmetischer Natur.

Danke

**Comment by SKB-CGN** [comment]
Japp, genau.

Die Quelle sagt aus, wie die der Wert auf Watt kommt.

Dann Watt in kW oder eben nicht - dann die richtige Einheit und gut ist.

Das sollte so funktionieren.

**Comment by SKB-CGN** [comment]
Bitte Rückmeldung, ob es mit der Einstellung klappt.

**Comment by SKB-CGN** [comment]
Hallo,
tut mir Leid, wenn der aktuelle "Energiefluss" Adapter deine Wünsche nicht berücksichtigen konnte.

Ich habe einen neuen Adapter, den "Energiefluss-erweitert", entwickelt, der möglicherweise Deinen Wünsche bereits berücksichtigt bzw. noch berücksichtigen wird.

Du kannst Ihn gerne ausprobieren.

Forum:
https://forum.iobroker.net/topic/64734/test-adapter-energiefluss-erweitert-v0-0-x-github-latest

Github Link:
https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert

Schau mal rein ;)
