### ISSUE TITLE
Verbrauchsberechnung funktioniert nicht richtig

### ISSUE THREAD

**Issue by HSGEV** [SKB-CGN/ioBroker.energiefluss#127]
Ich habe einen SMA Wechselrichter und einen Energymeter von SMA. 

Die aktuell PV Leistung des Wechselrichters lese ich über Modbus (modbus.0.inputRegisters.30775_PV-Leistung) aus. So lange der Wechselrichter arbeitet werden die Werte richtig berechnet. Sobald der Wechselrichter ausgeht (Keine Sonne  :-)) gibt der Modbus Adapter für dieses Value den Wert "-2147483648" aus. 

Bei der Berechnung des Verbrauches kommt es jetzt du den Fehler, dass er mit bei reinem Netzbezug O Watt Verbrauch angezeigt. Ich denke mal dies liegt daran, weil intern mit dem negativen Wert des Wechselrichters gerechnet wird. In der Anzeige wird dieser nämlich richtigerweise mit Null angezeigt. 

![Bildschirm­foto 2023-02-16 um 20 08 33](https://user-images.githubusercontent.com/97755526/219464508-77da25ca-ba6b-48f0-b51a-7ba480285a0f.png)

Das Problem sollte behoben sein, wenn bei der Berechnung mit der PV Leistung eine Abfrage erfolgt, ob der Wert >=  Null ist.

**Comment by SKB-CGN** [comment]
Guter Einwand. Schaue ich mir an und melde mich zurück.

**Comment by rabbit6984** [comment]
Schließe mich an auch SMA wechselrichter.

Wenn man was testen kann einfach melden.

Grüsse und vielen dank

**Comment by SKB-CGN** [comment]
Bite einmal drüber installieren und Rückmeldung. Habe das mit > 0 implementiert.

**Comment by HSGEV** [comment]
Sieht gut aus und läuft. Danke dir.
