### ISSUE TITLE
Farbanpassung Netzwert wünschenswert, Farbeinstellung Schwellwert bei Auto fehlt

### ISSUE THREAD

**Issue by Markus-3** [SKB-CGN/ioBroker.energiefluss#128]
Hallo,
der Adapter ist schon sehr gut! Was mir noch aufgefallen ist:

Unter Farbeinstellungen und Element 11 Auto Aufladen kann die Farbe für den Schwellwert nicht eingetragen werden. Das wäre noch wünschenswert wenn dies wie bei den anderen Elementen noch möglich wäre.

Was die Visualisierung zudem noch deutlicher machen würde wäre wenn der Wert unter Netz farblich abhängig davon eingestellt werden könnte ob eingespeist (zB in grün) oder verbraucht (zB in rot) wird.

Aber das sind nur noch die feinheiten. Ansonsten ist das Ding und die welche das programmiert haben SPITZENKLASSE !!!!
Vielen Dank!

**Comment by SKB-CGN** [comment]
Hallo,
der Schwellenwert kann eingetragen werden, wenn das Element nicht als Auto benutzt wird. Macht ja sonst keinen Sinn.

Die Farbe für Bezug oder Einspeisung nehme ich einmal mit auf.

**Comment by Markus-3** [comment]
Hallo der der das Ding so gut programmiert hat ;)

der Schwellwert bezug würde für mich sinn machen da alle Teilnehmer die AUS sind (aber vielleicht stand by verbrauch haben) grau dargestellt werden können, ausser eben Auto. Alle die AN sind haben dann die Farbe rot. 
![Energie](https://user-images.githubusercontent.com/85412355/219660552-e96a85b6-939a-4932-a4f7-2a76a228e1c1.JPG)

**Comment by SKB-CGN** [comment]
Bitte die neue Version einmal ausprobieren. Das geforderte Thema Deines Beitrags wurde hier berücksichtigt!
