### ISSUE TITLE
Error Loading Config and Values V3.50

### ISSUE THREAD

**Issue by PhiDiWoe** [SKB-CGN/ioBroker.energiefluss#129]
Installierte Version 3.50 

Habe den IOBroker neu installiert, wie bisher davor auch die Installation per Github gemacht, mit der Version 3.5 bleibt das Fenster bei lading Config and Values hängen.

Die Datenquellen Liefern alle Daten und soweit auch logische Werte.
Neustarts des Adapers/ weitere Instanzen bringen keine Änderung

Die Installation ist fehlerfrei durchgelaufen

Errorlog seitens IOBorkoer ist leer, Web Adapter ist instlaliert und läuft

**Comment by SKB-CGN** [comment]
Dann mal ein

iobroker upload energiefluss

Im iobroker Verzeichnis und das Browser Fenster neuladen.

**Comment by PhiDiWoe** [comment]
![Energiefluss Error](https://user-images.githubusercontent.com/125668706/219684385-ab135c09-2748-455e-a954-72c9d9298568.jpg)
![Energiefluss Error_2](https://user-images.githubusercontent.com/125668706/219684397-e1117654-2904-4836-b1c5-b4adcfc261ef.jpg)

Instanz gestoppt, Upload durchgeführt, Instanz neu gestartet, leider immernoch kein Erfolg.

Gibt´s noch weitere Log´s in denen man nachsehen kann woran es hängt?

**Comment by SKB-CGN** [comment]
Steht der Web-Adapter auf **integrierte** Sockets oder **socket.io**?

Energiefluss funktioniert nur mit **Integriert**.

Was sagt die Browser-Konsole?

Testweise: http://<ip-iobroker>:<port>/energiefluss/ aufrufen.

Was sagt die Konsole da?

**Comment by PhiDiWoe** [comment]
Web umgestellt auf integriert, alle Adapter neu gestartet.

Leider immernoch der gleiche Zustand wie vorhin sowohl im IOBroker als auch direkt über den Browser "Loading Config and Values..."

Socket.io Adapter deaktiviert alles neu gestartet, immernoch das gleiche.

**Comment by SKB-CGN** [comment]
> Was sagt die Browser-Konsole?
> 
> Testweise: http://:/energiefluss/ aufrufen.
> 
> Was sagt die Konsole da?

**Comment by PhiDiWoe** [comment]
das Gleiche, scheint aber als ist der Adapter nicht richtig installiert, weil er auch im Browser nicht unter http://ip-iobroker:web-port aufgeführt ist

**Comment by SKB-CGN** [comment]
Was heisst denn "das Gleiche"? Fehlermeldungen per F12 anzeigen lassen und hier beschreiben.
Meine Glaskugel hat leider einen Sprung :)

**Comment by PhiDiWoe** [comment]
also nochmal alles gelöscht, und neu von Github installiert, alles ohne Fehler.

Adapter wird nicht unter http://ip-iobroker:web-port aufgeführt

**Comment by SKB-CGN** [comment]
**> Er erscheint nicht auf der Web-Seite? Das ist korrekt so, da sich dort nur Admin und VIS (die Hauptkomponenten von ioBroker) eintragen (können).**
> 


Testweise: http://ip-iobroker:web-port**/energiefluss/** aufrufen.

Vielleicht liest Du auch einmal ganz, was dort steht und nicht nur einzelne Sätze. Dann kann Dir auch geholfen werden.

**Comment by PhiDiWoe** [comment]
so der Haken bei "Reine Web-Sockets (iobroker.ws) verwenden" muss zwingend angehakt werden.

Jetzt läuft es. 
Danke für die Unterstützung
