### ISSUE TITLE
2.ter Erzeugungspunkt

### ISSUE THREAD

**Issue by guthubps1304** [SKB-CGN/ioBroker.energiefluss#13]
Installation und Konfiguration funktioniert einwandfrei !!! Gibt s die Möglichkeit einen 2.ten Erzeugungspunkt anzulegen und einen Addition der Erzeuger ?
Habe einen E3DC und einen zusätzlichen Wechselrichter, deshalb habe ich 2 Erzeugungsdatenpunkte - oder soll ich einfach einen eigen Datenpunkt erzeugen (Addition der beiden Punkte)?

Gruß Peter

**Comment by SKB-CGN** [comment]
Hallo Peter,
Der Adapter deckt nicht alle Eventualitäten ab. Daher wäre hier ein 2. Datenpunkt besser.

Aufwand gering - Ergebnis groß ;)

**Comment by guthubps1304** [comment]
Danke, kein Problem super Adapter!!!

⁣BlueMail for Android herunterladen ​

Am 22. Aug. 2022, 19:39, um 19:39, SKB-CGN ***@***.***> schrieb:
>Hallo Peter,
>Der Adapter deckt nicht alle Eventualitäten ab. Daher wäre hier ein 2.
>Datenpunkt besser.
>
>Aufwand gering - Ergebnis groß ;)
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/SKB-CGN/ioBroker.energiefluss/issues/13#issuecomment-1222694731
>You are receiving this because you authored the thread.
>
>Message ID:
***@***.***>

**Comment by SKB-CGN** [comment]
Freut mich.
Danke!

**Comment by SKB-CGN** [comment]
Dies ist nun auch seit Version 3.2.0 möglich
