### ISSUE TITLE
Akku gleichzeitig laden und entladen (AC) wird nicht angezeigt

### ISSUE THREAD

**Issue by Pali-33** [SKB-CGN/ioBroker.energiefluss#130]
Hallo,
zuerst: super Adapter, hat mir sehr viel Arbeit gespart. Vielen Dank!

Meinen Akku lade ich mit einem AC-Ladegerät mit PV-Überschuss.
Entladen wird mit einem extra Wechselrichter.
Die Werte/Datenpunkte für Energiefluss-Adapter sind jeweils der AC-Verbrauch des Ladegerätes und des Wechselrichters.
Es ist also möglich laden und gleichzeitig entladen.
Wenn aber das passiert, dass gleichzeitig laden und entladen wird, wird kein Energiefluss angezeigt (zwischen Akku und PV-Erzeugung). Wenn nur geladen oder nur entladen wird, wird auch Energiefluss richtig angezeigt.

Habe die neuste Version heute den 19.02.23 installiert.
Wäre es möglich das hier anzupassen, dass auch gleichzeitiges Laden und Entladen angezeigt wird?
Vielen Dank im Voraus.
Pali

**Comment by SKB-CGN** [comment]
Gleichzeitig laden und entladen macht eigentlich keinen Sinn.

Daher wird es nicht angezeigt.

**Comment by Pali-33** [comment]
Es ist nur ungewöhnlich, aber nicht sinnlos. 
Bin ich der einzige, der tagsüber die Lastspitzen von E-Herd von der Batterie "dämpft" (wenn genug Energie vorhanden auch während laden der Batterie)?

Es ist natürlich nicht unbedingt nötig.
Aber wenn man schon zwei unterschiedliche Datenpunkte für Laden und Entladen hat, wäre nicht schlecht, wenn diese auch angezeigt werden (auch gleichzeitig).

Ist nur ein Vorschlag, ich bin mit dem Adapter trotzdem sehr zufrieden 😀

**Comment by SKB-CGN** [comment]
Ich sagte nichts von sinnlos.

Es macht keinen Sinn - Akku laden und entladen zur selben Zeit - da kann man auch direkt die Energie an den Verbraucher leiten, ohne den Akku zu belasten, der ja auch nur x Lade-/Entladezyklen hat.

Die 2 Datenpunkte gibt es, weil manche Benutzer eben 2 getrennte Datenpunkte haben, die den Lade-/Entladevorgang anzeigen bzw. dir Werte beinhalten.
