### ISSUE TITLE
Unterstützung Kaskadenzähleranordnung

### ISSUE THREAD

**Issue by stheinen** [SKB-CGN/ioBroker.energiefluss#132]
Hallo,
wird eine Kaskasdenzähleranordnung für PV kombiniert mit Wärmepumpe  unterstützt?

Falls nein, wäre es schön dieses Feature zu integrieren.
https://www.polarstern-energie.de/fileadmin/files/downloads/Polarstern_Infoblatt_Kaskadenschaltung_PV-Waermepumpe.pdf

Viele Grüße
Stefan

**Comment by SKB-CGN** [comment]
Ist die Wärmepumpe als Erzeuger gedacht?

Wenn ja, kannst Du sie als Solar-Element angeben, allerdings hat sie dann auch ein Solar Icon.

Es wird noch implementiert, das man das Icon wechseln kann.

**Comment by stheinen** [comment]
Hallo,
die Wärmepumpe ist kein Erzeuger!
Es gibt zwei Zähler d.h. ein Netz-Zähler direkt am Netzübergabepunkt. Die WP ist danach angeschlossen und wiederum danach der Zähler für den Hausverbrauch. 

DIe Leistungsaufnahme der WP ergibt sich als Differenz der beiden Zähler.
DIeses Messkonzept ermöglicht die flexible Nutzung der PV-Energie zunächst im Haushalt und dann in der WP.
Der Rest wird über den Netzzähler eingespeist.
MfG
Stefan

**Comment by larsv-git** [comment]
Wäre auch eine Anforderung von meiner Seite. Habe versucht meine Kaskade darzustellen, was leider nicht klappt. Bitte berücksichtigen. Ansonsten ist der Adapter aber super.

**Comment by Winny1904** [comment]
Das ist wäre auch mein Wunsch. Das hatte ich im iobroker forum schon mal angesprochen. Das ein 2 zähler aufs Board kann

**Comment by SKB-CGN** [comment]
Hallo,
tut mir Leid, wenn der aktuelle "Energiefluss" Adapter deine Wünsche nicht berücksichtigen konnte.

Ich habe einen neuen Adapter, den "Energiefluss-erweitert", entwickelt, der möglicherweise Deinen Wünsche bereits berücksichtigt bzw. noch berücksichtigen wird.

Du kannst Ihn gerne ausprobieren.

Forum:
https://forum.iobroker.net/topic/64734/test-adapter-energiefluss-erweitert-v0-0-x-github-latest

Github Link:
https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert

Schau mal rein ;)
