### ISSUE TITLE
Wish: Support more consumer items with support for cascade counter array / Wunsch: Unterstützung von mehr Verbraucherelementen mit Unterstützung für Kaskadenzähler

### ISSUE THREAD

**Issue by zonfacter** [SKB-CGN/ioBroker.energiefluss#134]
Es wäre wünschenswert weitere Verbraucher Elemente hinzuzufügen (am liebsten keine Limitierung ) mit der Option einzelne Verbraucher einen weiteren Summenzähler zuzuordnen.
(Haus Hauptverteilung Keller -> Unterverteilung Garage -> Unterverteilung Gartenhaus) 

Haus Hauptverteilung Keller = Shelly 1 = Lampe 1
Unterverteilung Garage = Shelly 13 = Licht
Unterverteilung Gartenhaus = Shelly 23 = Balkonkraftwerk

In jeder Verteilung wäre beispielsweise ein Shelly 3 EM oder ähnliches verbaut, 

It would be desirable to add further consumer elements (preferably no limitation) with the option of assigning an additional totalizer to individual consumers.
(house main distribution basement -> sub-distribution garage -> sub-distribution garden house)

**Comment by SKB-CGN** [comment]
Eine Kaskade ist aktuell nicht vorgesehen. 

Allerdings lässt sich das mit mehreren Instanzen regeln. So lassen sich dann auch "unlimitierte" Elemente darstellen.

**Comment by zonfacter** [comment]
> Eine Kaskade ist aktuell nicht vorgesehen.
> 
> Allerdings lässt sich das mit mehreren Instanzen regeln. So lassen sich dann auch "unlimitierte" Elemente darstellen.

Ja, das stimmt. Dies sollte klappen, mit mehreren Instanzen...

**Comment by PhilippLeitner** [comment]
Du könntest die Namen von den Kaskaden als Link machen, dann könntest su auf die untergeordnete Ebene springen! 

Wenn du im Beschriftungsfeld <a href="url">link text</a> eingiebst, kannst du dies umsetzten. Mir fehlen für den Test noch zwei Zählpunkte, dann kann ich das bei mir umsetzen und euch zeigen.

LG Philipp

**Comment by SKB-CGN** [comment]
Hallo,
tut mir Leid, wenn der aktuelle "Energiefluss" Adapter deine Wünsche nicht berücksichtigen konnte.

Ich habe einen neuen Adapter, den "Energiefluss-erweitert", entwickelt, der möglicherweise Deinen Wünsche bereits berücksichtigt bzw. noch berücksichtigen wird.

Du kannst Ihn gerne ausprobieren.

Forum:
https://forum.iobroker.net/topic/64734/test-adapter-energiefluss-erweitert-v0-0-x-github-latest

Github Link:
https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert

Schau mal rein ;)
