### ISSUE TITLE
Featurerequest: mehrere Speicher/Batterien 

### ISSUE THREAD

**Issue by octane321** [SKB-CGN/ioBroker.energiefluss#135]
Mit dem Adapter hast du den Nerv der Zeit getroffen.
Würde mich freuen wenn es möglich wäre mehrere Batterien einzubinden
Ich habe immer mehrere Systeme parallel in Betrieb und das würde für die Übersicht wirklich sehr helfen!

VG

**Comment by SKB-CGN** [comment]
Für mehrere Batterien bietet sich im Moment leider kein Platz.
