### ISSUE TITLE
Instanz wird nicht angezeigt

### ISSUE THREAD

**Issue by tipp88** [SKB-CGN/ioBroker.energiefluss#136]
Hallo,

ich habe den Adapter per Github URL installiert, er taucht auch im Adapter Menü als installiert auf, aber in der Instanz-Übersicht ist keine Vorhanden. Jemand eine Lösung für das Problem?
![image](https://user-images.githubusercontent.com/68737433/220344980-c33acc8c-c0dd-43ea-9f72-03c2ac54ea8c.png)
![image](https://user-images.githubusercontent.com/68737433/220345302-a0e36d72-9e44-4297-a2f0-ed497d6f2f8e.png)

**Comment by SKB-CGN** [comment]
Du musst die Instanz anlegen.

Im oberen Bild auf die 3 Punkte, dann auf das "Plus". 
Instanz auf automatisch.

**Comment by tipp88** [comment]
Danke!
