### ISSUE TITLE
Restlaufzeit bei Entladung nicht immer korrekt

### ISSUE THREAD

**Issue by Andre-0815-4711** [SKB-CGN/ioBroker.energiefluss#137]
Restlaufzeit bei Entladung wird bei einer eingestellten Entladegrenze falsch berechnet. Hier entstehen Differenzen über mehrere Stunden.

`
852               rest = (battery_capacity * percent) / 100;
`
Für die Berechnung der Restlaufzeit wird immer der aktuelle Füllstand bis zur 0% Entladung berechnet.
Alle PV Speicher haben aber eine eingestellte Entladegrenze.
ZITAT:"Entladetiefe (DoD)
Eine Solarbatterie kann nicht zu 100% entladen werden. Diese sog. Tiefenentladung schädigt die Batterie. Deshalb kann eine Solarbatterie nur bis zur Entladetiefe entladen werden. Diese variiert je nach Hersteller. Zwischen 50% und mehr als 90% der gespeicherten Strommenge kann bei einem Entladevorgang deshalb (nur) entnommen werden."

Vorschlag zur Lösung:
Bei den Grundeinstellungen Batterie ein Feld für DoD hinzufügen.
Diesen Wert z.B. battery_DoD bei der Berechnung der Entladezeit berücksichtigen.
`
852               rest = (battery_capacity * (percent - battery_DoD) / 100;
`

**Comment by SKB-CGN** [comment]
Reicht im Forum nicht, den ganzen Tag davon zu schreiben? Muss es nun noch ein Issue sein?

Schon etwas pedantisch, findest Du nicht?

**Comment by Andre-0815-4711** [comment]
Hast Recht. Mach nen Haken ran.

**Comment by SKB-CGN** [comment]
Bitte die neue Version einmal ausprobieren. Das geforderte Thema Deines Beitrags wurde hier berücksichtigt!

**Comment by Andre-0815-4711** [comment]
Läuft 👍
