### ISSUE TITLE
Weitere Fahrzeuge

### ISSUE THREAD

**Issue by bjoernszw** [SKB-CGN/ioBroker.energiefluss#14]
Hallo,
Adapter läuft top, Allerdings wäre es cool wenn man mehrere Autos dort hinterlegen könnte, ich hab zwei Ladestationen am Haus und kann nur eine so schön darstellen.

**Comment by SKB-CGN** [comment]
Du kannst dafür einen der 4 möglichen benutzerdefinierten Kreise nehmen.

**Comment by bjoernszw** [comment]
das stimmt, allerdings nicht so schön mit den weiteren parametern (Ladezustand/Ladegerät angeschlossen)

**Comment by SKB-CGN** [comment]
Aktuell decken wir erstmal die Grundbedürfnisse ab :D

Dann schauen wir weiter, was dargestellt werden kann.

Bis dahin würde ich noch ein wenig um Geduld bitten.

**Comment by SKB-CGN** [comment]
2. Fahrzeug möglich mit:
https://github.com/SKB-CGN/ioBroker.energiefluss/commit/99b906a2821100120bc1328e3b49e52e7b2b03e2

**Comment by SKB-CGN** [comment]
Hallo,
tut mir Leid, wenn der aktuelle "Energiefluss" Adapter deine Wünsche nicht berücksichtigen konnte.

Ich habe einen neuen Adapter, den "Energiefluss-erweitert", entwickelt, der möglicherweise Deinen Wünsche bereits berücksichtigt bzw. noch berücksichtigen wird.

Du kannst Ihn gerne ausprobieren.

Forum:
https://forum.iobroker.net/topic/64734/test-adapter-energiefluss-erweitert-v0-0-x-github-latest

Github Link:
https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert

Schau mal rein ;)
