### ISSUE TITLE
Battery symbol missing / battery time param bumping around

### ISSUE THREAD

**Issue by thorstenman** [SKB-CGN/ioBroker.energiefluss#140]
**Describe the bug**  
Not able to define or display battery symbol. It is not configurable - but also does not show up.

**Expected behavior**  
Configuration possible or standard symbol like for other set up devices.

In addition, param „Offset des verbleibenden Batterietextes neben dem Batterieelement“ is just not precisely configurable. Edited values do not behave as expected. Put in numbers lead to not only object bumping around left-right, sometimes up-down. Can this be set up „stable“ - also linked to the other objects so that it also does not look different (overlapping with other objects) for different display sizes.

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Latest version
 - JS-Controller version: Latest version
 - Node version: Latest version
 - Operating system: Rasbian Buster

**Additional context**  
A big THANK YOU for this amazing feature!

**Comment by SKB-CGN** [comment]
Lass mich raten, du verwendest Safari?

**Comment by thorstenman** [comment]
> Lass mich raten, du verwendest Safari?

Jo, oder die iOS ioBroker App.

**Comment by SKB-CGN** [comment]
Und da klappt die Restanzeige leider nicht und das Batterie-Icon, welches animiert wird, auch nicht.

Da liegt es leider an iOS.

**Comment by SKB-CGN** [comment]
https://github.com/SKB-CGN/ioBroker.energiefluss#bekannte-probleme
