### ISSUE TITLE
MQTT Werte werden nicht erfasst

### ISSUE THREAD

**Issue by ZoXx** [SKB-CGN/ioBroker.energiefluss#144]
Hallo,

erst einmal vielen vielen Dank für die wunderschöne Visualisierung und die Arbeit!

Ich habe meine Wärmepoumpe und einige Verbraucher via MQTT eingebunden.
Die Werte werden allerdings vom der Instanz leider nicht erfasst.
Ist hier ein Bug vorhanden oder ist es derzeit noch gar nicht vorgesehen?

Gibt es die Möglichkeit, dass man den Export des Stroms direkt über den Hausverbrauch laufen lässt, anstatt das man diesen von der Erzeugung zum Netz laufen lässt? Weil der Bezug kommt ja auch vom Netz zum Hausverbrauch.

Viele Grüße!

**Comment by SKB-CGN** [comment]
Wie hast Du denn die Datenpunkte im Adapter eingestellt?

**Comment by ZoXx** [comment]
Hey,

ich habe die direkt mit dem Punkt "Datenpunkt Ihres benutzerdefinierten Elements" ausgewählt.

Da hast du natürlich vollkommen recht.

**Comment by SKB-CGN** [comment]
Du benötigst ja auch mindestens den Vebrauch bzw das Netzelement.

Die Benutzerdefinierten Elemente kommen vom Haus. Sieht man ja auch auf der Grafik.

**Comment by ZoXx** [comment]
Es sind noch weitere Elemente vorhanden inkl. PV-Anlage und Netz.

**Comment by SKB-CGN** [comment]
Wie sieht es denn als Grafik aus?

Hast Du einen Titel für das jeweilige Element vergeben?

**Comment by ZoXx** [comment]
So sehen die Einstellungen dazu bei mir aus:
![image](https://user-images.githubusercontent.com/11578454/221569795-32948773-fefa-4fe5-bbe6-e41bd78a1522.png)

**Comment by SKB-CGN** [comment]
Wie schaut denn der Datenpunkt dazu aus? Welche Version hast Du denn installiert? 3.5 oder 3.6?

**Comment by ZoXx** [comment]
Installiert ist Version 3.6.0.
Datenpunkt schaut folgendermaßen aus:
![image](https://user-images.githubusercontent.com/11578454/221573047-7a4606f2-a775-490a-a3f7-256da9dc1ee9.png)

**Comment by SKB-CGN** [comment]
Kannst Du im Browser einmal mit F12 schauen, ob dort Fehler in der Konsole erscheinen? Sieht z.B. so aus.

![2023-02-27 14_37_50-Close Icons – Download for Free in PNG and SVG](https://user-images.githubusercontent.com/58603329/221578128-fa3f8872-e90c-4a27-8d8e-4bd7b54470ca.png)

**Comment by ZoXx** [comment]
Habe im Reiter Energiefluss nur folgendes gefunden:
![image](https://user-images.githubusercontent.com/11578454/221579453-dc7d4a8c-ff85-483b-82e3-307dfd2bafa0.png)

**Comment by SKB-CGN** [comment]
Nein, wenn Du den Fluss als solches anzeigst:

http://ip-iobroker:8082/energiefluss

Erscheinen da Fehler?

**Comment by ZoXx** [comment]
Wenn ich die IP-Adresse einsetze kommt:
File not found: {}

**Comment by SKB-CGN** [comment]
Habe es korrigiert-> fehlt ein / am Ende

**Comment by ZoXx** [comment]
Erhalte ich ein: ERR_CONNECTION_REFUSED

In VIS ist es eingesetzt und im Reiter Energiefluss sehe ich auch alles.
Dort werden keine Fehler angezeigt.

**Comment by ZoXx** [comment]
Keine Fehler vorhanden.

**Comment by SKB-CGN** [comment]
Steht der Web-Adapter auf integrierte oder socket.io?

**Comment by ZoXx** [comment]
Der steht auf "integriert"
![image](https://user-images.githubusercontent.com/11578454/221588513-8da1c182-e98c-43a0-bd2a-328de6cef085.png)

**Comment by SKB-CGN** [comment]
Dann brauche ich mal in den Inhalt des Datenpunktes "config" des Adapters.

**Comment by ZoXx** [comment]
Inhalt des Datenpunktes:
{
  "common": {
    "name": "Stromerfassung_251/Zähler0-Leistung",
    "write": true,
    "read": true,
    "role": "variable",
    "desc": "mqtt server variable",
    "type": "string"
  },
  "native": {
    "topic": "Stromerfassung_251/Zähler0-Leistung"
  },
  "type": "state",
  "_id": "mqtt.0.Stromerfassung_251.Zähler0-Leistung",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  },
  "from": "system.adapter.admin.0",
  "user": "system.user.admin",
  "ts": 1664700898871
}

Und welche config des Adapters?

**Comment by SKB-CGN** [comment]
```
energiefluss.0.configuration
und
energiefluss.0.data
```

**Comment by ZoXx** [comment]
Ganz dumm gefragt.
Wo finde ich die Daten, die du benötigst?

**Comment by SKB-CGN** [comment]
Im Objekt Browser

**Comment by ZoXx** [comment]
Ah alles klar! :)

**data:**
{
  "_id": "energiefluss.0.battery_remaining",
  "type": "state",
  "common": {
    "name": "Remaining Time of the battery",
    "type": "string",
    "role": "text",
    "read": true,
    "write": false
  },
  "native": {},
  "from": "system.adapter.energiefluss.0",
  "ts": 1677504394304,
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  },
  "user": "system.user.admin"
}

**configuration:**
{
  "_id": "energiefluss.0.configuration",
  "type": "state",
  "common": {
    "name": "Parameters for HTML Output",
    "type": "string",
    "role": "state",
    "read": true,
    "write": false
  },
  "native": {},
  "from": "system.adapter.energiefluss.0",
  "ts": 1677504394299,
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  },
  "user": "system.user.admin"
}

**Comment by SKB-CGN** [comment]
Den Inhalt!!!

**Comment by ZoXx** [comment]
**Data:**
{"values":{"car_custom10_plugged":false,"car_custom_plugged":false,"consumption_value":"3072.00","production_value":"3649.00","grid_value":"519.00","custom0_value":"0.00","custom1_value":"0.00","custom2_value":"3.00","custom3_value":"1.00","custom4_value":"0.00","custom5_value":"0.00","custom6_value":"0.00"},"animations":{"solar_to_house":true,"grid_to_house":false,"solar_to_grid":true,"grid_to_battery":false,"solar_to_battery":false,"solar0_to_solar":false,"solar1_to_solar":false,"solar0_to_solar1":false,"battery_to_house":false,"house_to_custom0":false,"house_to_custom1":false,"house_to_custom2":true,"house_to_custom3":true,"house_to_custom4":false,"house_to_custom5":false,"house_to_custom6":false,"house_to_custom7":false,"house_to_custom8":false,"house_to_custom9":false,"house_to_custom10":false,"custom4_to_house":false,"custom9_to_house":false},"battery_animation":{"direction":"none"},"color":{"consumption_value":"#00b5dd","grid_value":"#ffffff","production_value":"#ffce4a","production0_value":"#ffce4a","production1_value":"#ffce4a","battery_value":"#a1d343","battery_remaining":"#a1d343","battery_percent":"#a1d343","custom0_value":"#f20e40","custom1_value":"#f20e40","custom2_value":"#f20e40","custom3_value":"#f20e40","custom4_value":"#f20e40","custom5_value":"#f20e40","custom6_value":"#f20e40","custom7_value":"#f20e40","custom8_value":"#f20e40","custom9_value":"#f20e40","custom10_value":"#f20e40","custom0_percent":"#f20e40","car_custom_plugged":"#a1d343","custom10_percent":"#f20e40","car_custom10_plugged":"#a1d343","swap_consumption_value":"#00b5dd","swap_grid_value":"#ffffff","swap_production_value":"#ffce4a","swap_production0_value":"#ffce4a","swap_production1_value":"#ffce4a"},"swap_values":{},"automatic_animation":[]}

**Configuration:**
{"lines":{"lines":{"battery_to_house":false,"grid_to_house":true,"grid_to_battery":false,"house_to_custom0":true,"house_to_custom1":true,"house_to_custom2":true,"house_to_custom3":true,"house_to_custom4":true,"house_to_custom5":true,"house_to_custom6":true,"house_to_custom7":false,"house_to_custom8":false,"house_to_custom9":false,"house_to_custom10":false,"solar_to_battery":false,"solar_to_grid":true,"solar_to_house":true,"solar0_to_solar":false,"solar1_to_solar":false,"custom4_to_house":false,"custom9_to_house":false,"solar0_to_solar1":false},"style":{"line_size":6,"animation_width":6,"animation":"6 6 6 6 6 6 6 6 6 6 6  70","animation_duration":2000,"animation_linecap":"round","animation_type":"linear"},"color":{"solar_to_battery":"","solar_to_grid":"","solar_to_house":"","solar0_to_solar":"","solar1_to_solar":"","grid_to_house":"","grid_to_battery":"","battery_to_house":"","default":"#000000","house_to_custom0":"","house_to_custom1":"","house_to_custom2":"","house_to_custom3":"","house_to_custom4":"","house_to_custom5":"","house_to_custom6":"","house_to_custom7":"","house_to_custom8":"","house_to_custom9":"","house_to_custom10":""},"animation_colors":{"solar_to_battery":"","solar_to_grid":"#42b807","solar_to_house":"#42b807","solar0_to_solar":"","solar1_to_solar":"","grid_to_house":"#ff2600","grid_to_battery":"","battery_to_house":"","default":"#ffce4a","house_to_custom0":"#ff2600","house_to_custom1":"#ff2600","house_to_custom2":"#ff2600","house_to_custom3":"#ff2600","house_to_custom4":"#ff2600","house_to_custom5":"#ff2600","house_to_custom6":"#ff2600","house_to_custom7":"#ff2600","house_to_custom8":"#ff2600","house_to_custom9":"#ff2600","house_to_custom10":"#ff2600"}},"elements":{"elements":{"house":true,"solar":true,"solar0":false,"solar1":false,"grid":true,"battery":false,"custom0":true,"custom1":true,"custom2":true,"custom3":true,"custom4":true,"custom5":true,"custom6":true,"custom7":false,"custom8":false,"custom9":false,"custom10":false},"style":{"size":2,"circle_radius":50,"shadow":true,"shadow_color":"rgba(0, 0, 0, 0.7)","rect_height":100,"rect_width":100,"rect_corner":15},"fill":{"house":"","grid":"","solar":"","solar0":"","solar1":"","battery":"","custom0":"","custom1":"","custom2":"","custom3":"","custom4":"","custom5":"","custom6":"","custom7":"","custom8":"","custom9":"","custom10":""},"color":{"house":"#00b5dd","grid":"#61687a","solar":"#ffce4a","solar0":"#ffce4a","solar1":"#ffce4a","battery":"#a1d343","custom0":"#f20e40","custom1":"#f20e40","custom2":"#f20e40","custom3":"#f20e40","custom4":"#f20e40","custom5":"#f20e40","custom6":"#f20e40","custom7":"#f20e40","custom8":"#f20e40","custom9":"#f20e40","custom10":"#f20e40"}},"fonts":{"font_src":"","font":"sans-serif","font_size_label":"12","font_size_value":"14","font_size_percent":"14","font_size_unit":"14","font_size_unit_percent":"14","font_size_remaining":"14"},"general":{"no_battery":true,"unit":"W","unit_swap":"kW/h","battery_animation":true,"fill_elements":false,"slim_design":false,"type":"rect","custom_type":"consumer","offset_icon":0,"offset_text":0,"offset_value":0,"offset_percent":0,"offset_remaining":0,"opacity_icon":70,"opacity_text":70,"opacity_value":100,"opacity_percent":100,"opacity_remaining":70,"opacity_line":70,"element_distance":15,"element_animation":true,"element_animation_time":5000,"line_visible":true,"automatic_animation":false,"disable_icons":false,"debounce_percent":10,"background_color":"transparent"},"icons":{"icons":{"house":true,"production":true,"production0":false,"production1":false,"grid":true,"battery":false,"custom0":true,"custom1":true,"custom2":true,"custom3":true,"custom4":true,"custom5":true,"custom6":true,"custom7":false,"custom8":false,"custom9":false,"custom10":false},"color":{"default":"#ffffff"},"style":{"shadow":false,"shadow_color":"rgba(0, 0, 0, 0.7)"}},"texts":{"texts":{"consumption_text":true,"production_text":true,"production0_text":false,"production1_text":false,"grid_text":true,"battery_text":false,"battery_remaining_text":false,"custom0_text":true,"custom1_text":true,"custom2_text":true,"custom3_text":true,"custom4_text":true,"custom5_text":true,"custom6_text":true,"custom7_text":false,"custom8_text":false,"custom9_text":false,"custom10_text":false},"labels":{"house":"Hausverbrauch","solar":"Erzeugung","solar0":"2. Erzeugung","solar1":"3. Erzeugung","grid":"Netz","battery":"Batterie","battery_remaining":"Restzeit","custom0":"Trockner","custom1":"Waschmaschine","custom2":"Kühlschrank","custom3":"Spülmaschine","custom4":"Backofen","custom5":"Wärmepumpe","custom6":"EDV","custom7":"","custom8":"","custom9":"","custom10":""},"color":{"default":"#ffffff","battery_remaining":"#000000"},"style":{"shadow":false,"shadow_color":"rgba(0, 0, 0, 0.7)"}},"values":{"values":{"consumption_value":true,"production_value":true,"production0_value":false,"production1_value":false,"grid_value":true,"custom0_percent":false,"custom10_percent":false,"battery_value":false,"battery_percent":false,"custom0_value":true,"custom1_value":true,"custom2_value":true,"custom3_value":true,"custom4_value":true,"custom5_value":true,"custom6_value":true,"custom7_value":false,"custom8_value":false,"custom9_value":false,"custom10_value":false},"style":{"shadow":false,"shadow_color":"rgba(0, 0, 0, 0.7)"}},"percent":{"style":{"shadow":false,"shadow_color":"rgba(0, 0, 0, 0.7)"}},"custom_symbol":{"icon_custom0":"","icon_custom1":"","icon_custom2":"M17 2H7C5.9 2 5 2.9 5 4V19C5 20.11 5.9 21 7 21V22H9V21H15V22H17V21C18.11 21 19 20.11 19 19V4C19 2.9 18.11 2 17 2M17 19H7V4H17V19M10 15H8V10H10V15Z","icon_custom3":"M18,2H6A2,2 0 0,0 4,4V20A2,2 0 0,0 6,22H18A2,2 0 0,0 20,20V4A2,2 0 0,0 18,2M10,4A1,1 0 0,1 11,5A1,1 0 0,1 10,6A1,1 0 0,1 9,5A1,1 0 0,1 10,4M7,4A1,1 0 0,1 8,5A1,1 0 0,1 7,6A1,1 0 0,1 6,5A1,1 0 0,1 7,4M18,20H6V8H18V20M14.67,15.33C14.69,16.03 14.41,16.71 13.91,17.21C12.86,18.26 11.15,18.27 10.09,17.21C9.59,16.71 9.31,16.03 9.33,15.33C9.4,14.62 9.63,13.94 10,13.33C10.37,12.5 10.81,11.73 11.33,11L12,10C13.79,12.59 14.67,14.36 14.67,15.33","icon_custom4":"","icon_custom5":"","icon_custom6":"","icon_custom7":"","icon_custom8":"","icon_custom9":"","icon_custom10":"","icon_solar":"M4,2H20A2,2 0 0,1 22,4V14A2,2 0 0,1 20,16H15V20H18V22H13V16H11V22H6V20H9V16H4A2,2 0 0,1 2,14V4A2,2 0 0,1 4,2M4,4V8H11V4H4M4,14H11V10H4V14M20,14V10H13V14H20M20,4H13V8H20V4Z","icon_solar0":"M4,2H20A2,2 0 0,1 22,4V14A2,2 0 0,1 20,16H15V20H18V22H13V16H11V22H6V20H9V16H4A2,2 0 0,1 2,14V4A2,2 0 0,1 4,2M4,4V8H11V4H4M4,14H11V10H4V14M20,14V10H13V14H20M20,4H13V8H20V4Z","icon_solar1":"M4,2H20A2,2 0 0,1 22,4V14A2,2 0 0,1 20,16H15V20H18V22H13V16H11V22H6V20H9V16H4A2,2 0 0,1 2,14V4A2,2 0 0,1 4,2M4,4V8H11V4H4M4,14H11V10H4V14M20,14V10H13V14H20M20,4H13V8H20V4Z","icon_grid":"M8.28,5.45L6.5,4.55L7.76,2H16.23L17.5,4.55L15.72,5.44L15,4H9L8.28,5.45M18.62,8H14.09L13.3,5H10.7L9.91,8H5.38L4.1,10.55L5.89,11.44L6.62,10H17.38L18.1,11.45L19.89,10.56L18.62,8M17.77,22H15.7L15.46,21.1L12,15.9L8.53,21.1L8.3,22H6.23L9.12,11H11.19L10.83,12.35L12,14.1L13.16,12.35L12.81,11H14.88L17.77,22M11.4,15L10.5,13.65L9.32,18.13L11.4,15M14.68,18.12L13.5,13.64L12.6,15L14.68,18.12Z","icon_house":"M0,21V10L7.5,5L15,10V21H10V14H5V21H0M24,2V21H17V8.93L16,8.27V6H14V6.93L10,4.27V2H24M21,14H19V16H21V14M21,10H19V12H21V10M21,6H19V8H21V6Z"},"swap_texts":{"labels":{"solar":"","solar0":"","solar1":"","grid":"","house":""}}}

**Comment by SKB-CGN** [comment]
Kannst Du bitte mit der Maus über dem Wert des Datenpunktes, der keinen Wert anzeigt, einmal stehen bleiben und folgenden Screenshot produzieren?

![2023-02-27 16_53_11-objects - ioBroker](https://user-images.githubusercontent.com/58603329/221612887-59264df7-7b8f-4bec-98d6-40248ee8d758.png)

**Comment by ZoXx** [comment]
Klar.
![image](https://user-images.githubusercontent.com/11578454/221613172-b1126c70-471d-47d5-834f-9e0b0b342668.png)

**Comment by SKB-CGN** [comment]
Ah, ich denke, ich habe den Fehler gefunden. Der Wert dort ist vom Typ String (Zeichenkette).
Soweit kein Problem -das Wertezeichen am Ende macht das Problem, da hier nicht mehr konvertiert werden kann.

Kann dieser MQTT Adapter auch keine Werte hinten anhängen?

**Comment by SKB-CGN** [comment]
Habe Dir mal eben einen "Fix" gebaut. Bitte einfach nochmal drüber installieren. Dann sollte das Thema Geschichte sein.

**Comment by ZoXx** [comment]
Guten Morgen,
der Fix ist eingespielt! Es funktioniert!

Eine Frage bleibt jedoch noch, ich habe das Fenster via iFrame im VIS eingebunden. Es scheint extrem Ressourcenfressend zu sein, sodass mein Fully Kiosk am Tablet abschmiert. Im Chrome auf dem PC läuft es tadellos. Kannst du dazu was sagen?

Viele Grüße

**Comment by SKB-CGN** [comment]
Dann kommen wahrscheinlich wieder irgendwo Werte an, die nicht stimmen bzw irgendwelche Zeichen mit sich führen.

Dies bitte vorher prüfen!

**Comment by ZoXx** [comment]
Guten Morgen,

Vorzeichen wurde geändert, nun wird der Erzeugte Strom aber nicht mehr berücksichtigt.
![Screenshot 2023-03-21 081458](https://user-images.githubusercontent.com/11578454/226539668-0c5b2415-a724-4306-ae72-4dcf885fd4f2.png)

**Comment by ZoXx** [comment]
Anbei ein aktuelles Bild
![image](https://user-images.githubusercontent.com/11578454/227508136-7578f498-0eb3-42ce-a964-c8639b0038a7.png)

**Comment by SKB-CGN** [comment]
Abermals: aus Grafiken kann ich keine Rohwerte lesen. 

Immer Datenpunkte mit Werten einstellen und Code Tags benutzen.
