### ISSUE TITLE
Restzeit wird nicht richtig dargestellt bzw. ist abgeschnitten

### ISSUE THREAD

**Issue by srwilli1** [SKB-CGN/ioBroker.energiefluss#146]
Die Anzeige der Restzeit wird abgeschnitten. 
Das Bild ist aus Jarvis (Iframe). Es sieht aber direkt im Browser genauso aus. Ich benutze Chrome und fullybrowser

![restzeit](https://user-images.githubusercontent.com/91827670/221817101-57dc225a-c60c-436b-9e51-cd47c0ff6a1c.JPG)

**Comment by SKB-CGN** [comment]
Kleinere Schriftart wählen.

**Comment by SKB-CGN** [comment]
Unter dem Akku ist eine Linie. Da passt es nicht hin.

**Comment by srwilli1** [comment]
Mit in den Kasten oder rechts daneben
