### ISSUE TITLE
energieflussanzeige bei HTTPS nicht möglich

### ISSUE THREAD

**Issue by minoger** [SKB-CGN/ioBroker.energiefluss#147]
Hallo,

vielen dank für den Adapter ...der verschafft eine schnelle Übersicht über die Anlage.
Ich habe jedoch folgendes Problem:

**Describe the bug**  
+ Ich nutze iobroker mit einem HTTPS Zertifikat
+ iobroker lässt sich damit normal nutzen
+ Die Energieflussanzeige bringt aber einen Fehler: "ungültige Antwort gesendet"
+ eine zweite Instanz des iobroker ohne HTTPS funktioniert ohne Probleme.

**Expected behavior**  
Energiefluss sollte auch sichtbar sein, wenn iobroker mit HTTPS läuft.

**Screenshots & Logfiles**  
![image](https://user-images.githubusercontent.com/40298767/222366672-f462f748-dc1d-4160-ab02-31a16feba0b2.png)

**Versions:**  

+ Version 3.6.0 (non-npm: SKB-CGN/ioBroker.energiefluss) 
+ node: v16.19.0
+ js-controller: 4.0.24

**Comment by SKB-CGN** [comment]
Danke für die Rückmeldung. Schaue ich mir mal an.
