### ISSUE TITLE
Second Batterie missing

### ISSUE THREAD

**Issue by BS-GIFHUB** [SKB-CGN/ioBroker.energiefluss#148]
Hello,

thanks for this very good approach to visualize energy flow. I have to batteries (one house battery and also a Bluetti battery station) which is integrated in my  solar home energy system. I can't find a second battery item to configure my home. Is it possible to add it ?
I principle I recommend to have configured items in general and every item could be a solar panel, consumption point,  a battery or an wallbox, or whatever is important to visualize.

Thanks

Bernhard

**Comment by SKB-CGN** [comment]
Hallo,
tut mir Leid, wenn der aktuelle "Energiefluss" Adapter deine Wünsche nicht berücksichtigen konnte.

Ich habe einen neuen Adapter, den "Energiefluss-erweitert", entwickelt, der möglicherweise Deinen Wünsche bereits berücksichtigt bzw. noch berücksichtigen wird.

Du kannst Ihn gerne ausprobieren.

Forum:
https://forum.iobroker.net/topic/64734/test-adapter-energiefluss-erweitert-v0-0-x-github-latest

Github Link:
https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert

Schau mal rein ;)
