### ISSUE TITLE
PV Erzeugung - keine Energiefluss

### ISSUE THREAD

**Issue by bjoernszw** [SKB-CGN/ioBroker.energiefluss#15]
Hallo,

ich hab zwar unter der Erzeugung einen Datenpunkt PV_Power der auch einen Wert liefert, allerdings ist die Flussrichtung weder zum Verbrauch noch zum Netz ersichtlich. Wenn ich die Verbrauchsberechnung über Erzeugung + Netz wähle, stimmt die Flussrichtung, allerdings stimmt dann der Wert vom Verbrauch nicht mehr. Was müsste man da einstellen?
Als Wechselrichter habe ich ein Fronius der liefert unteranderem: PV_Power, Load (Hausverbrauch), und P_Grid (Einspeisung Netz), aktuell hol ich mir die Netzeinspeisung über den smartmeter der den Wert direkt aus dem Zähler liest.

Hier noch ein Screenshot

![Screenshot 2022-08-23 101022](https://user-images.githubusercontent.com/84512347/186106880-2f2fe8dc-f67d-417e-bff9-273d73dbffa7.png)

Vielen Dank und viele Grüße!

**Comment by SKB-CGN** [comment]
Danke für die Rückmeldung. Könntest Du einmal zeigen, welche Checkboxen Du aktiviert hast? Sieht eher so aus, als wenn die Falschen aktiviert sind.

**Comment by bjoernszw** [comment]
hier nochmal der Screenshot

![Screenshot 2022-08-23 102858](https://user-images.githubusercontent.com/84512347/186110989-8f372851-03ea-4c24-8eb8-697b1701ae15.png)

**Comment by SKB-CGN** [comment]
Ist denn dein Verbrauch im Datenpunkt auch negativ? Wenn nein, stimmt die Checkbox nicht. Diese ist anzuklicken, wenn der Verbrauch im Datenpunkt negativ ist.

**Comment by bjoernszw** [comment]
ja ist er, siehe hier.
![Screenshot 2022-08-23 103420](https://user-images.githubusercontent.com/84512347/186112141-022a6b9f-93b1-4b25-a7c3-8eb386f663b8.png)

**Comment by SKB-CGN** [comment]
Verstehe. Schaue ich mir an.

**Comment by SKB-CGN** [comment]
Ich bräuchte noch die Information, wie du den Netzbezug bzw. Netzverbrauch bekommst.
Sind die Werte positiv/negativ? Ist es ein oder 2 Datenpunkte?

**Comment by bjoernszw** [comment]
wie du im screenshot siehst, bekomm ich den gesamtverbrauch über p_load, der wert p_grid ist der einspeise wert aus dem netz (netzbezug, da könnte ich aber auch über das smartmeter gehen und mir den wert auch holen der wäre dann bei bezug positiv und bei einspeisung negativ (allerdings ist das ja nur der überschuss oder halt der zugekaufte strom. der tatsächliche hausverbrauch ist p_load. Somit hab ich keine zwei datenpunkte. ich hoffe das ist versändlich :-)

**Comment by SKB-CGN** [comment]
Prima, danke. Ich habe eine neue Version online gestellt. Vielleicht probierst Du einmal aus.

Einfach nochmal mit der Katze drüber installieren.

**Comment by bjoernszw** [comment]
hab ich gemacht, er bekommt aber nur v1.0.1 auch wenn ich sag bestimmte version, wird mir nicht die 1.0.2 angeboten.

**Comment by SKB-CGN** [comment]
Du musst den gesamten Adapter über die Git-Katze noch einmal drüber installieren. Dann wird die Version automatisch angehoben.

**Comment by bjoernszw** [comment]
habs noch paar mal gemacht, jetzt hat er ihn geupdatet auf 1.0.6, sieht auf den ersten blick erstmal korrekt aus. ich warte bis sich die zustände ändern

![Screenshot 2022-08-23 140631](https://user-images.githubusercontent.com/84512347/186165869-21340201-e84d-4221-b829-47e7689a84b0.png)

**Comment by SKB-CGN** [comment]
Du verbrauchst aber keine 911kW  bzw. produzierst 2187kW, oder? ;)

**Comment by bjoernszw** [comment]
nein, das sind natürlich W :-) hab ich auch schon abgeändert.......

**Comment by SKB-CGN** [comment]
[](url)Hallo,
tut mir Leid, wenn der aktuelle "Energiefluss" Adapter deine Wünsche nicht berücksichtigen konnte.

Ich habe einen neuen Adapter, den "Energiefluss-erweitert", entwickelt, der möglicherweise Deinen Wünsche bereits berücksichtigt bzw. noch berücksichtigen wird.

Du kannst Ihn gerne ausprobieren.

Forum:
https://forum.iobroker.net/topic/64734/test-adapter-energiefluss-erweitert-v0-0-x-github-latest

Github Link:
https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert

Schau mal rein ;)
