### ISSUE TITLE
Falsche Schriftfarbe, wenn Objekt abhängig vom prozentualen Wert gefüllt wird

### ISSUE THREAD

**Issue by danickel** [SKB-CGN/ioBroker.energiefluss#151]
Die gewählte Schriftfarbe stimmt nicht mehr, wenn die Option "Füllen Sie Objekte abhängig von ihrem prozentualen Wert" aktiviert ist:

Option:
![image](https://user-images.githubusercontent.com/90868055/223205773-3cdbec38-756b-4300-b0bc-8f543b42bb22.png)

Farbeinstellungen:
![image](https://user-images.githubusercontent.com/90868055/223205838-90e9cf3f-be16-4ae8-bc3d-fce2a408a3a0.png)

Ergebnis:
![image](https://user-images.githubusercontent.com/90868055/223205946-1744b023-66bf-4eb3-9844-9be1bb552e61.png)
_____________________________________________________________________________________________

Wenn die Option deaktiviert ist:
![image](https://user-images.githubusercontent.com/90868055/223206086-5ca27681-44df-4010-b7f3-25df41674092.png)

Ergebnis:
![image](https://user-images.githubusercontent.com/90868055/223206156-ecafe6b1-bc72-4442-904c-8000dafdc5f5.png)

**Comment by SKB-CGN** [comment]
Ist richtig so - das Programm sucht die passende Farbe um den Kontrast herzustellen, damit man den Text auch lesen kann.

Ist das Element weniger gefüllt, wird die eingestellte Farbe genutzt.

**Comment by danickel** [comment]
Hm...kann man das auch irgendwie abstellen?
Das lila lässt sich deutlich schlechter lesen, als das weiß.

Sonst find ich die Funktion eigentlich richtig gut. 
Könnte man eventuell auch noch einbauen, dass man bei der solaren Produktion auch einen Prozentwert hinterlegen kann? Dann könnte man den Ertrag darstellen und im "vorbeigehen" am Tablet an der Wand direkt sehen wie voll der Akku ist und wieviel gerade vom Dach kommt.

**Comment by SKB-CGN** [comment]
Nein, lässt sich nicht abstellen - außer man nutzt die Funktion nicht. Die Farbe wird anhand des Kontrastes berechnet. Lila auf grün sieht man besser als weiß auf grün. 

Sicher kann man alles einbauen - kommt immer drauf an, wieviel Zeit man dafür hat.

**Comment by danickel** [comment]
Alles klar, schade :-)

Wundert mich nur etwas. Denn eins der besten Sachen an dem Adapter ist, dass ich jede noch so kleine Sache individuell einstellen kann. Aber an dieser Stelle entscheidet der Adapter plötzlich selber was der beste Kontrast ist...
Das passt irgendwie nichts so ins Gesamtkonzept...und mal ehrlich, das hier ist so nicht gut zu lesen ;-)

![image](https://user-images.githubusercontent.com/90868055/223267404-2cdc42a4-e4c1-418c-b01c-4f7861b9698e.png)

Aber kein Ding. Dann nutze ich die Funktion nicht. Der Adapter bleibt trotzdem TOP 👍
