### ISSUE TITLE
Werte von Verbrauch des öffentlichen Netzes werden nicht angezeigt

### ISSUE THREAD

**Issue by Tscho32** [SKB-CGN/ioBroker.energiefluss#154]
Werte von Verbrauch des öffentlichen Netzes werden nicht angezeigt.

Mein Datenpunkt liefert eine Nummerwert.
Dieser Wert entspricht der Leistung die ich aktuell aus dem Netz beziehe.
Trage ich diesen bei Verbrauch des öffentlichen Netzes ein, erscheint dieser Wert nicht in der Grafik. Er bleibt immer auf 0 W stehen und auch die Flussrichtung erschein nicht. 
![Verbrauch des Öffentlichen Netzes](https://user-images.githubusercontent.com/87376051/224481427-d4dd474a-6f06-4b08-a54b-bcf1d7ce1a68.png)

Trage ich den selben Wert aber bei Öffentlicher Netzeinspeisung ein, kommt der Wert in der Grafik (selbstverständlich ist dann die Flussrichtung in Richtung Netz)
![Öffentlicher Netzeinspeisung](https://user-images.githubusercontent.com/87376051/224481443-c79fa564-53a2-4a06-b757-99585cd92d68.png)

Ich habe auch schon andere Quellen genommen aber es bleibt immer bei 0W und ohne Flussrichtung
![1](https://user-images.githubusercontent.com/87376051/224481381-ce4bca0c-f49c-4f55-9508-b165efda5313.png)

**Versions:**  
 - Adapter version: V3.6.0
 - JS-Controller version:  4.0.24
 - Node version: 16.19.1
 - Operating system: Debian version: 11 (bullseye)

**Comment by SKB-CGN** [comment]
Bitte den Adapter richtig einstellen.

Die Checkboxen entsprechend betätigen. Dann klappt es auch.

**Comment by Tscho32** [comment]
Es ist nicht so das ich noch nichts probiert habe. Ich spiele seit einer Stunde herum.
Welche Checkbox habe ich den falsch?

**Comment by SKB-CGN** [comment]
Das erste Feld nimmt positiv oder negativ des gleichen Datenpunktes (Einspeisung/Bezug)

Das 2. ist abhängig vom ersten Feld.

Dann die passende Checkbox, ob wer positiv oder negativ ist und schon hast Du es.
