### ISSUE TITLE
Verbrauch als Datenpunkt ausgeben

### ISSUE THREAD

**Issue by rabbit6984** [SKB-CGN/ioBroker.energiefluss#159]
Hi,

Ist es möglich den Verbrauch als Datenpunkt Objekt auszugeben damit mit diesem weiter gearbeitet werden kann?

Danke

**Comment by SKB-CGN** [comment]
Theoretisch schon.

Dies kannst Du aber auch schnell selbst über ein Javascript oder Blockly erledigen.

**Comment by rabbit6984** [comment]
Hi, ja ich weiß, aber dann hab ich wieder ne Abhängigkeit von nem anderen Adapter etc. So dachte da du das ja eh berechnest in Abhängigkeit deiner Verbraucher wäre ja alles da im blockly müsste ich ja die Verbraucher immer anpassen.

Grüsse

**Comment by rabbit6984** [comment]
Hi, wollte mal nachfragen ob es mit dem Datenpunkt klappt.
Wäre cool 😎 alles aus einer Hand und kein hin und her mit einem anderen Script etc.


Vielen Dank
