### ISSUE TITLE
mehr als 10 benutzerdefinierte Elemente

### ISSUE THREAD

**Issue by stmb-100** [SKB-CGN/ioBroker.energiefluss#163]
Hallo
kannst Du bitte mehr als 10 benutzerdefinierte Elemente einbauen ?

**Comment by SKB-CGN** [comment]
Es ist kein Platz für mehr als 10 Elemente.

**Comment by SKB-CGN** [comment]
Hallo,
tut mir Leid, wenn der aktuelle "Energiefluss" Adapter deine Wünsche nicht berücksichtigen konnte.

Ich habe einen neuen Adapter, den "Energiefluss-erweitert", entwickelt, der möglicherweise Deinen Wünsche bereits berücksichtigt bzw. noch berücksichtigen wird.

Du kannst Ihn gerne ausprobieren.

Forum:
https://forum.iobroker.net/topic/64734/test-adapter-energiefluss-erweitert-v0-0-x-github-latest

Github Link:
https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert

Schau mal rein ;)
