### ISSUE TITLE
VIS iFrame

### ISSUE THREAD

**Issue by stmb-100** [SKB-CGN/ioBroker.energiefluss#164]
Hi
ich versuche in VIS und VIS-2-Beta im iFrame diesen Link und bekomme es einfach nicht hin, dass der Energiefluss angezeigt wird.

http://192.168.1.241:8081/#tab-energiefluss-0 (Link aus dem Menü)

Wo liegt mein Gedanken Fehler ?

Der schon geschlossene Issue hat mir leider nicht geholfen.

LG
Stefan

**Comment by SKB-CGN** [comment]
Der Link für dein iframe lautet in dem Fall:
https://192.168.1.241:8082/energiefluss/

**Comment by stmb-100** [comment]
OK Danke der 1. geht so 
http://192.168.1.241:8082/energiefluss/
ich habe noch einen 2. Energiefluss, da ich mehr als 10 Verbraucher habe
http://192.168.1.241:8081/#tab-energiefluss-1
wie bekomme ich den in den iFrame ?

**Comment by SKB-CGN** [comment]
http://192.168.1.241:8082/energiefluss/?instance=1
