### ISSUE TITLE
Ladeleistung bzw. Entladeleistung liegt nur als ein als positiver Wert vor

### ISSUE THREAD

**Issue by dherm2023** [SKB-CGN/ioBroker.energiefluss#172]
**Describe the bug**  
Sungrow Wechselrichter SH5.0RT geben für Battery Power nur einen Wert aus. Der ist immer Positiv. Wie kann der Energiefluss trotzdem richtig dargestellt werden?

**To Reproduce**  
2. Click on '...'

**Expected behavior**  

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: <adapter-version>
 - JS-Controller version: <js-controller-version> 
 - Node version: <node-version> 
 - Operating system: <os-name>

**Additional context**

**Comment by SKB-CGN** [comment]
Gibt es denn 2 Werte, die laden oder entladen anzeigen?

Wenn ja, die Checkbox für unterschiedliche Zustände aktivieren und jeweils die Textboxen füllen. Dann sind beide Werte positiv.

**Comment by dherm2023** [comment]
Nein es gibt nur einen Wert im Modbus wie oben beschrieben.
Hier beschrieben:
https://noegel.io/posts/2022-10-09-sungrow/

**Comment by SKB-CGN** [comment]
Dann müsstest Du, anhand der Input Register, 2 eigene Datenpunkte speisen, die dann entsprechend die Werte liefern.

Input Register für Laden/Entladen prüfen, ob 0 oder 1 und dann den jeweiligen Datenpunkt mit dem Wert füllen und dann anderen Nullen.

Die DPs dann einbinden und die Checkbox für die unterschiedlichen Zustände aktivieren.

**Comment by dherm2023** [comment]
Danke für den Tip. Ist vielleicht sehr simpel.
Leider fehlt mir die praktische Erfahrung dazu.
Beschäftigen wir uns später mal mit.
