### ISSUE TITLE
Alias subscription error

### ISSUE THREAD

**Issue by DEV2DEV-DE** [SKB-CGN/ioBroker.energiefluss#174]
Sobald die Instanz gestartet wurde, wird beim Klick in die Seitenleiste das Log mit Meldungen a lá
`admin.0 2023-04-04 19:44:41.561	error	Alias subscription error. Please check your alias definitions: sourceId=XXXXXX`
vollgeschrieben. Trotzdem funktioniert alles einwandfrei.
Für jeden Alias wird eine Zeile ins Log geschrieben.
Die Alias-Definitionen selbst sind allerdings alle korrekt!

Stoppe ich die Instanz, bleibt auch das Log sauber.

Dieses Verhalten konnten andere Anwender bestätigen.

**Comment by SKB-CGN** [comment]
Ich habe davon noch nichts gehört. Bei den "anderen Benutzern" scheint es dann auch ein Problem mit dem Alias Adapter zu sein.

Auch die Tutorials im Netz funktionieren problemlos.

Ich selbst nutze keine Alias(e) und habe davon bisher auch noch nichts gehört.

**Comment by SKB-CGN** [comment]
"Ein Klick in die Seitenleiste" ...
da ist schon etwas nicht richtig - denn, der Adapter holt ja die ganze Zeit Daten der Datenpunkte ab. Nicht erst, wenn man es anzeigt.

Somit scheint in der Verbindung etwas nicht zu stimmen.

Kommt auch etwas im Log, wenn du den Link in Instanzen nimmst und nicht in der Seitenleiste?

**Comment by DEV2DEV-DE** [comment]
> Kommt auch etwas im Log, wenn du den Link in Instanzen nimmst und nicht in der Seitenleiste?

Nicht derart reproduzierbar wie mit der Seitenleiste.
Ich habe den Adapter mal komplett rausgenommen und werde ihn gleich neu installieren.
Wenn ich das dann rudimentär eingerichtet habe, melde ich mich wieder.

**Comment by DEV2DEV-DE** [comment]
Schritt 1: Installiert und gestartet - ohne weitere Einstellungen. Keine Fehler erkennbar ... und auch nicht zu provozieren.

**Comment by DEV2DEV-DE** [comment]
Kommando zurück: Die Fehler kann ich mit dem Klick in die Seitenleiste jetzt auch wieder provozieren.
Mit dem Instanzlink allerdings nicht.

Ich werde das jetzt mal einrichten und sehen, ob die Fehler auch auftreten wenn man nicht in die Seitenleiste klickt. Darauf könnte ich durchaus verzichten.

**Comment by DEV2DEV-DE** [comment]
So, grundsätzlich erstmal eingerichtet und die Seitenleiste ausgeblendet. Ich zeige das über Vis an.
Nach den ersten 10 Minuten ohne Fehler im Log.
Es stellt sich mir die Frage, was beim Klick in die Seitenleiste anders ist als mit dem Instanzlink?
Da 10 Minuten nicht wirklich aussagekräftig sind, werde ich das mal bis morgen beobachten.

![grafik](https://user-images.githubusercontent.com/95883579/229901663-baacfd4b-54ae-4286-aab0-e9e20f85b02d.png)

**Comment by SKB-CGN** [comment]
Die Seitenleiste öffnet die Seite in einem Frame bzw wird per Skript weitergeleitet, weil dort nicht alle Funktionen zur Verfügung stehen.

Der Instanzlink öffnet die direkte Seite des Adapters.

**Comment by DEV2DEV-DE** [comment]
Ich beobachte erstmal und werde berichten ...

**Comment by SKB-CGN** [comment]
In deiner Log Meldung von oben kann man erkennen, daß es der Admin Adapter ist, der die Fehler wirft.

Beta oder zu alte Version installiert?

**Comment by DEV2DEV-DE** [comment]
Admin 3.6.5 - also aktuelle Version aus stable. Wie der Rest des Systems.
Der Admin-Adapter verwaltet die Aliase - ist also klar warum der die Meldungen wirft.

**Comment by SKB-CGN** [comment]
Nicht zwingend.

Wenn ein Adapter versucht, auf diese zuzugreifen, wirft der Adapter selbst die Fehler.

Dennoch denke ich weiter, das in diesen Aliasen irgendwo ein Fehler ist.

**Comment by DEV2DEV-DE** [comment]
So, die Nacht ist rum und keine Fehler im Log.
Auch interessant: Die Fehler lassen sich nur über die Seitenleiste provozieren.
Klicke ich auf der Seite "Übersicht" auf die Kachel, funktioniert die Anzeige ohne Probleme.

Vielleicht hast Du ja mal Zeit und Lust, das auf Deiner Entwicklungsmaschine nachzustellen.
Einfach mal einen (oder mehrere) Aliase im Objektbaum anlegen und schauen ob Du das beim Klick in die Seitenleiste zumindest bestätigen kannst.
Ich werde das auf meinem Testsystem ebenfalls mal machen.

Hier mache ich erstmal zu.
Es scheint mir kein direktes Problem mit dem Adapter zu sein, sondern eher eine seltsame Wechselwirkung.
Ich werde auf dem Testsystem mal den neuen JS-Adapter einrichten - vielleicht hilft's ja ;-)

Frohes Schaffen ...
