### ISSUE TITLE
Balkonkraftwerk auf Hausverbrauch "addieren"

### ISSUE THREAD

**Issue by clio2k** [SKB-CGN/ioBroker.energiefluss#175]
Mir ist aufgefallen, dass eine Datenquelle, die als "Balkonkraftwerk" definiert ist, nicht auf den Hausverbrauch aufgerechnet werden kann. Das wäre aber eigentlich in den meisten Fällen notwendig, da Balkonkraftwerke ja einfach "ungemessen" ins Hausnetz einspeisen und damit den Hausverbrauch (gemessen am Zähler) reduzieren. Ich habe lediglich die Funktion "abziehen" vom Hausverbrauch gefunden.

Gibt es hierzu eine Lösung?

**Comment by SKB-CGN** [comment]
Das wäre doch in dem Falle richtig.

Das BKW speist ins Hausnetz ein, also kannst Du es vom Hausverbrauch abziehen, damit dieser weniger wird. Dann stimmt die Darstellung wieder.

Verbrauch abziehen geht ja für alles - Auto, Verbraucher und BKW.

**Comment by clio2k** [comment]
Nein, das ist aus meiner Sicht falsch. Das Balkonkraftwerk reduziert ja bereits den Hausverbrauch. Ich moechte ja aber wissen, was ohne Balkonkraftwerk der „reguläre“ Hausverbrauch gewesen waere. Abziehen waere in diesem Fall richtig falsch, denn damit wuerde ich den Hausverbrauch ja nochmals um den gleichen Wert reduzieren.

**Comment by SKB-CGN** [comment]
Hast Du natürlich Recht - denken ohne Kaffee 🤭

Dann müsste es hier eine Rechnung greifen - schaue ich bei Gelegenheit einmal nach.

**Comment by Technikfan** [comment]
Hallo, wollte mal hören wie weit es denn mit der "Denke" zu dieser Frage steht?

Baue mir hier auch gerade das Equipment auf und mache die ersten Gehversuche in der GUI zum Energieflussadapter.
Die Umsetzung finde ich schon sehr ansprechend, nur sie Logik hinter dem Verbrauch passt bei mir irgendwie auch nicht.

Meine Messtelle "am Zähler" liefert mir schon den um den Betrag des eingespeisten Solarstroms reduziert.
Ich habe somit keinen eigenen Datenpunkt von dort, den ich dem Verbrauch unterjubeln könnte, den müsste ich mir dann selber schaffen.
Und ohne den Verbrauch in der Darstellung hängen die Verbraucher in der Darstellung unschön "in der Luft".
Vielleicht habe ich da auch die Logik noch nicht ganz verstanden, zum Nachlesen konnte ich nichts finden.
VG
Uwe
