### ISSUE TITLE
Symbole anordnen 

### ISSUE THREAD

**Issue by corsac82** [SKB-CGN/ioBroker.energiefluss#176]
Hallo 

kann man die Symbole auch manuell anordnen oder verschieben. So wie man sie braucht ?  Oder ist es fest vorgegeben?

**Comment by SKB-CGN** [comment]
Die Symbole sind vorgegeben. Genau wie die Elemente ansich auch.

**Comment by raidsec** [comment]
Hallo,

sehr geiles Projekt. Ich feiere es! Ist es denn geplant, eine Funktion zu implementieren, mit der die Symbole anders angeordnet werden können? Frei?

**Comment by SKB-CGN** [comment]
Die Symbole gehören zu den Elementen.

Somit lassen sie sich aktuell nur senkrecht nach oben oder unten verschieben.

Das funktioniert mit der Offset Einstellung.

Freie Symbole sind aktuell nicht geplant.

**Comment by corsac82** [comment]
Wäre aber ein schönes Feature. Könnte man halt so anordnen das man zum Beispiele jede Etage oder gerät frei positionieren könnte. Fände ich auch gut.

**Comment by SKB-CGN** [comment]
Was einem selbst Nutzen würde ist immer ein tolles Feature 🙂

Ich notiere die mal auf der Liste für die zukünftigen Phasen.

**Comment by corsac82** [comment]
Ja das stimmt 😄😜. Aber super das du es dir auf die to do liste schreibst. Danke

**Comment by SKB-CGN** [comment]
Hallo,
tut mir Leid, wenn der aktuelle "Energiefluss" Adapter deine Wünsche nicht berücksichtigen konnte.

Ich habe einen neuen Adapter, den "Energiefluss-erweitert", entwickelt, der möglicherweise Deinen Wünsche bereits berücksichtigt bzw. noch berücksichtigen wird.

Du kannst Ihn gerne ausprobieren.

Forum:
https://forum.iobroker.net/topic/64734/test-adapter-energiefluss-erweitert-v0-0-x-github-latest

Github Link:
https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert

Schau mal rein ;)
