### ISSUE TITLE
Data presentation

### ISSUE THREAD

**Issue by Sineos** [SKB-CGN/ioBroker.energiefluss#18]
All my consumption measurements are in Wh or kWh, e.g. for to / from grid I use a SML meter. This returns via the respective OBIS codes the total to / from grid in kWh.

For monitoring my PV I use a Solarlog which returns convient data points for
* Daily yield in Wh 
* Daily total consumption in Wh
* Daily self consumption in Wh

When adding these data points to the adapter, the results are basically correct but "strange":

![grafik](https://user-images.githubusercontent.com/4459312/187046001-9425de37-4a68-43e1-94eb-4921d7906f34.png)

* Why is cumsumption measured in W?
* IMHO, the energy flow should be on a daily basis:
  * reset at midnight
  * Use Wh / kWh as input
  * Summarize (on daily basis) from the respective start value to the current value, i.e. current[Wh / current timestamp] - starting[Wh / current day at 00:00]

Just recently homeassistant added something similar:
![grafik](https://user-images.githubusercontent.com/4459312/187046191-a90d0d8b-878b-4d43-a7f4-5533c00a7cfb.png)

This is today from my home. 
Homeassistant is nice but I like iobroker better, so many thanks in starting to add such a feature. Something I was really missing in iobroker and my Vis skills are definitively not enough to rebuild something like this.

Maybe as an additional feature request: When going for daily data some persistance via a history adapter, e.g. influxdb would be awesome.

**Comment by Sineos** [comment]
Just for sake of completness - this is how the settings page in HA looks like:

![grafik](https://user-images.githubusercontent.com/4459312/187046446-f6651ba7-ffa8-44a3-8a52-3f2f770dcddd.png)

**Comment by SKB-CGN** [comment]
Perhaps you missed the "usage" of this adapter.

It provides a live flow of the current used or produced energy.

No history, no yearly or daily measures.
Only live graphical view of the consumption flow and production.

**Comment by Sineos** [comment]
Thanks for the clarification. Then I guess I really misunderstood the adapter.
For me the "Watt Flow" is not interesting. I'm only interested in the flow of (k)Wh because this is what has an effect:
* Every self-consumed kWh is saved money
* Every kWh feed into the grid is an earning
* Every kWh pulled from the grid is spend money

> Edit: I will update the description for the Adapter as soon as possible to avoid any confusion.

Maybe it makes sense to update the settings as well, because it everywhere mentions "consumption" and "consumption" is measured in (k)Wh. Electric Power is measured in W

**Comment by SKB-CGN** [comment]
Well, all users till now understood the Adapter correctly and how it is used.

If you are not interested in the flow consumption, just uninstall the adapter to free up the space it used.

**Comment by Sineos** [comment]
> As a side note: Consumption can measure both values - energy and power.

Uhm, no. This is clearly defined. Energy in measured in P = U * I [W] (and is work **per** time unit) and consumption is measured W = P * t [Ws, Wh]

This is exactly the reason why looking at Watts in this context does not make much sense as it is only true for the moment you are looking at it. Anyway, your adapter, your call.

**Comment by SKB-CGN** [comment]
... and this is exactly, what the adapter shows.
A live flow of energy.
