### ISSUE TITLE
E3DC Wallbox

### ISSUE THREAD

**Issue by gitpaddex** [SKB-CGN/ioBroker.energiefluss#195]
Hallo, 

ich bin mal so frech und schreibe nur auf Deutsch.
Erstmal ein Lob: geiler Adapter !!!

Entwickelst du den Adapter noch weiter?

Wenn ja, wäre es möglich die Darstellung einer E3/DC Wallbox einzufügen? 
Kurz erklärt: Die E3/DC Wallbox würde nicht vom Haus abgehen, sondern hätte eine Leitung von der PV und eine vom Netz. Beide Werte kann man aus E3/DC auslesen.

So wie hier auf dem Screenshot.

![Screenshot 2023-05-14 095651](https://github.com/SKB-CGN/ioBroker.energiefluss/assets/28609352/2df4fcb5-8c67-4ba1-bae1-96949a4bf92f)

Ich selber habe gerade keine Idee, wie und wo es in dein Diagramm passen könnte, wollte dich aber trotzdem mal fragen. Vielleicht hast du ja eine gute Idee. Wenn nicht, dann schließe den Vorschlag hier einfach.

Vielen Dank für deine tolle Arbeit!
Gruß

Maik

**Comment by SKB-CGN** [comment]
Hallo,
Der Adapter wird aktuell nicht mehr erweitert.

Ich habe vor einigen Tagen die "erweitert"-Version im Alpha Status herausgegeben. Diese ist komplett frei einstellbar und würde deine Wallbox anzeigen können.

https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert

**Comment by gitpaddex** [comment]
Ah, sehr cool. Habe ich gleich mal auf meine Watchlist gesetzt :-) und werde es morgen mal ausprobieren.

Vielen Dank
