### ISSUE TITLE
Restlaufzeit der Batterie - Anzeige verschoben auf iOS Geräten + Safari

### ISSUE THREAD

**Issue by andy15m** [SKB-CGN/ioBroker.energiefluss#196]
Guten Abend, 

bei mir erscheint die Restlaufzeit auf dem Ipad verschoben. 
Auf dem PC + Firefox wird sie korrekt neben der Batterie angezeigt. 

Anbei ein Screenshot. 
Kann ich das Verhalten im Safari irgendwie beeinflussen?

![grafik](https://github.com/SKB-CGN/ioBroker.energiefluss/assets/108634159/0a714710-ebde-4b9d-a5cd-f17b1aa3c5cb)

**Comment by SKB-CGN** [comment]
Hallo,
Ja, den Safari nicht nutzen 😉
Dieser kann verschiedene Dinge nicht und ist nicht HTML5 konform.

**Comment by andy15m** [comment]
Hallo Stephan, 

vielen Dank für die schnelle Rückmeldung. 
Im Kiosk-Modus ist der Safari halt sehr gut integriert + Vollbildmodus.

Habe mir grade mal den Edge runtergeladen. 
Dort wird es mir ebenfalls (ein bisschen mehr mittig) angezeigt. 
Egal ob in mobiler Version oder mit angeforderter Desktop Version. 

PC+Edge ist alles normal. 
Vllt noch eine andere Idee?

![grafik](https://github.com/SKB-CGN/ioBroker.energiefluss/assets/108634159/ff948fed-b4b3-4600-950f-e2c90da9dca9)

**Comment by andy15m** [comment]
reopen
