### ISSUE TITLE
Speicher zu Netz

### ISSUE THREAD

**Issue by AlphaLima** [SKB-CGN/ioBroker.energiefluss#209]
Hallo,
wie kann ich die Verbindung Akku <-> öffentliches Netz mit Leben füllen? Diese Verbindung existiert in der Grafik, hat jedoch keine mir bekannten Datenpunkte.
Dieses Thema wir im Zuge der variablen Stromtarife (Tibber, Awattar, ...)  interessant, da damit auch im Winter der Solarakku netzdienliche genutzt werden kann.
 Gruß
  AL

**Comment by SKB-CGN** [comment]
Diese Linie wird aktiv, wenn die Ladung der Batterie stattfindet, jedoch keine Solarproduktion.

Dafür die Datenpunkte Ladung/Entladung der Batterie korrekt einstellen.

Oder, wenn der Adapter nicht das bereithält, was gewünscht wird, auf den Energiefluss-erweitert wechseln. 

Dieser ist komplett frei konfigurierbar.

**Comment by AlphaLima** [comment]
Hallo,
danke für die schnelle Antwort. Ich habe zwei Datenpunkte für Laden/Entladen des Akku (Kostal Plenticore), allerdings hat das bei mir nicht funktioniert, der Akku wird dann von der inaktiven (0W) PV geladen.
Ich probier es heute abend (ohne Sonne) noch mal aus, und mache mal einen screenshot.

Ich teste jetzt auch mal 
test-adapter-energiefluss-erweitert
den kannte ich noch gar nicht.
Gruß
 AL
