### ISSUE TITLE
Absturz Instanz wenn NULL Werte bei Verbrauchern

### ISSUE THREAD

**Issue by sheba-vdf** [SKB-CGN/ioBroker.energiefluss#214]
Hallo,
ich habe den Energieflussadapter in Version 3.6.0 und nutze ihn seit ein paar Monaten.

Ich habe meine Stromverbraucher wie Kühlschrank usw. per Shelly Plug eingebunden. Nun habe ich einen Shelly von einem Gerät an ein anderes gesetzt, wollte aber nicht den Alias löschen, weil dieser später wieder verwendet wird. Dann habe ich das neue Gerät hinzugefügt. Nach einem Neustart der Instanz wurde diese nicht mehr gestartet. Das Problem ist, dass der Alias nun den Wert NULL hat. Ich habe ihn händisch auf 0 gesetzt und nun kann ich es so betreiben. Es wäre schön, wenn dies Problem automatisch abgefangen werden könnte. Danke

**Comment by SKB-CGN** [comment]
Danke für den Kommentar.

Der Adapter bekommt nur noch Patches für NodeJS.

Der neue Adapter (Energiefluss-erweitert) erledigt nun die Aufgaben.
