### ISSUE TITLE
Prozentwert wird nicht gerundet

### ISSUE THREAD

**Issue by HaggardFFM** [SKB-CGN/ioBroker.energiefluss#218]
**Describe the bug**  
Ich habe 2 Wallboxen konfiguriert wobei Wallbox1 leider den Wert des Akkustandes mit 14 Nachkommastellen ausgibt.
Obwohl im Datenpunkt die richtige Zahl steht und die Rundung auf 2 Nachkommastellen. 

Das funktioniert auch richtig bei WB2

![image](https://github.com/SKB-CGN/ioBroker.energiefluss/assets/62116621/89b00a40-550e-443e-a29a-32fa332a5aa9)
![image](https://github.com/SKB-CGN/ioBroker.energiefluss/assets/62116621/a2f24ce3-18d9-44cb-9b44-befbb9c4e522)
![image](https://github.com/SKB-CGN/ioBroker.energiefluss/assets/62116621/dcb81c49-5e89-41ab-9e26-2e091b32c6af)

**Comment by SKB-CGN** [comment]
Bitte hier entlang: https://github.com/SKB-CGN/ioBroker.energiefluss/edit/main/README.md#note

**Comment by HaggardFFM** [comment]
Ich schau mir den neuen Adapter an. 
VG
