### ISSUE TITLE
Animation from Battery to Net not working

### ISSUE THREAD

**Issue by seid0017** [SKB-CGN/ioBroker.energiefluss#221]
**Describe the bug**  
I case of Battery discharge Power is higher than Home Power consumption, Battery Power will be transferred to Net. But animation is not showing this Power flow.  See Screenshot.
Used case: Forced Discharge of Battery.
![Screenshot 2023-07-02 122626](https://github.com/SKB-CGN/ioBroker.energiefluss/assets/23658146/c8e11224-6961-4b63-95b4-e33402435ca8)

**To Reproduce**  
Power values as seen in Screenshot, a external State for each Power Value is configured. No automatic calculation from e.g. Home Power via "Energiefluss" Adapter.

**Expected behavior**  
Power flow from Battery to Net should be displayed with animation.

**Versions:**  
 - Adapter version: 3.6.0
 - JS-Controller version: 4.0.23
 - Operating system: Win11

**Comment by SKB-CGN** [comment]
Hi,
hybrid batteries are not supported in this version of the adapter.
Please design your own animation flows with the new 'erweitert' version.

**Comment by seid0017** [comment]
OK understood. Its a special used case, I agree.

**Comment by SKB-CGN** [comment]
It is. But you can use the new 'erweitert' Version. This one supports bidirectional animations, depending on state values.

**Comment by seid0017** [comment]
I just installed it. Realy nice and very flexible. Thanks for Providing. Is there a posibility to takeover the configuration from used "Normal" Adapter into the "Erweitet " Adapter to have a starting point?

**Comment by SKB-CGN** [comment]
Sorry, as both Versions use different config storages (iobroker states vs iobroker inside) systems, there so no migration possible.
Further, the new one supports many more features, which were not available in the previous version.
