### ISSUE TITLE
Energiefluss wird in der Übersicht des IOB falsch dargestellt

### ISSUE THREAD

**Issue by smarteshome2020** [SKB-CGN/ioBroker.energiefluss#235]
**Describe the bug**  
After update the admin  to V6.6.1 (needed for awtrix) the name of the three energiefluss instancen is not shown in overview any more. It is not possible to edit the Name. Manuell added Tabs are posible to edit

**To Reproduce**  
is permamently

**Screenshots & Logfiles**  
![image](https://github.com/SKB-CGN/ioBroker.energiefluss/assets/97242825/20c06214-a73e-4812-a134-ad76e13a5d5f)

**Versions:**  
 - Adapter version: scrennshot was V 3.5.0, after update to V3.6.0 same error
 - JS-Controller version: 4.0.24
 - Node version: V18.17.0
 - Operating system: linux (runing on Proxmox LXC Container)

**Comment by mcm1957** [comment]
This error could be caused by an outdate version of admin.
Please report the admin version used.

**Comment by smarteshome2020** [comment]
Hi,now i use Admin V6.8.0 (yesterday installed) with same error.Am 22.08.2023 um 17:37 schrieb Martin M. ***@***.***>:﻿
This error could be caused by an outdate version of admin.
Please report the admin version used.

**Comment by mcm1957** [comment]
Ich kann das Problem mit der aktuellen Version nicht nachstellen.

![image](https://github.com/SKB-CGN/ioBroker.energiefluss/assets/28575778/f3a748b0-d3e4-4fbd-a0e6-c764581d5441)

Admin scheint jedenfalls normal zu funktionieren.

**Comment by smarteshome2020** [comment]
OK, was kann ich machen damit es mir in der Übersicht wieder korrekt angezeigt wird?
Die Funktionen wie bei Dir im Screenshot zu sehen sind habe ich gar nicht, auch nicht wenn ich den experten Modus aktiviere.

![image](https://github.com/SKB-CGN/ioBroker.energiefluss/assets/97242825/b1acb7ed-48c1-4036-aa5b-d4edcf9aaf4c)

**Comment by mcm1957** [comment]
Hatte instanzen in der Kachelansicht offen.

Aber ansonsten muss ich passen. Das muss dsich der Dev des Adapters ansehen und ggF mit admin Entwicklung abstimmen.
Ich hab mich nur eingemischt da ältere Admins den monolingualen Titel benutzten und nicht den mehrsprachigen. Da der Adapter nur mehrsprachigen Text anbietet (was an sich ok ist) dachte ich dass es das sein könnte. Ist es offenbar nicht.

Daher bitte warten. Bugs sollen lt. dev ja noch weiter behoben werden.

**Comment by SKB-CGN** [comment]
Ich würde mal den Upload Knopf drücken und dann schauen.

**Comment by smarteshome2020** [comment]
Danke, welchen „upload Knopf“ meinst du?Am 23.08.2023 um 20:58 schrieb SKB-CGN ***@***.***>:﻿
Ich würde mal den Upload Knopf drücken und dann schauen.

**Comment by SKB-CGN** [comment]
Der, der sich bei den Adaptern befindet, wo auch Instanzen erstellt werden.

Oder per cli:

```bash
cd /opt/iobroker
iob upload energiefluss
```
