### ISSUE TITLE
Adapter no longer maintained 

### ISSUE THREAD

**Issue by mcm1957** [SKB-CGN/ioBroker.energiefluss#240]
As this adapter is no longer maintained (according to README.md (https://github.com/SKB-CGN/ioBroker.energiefluss#note) consider setting this repository to ARCHIVED status

**Comment by SKB-CGN** [comment]
Correct, it's still getting security updates and so on, but nothing more.
Therefore, it's not beta anymore -> it's final fixed :)

**Comment by mcm1957** [comment]
Ok, but I would not call this no longer maintained.

**Comment by SKB-CGN** [comment]
Ok, then I will change it to a more expressive sentence

**Comment by mcm1957** [comment]
Consider eventually

'Feature complete but issues will be fixed and security updates will be merged'

or something like this
@Apollon77 - any suggestion?

P.S: I'll reopen latest PR and review in this case

**Comment by SKB-CGN** [comment]
Sure :)
