### ISSUE TITLE
Energiefluss bei Zusatzverbraucher animiert nicht

### ISSUE THREAD

**Issue by reihd** [SKB-CGN/ioBroker.energiefluss#246]
![image](https://github.com/SKB-CGN/ioBroker.energiefluss/assets/95223338/edba9496-5174-47b4-85a1-1cc47139cdcb)

ich habe das Problem, dass ich nur die Animation der Solaranlage und zur Batterie habe, die extra Verbraucher zeigen zwar an, aber animieren nicht, also der Balken wandert nicht sondern steht.

Adpaterversion ist: 3.6.0

**Comment by SKB-CGN** [comment]
Die Werte der Verbraucher sind ja auch 0 W. Demnach findet kein Verbrauch statt - daher keine Animation.

**Comment by reihd** [comment]
die Animieren auch nicht wenn knapp 100 Watt laufen, außerdem ist der rechte ja im Verbrauch und die Linien zeigt es ja an, sie laufen nur nicht. Auch wenn ich den Verbrauch vom Haus setze, animiert nichts

**Comment by reihd** [comment]
Browser: Chrome, aber auch Edge und Fully machen das gleiche. Keine Animation. Die Datenpunkte sind die Powerdatenpunkte von einigen Shellys. Fehler kommen nicht, die Animation startet ja nur nicht, der schwarze Balken kommt und die gelben kleinen Balken auch, nur sie laufen nicht.

**Comment by SKB-CGN** [comment]
Ist die automatische Animation an oder aus?
Wie lang ist die Animationsdauer?
Läuft die Animation in der Konfiguration?

**Comment by reihd** [comment]
![image](https://github.com/SKB-CGN/ioBroker.energiefluss/assets/95223338/b0fa186e-223d-415e-9c54-a07c598e262f)

ich habe hier den Haken heute früh gesetzt, habe diesen jetzt rausgenommen, dann läuft die Animation auch zu den Extra Verbrauchern. Aber wie schon geschrieben, bei 100 Watt lief nichts, aber die Solardaten wurden animiert. Ich weiß nicht ob das Ticket geschlossen werden kann, eigentlich ist es ein kleiner Bug? Keine Ahnung, generell ist das ein Hammer Adapter

**Comment by SKB-CGN** [comment]
Die automatische Animation greift über alles.
Heißt, wenn Du große Verbraucher hast (> 1000) und kleine (<=100), dann kann es sein, das die Animation sehr verlangsamt wird.

Es gibt inzwischen den 'erweitert' Adapter, der völlig frei konfigurierbar ist. Und auch noch einige Dinge mehr bietet 🙂

Den kannst Du auch nutzen.

**Comment by reihd** [comment]
Ah ok, danke für die Info und vielen Dank für den Support, echt super.
