### ISSUE TITLE
allow more than 10 custom items

### ISSUE THREAD

**Issue by jevylux** [SKB-CGN/ioBroker.energiefluss#304]
This is not a bug but a feature request

I like this adapter very much, but I have a suggestion.
Would it be possible to make the number of custom sources variable ?
At this moment in time I can define 10 custom elements
I have about 16 different power meters in the house, and would like to monitor all of them.
Best would be allow adding elements in the instance configuration.
But to be honest, I do not know the impact, especuially in the generated web page.

But maybe you would like to look at this in a future version

**Comment by SKB-CGN** [comment]
This adapter is limited to 10 custom items.
If you need more, you can switch to the 'erweitert' version.
This has no limitations of objects.
