### ISSUE TITLE
Feature Request: Hide unused/inactive devices

### ISSUE THREAD

**Issue by Stroell** [SKB-CGN/ioBroker.energiefluss#312]
Hi,
thanks for your great Adapter!
But I have one Feature Request.
It would be cool if you could hide unused/inactive devices. 
For example, I only want to see my washing machine when it is active (e.g. power draw over 10 Watts).
If the washing machine is not active, it should not be shown at all.

Thank you :)

**Comment by SKB-CGN** [comment]
Hi,
this can be done with the new 'energiefluss-erweitert' adapter.
