### ISSUE TITLE
Netz ist immer positiv

### ISSUE THREAD

**Issue by gehtnixx** [SKB-CGN/ioBroker.energiefluss#313]
Hi,

ich bin gerade am einrichten deines coolen Adaptern.
Allerdings kämpfe ich gerade mit der Anzeige der Netz Werte.
Egal was ich anhake oder abhake, der Wert ist immer positiv bei Bezug UND bei Einspeisung.
Die Flusslinien und Berechnungen funktionieren einwandfrei auch der Wert stimmt bei der Einspeisung nur eben fehlt das "-" Vorzeichen und dadurch verändert sich auch nicht die Farbe des Wertes, da es kein negativ Wert ist.
Was mache ich falsch?

Grüße
Patrick

![image](https://github.com/SKB-CGN/ioBroker.energiefluss/assets/104681809/20627475-8baa-47ab-8935-0c831cbe3d27)

**Comment by SKB-CGN** [comment]
Im letzten Tab sollte es die Box geben, den Wert als negativ darzustellen.

Auch würde ich auf den neuen 'erweitert' Adapter gehen, der bietet noch mehr Einstellmöglichkeiten.

**Comment by gehtnixx** [comment]
Mein Gott, wie kann man so blind sein.
Hut ab vor der schnellen Rückmeldung.
Aber das mit dem Schwellwert geht leider nicht, seh ich das richtig?

**Comment by SKB-CGN** [comment]
Was sollte mit dem Schwellenwert nicht gehen?

**Comment by gehtnixx** [comment]
Es zeigt jetzt zwar minus an, aber wird nicht als minus gesehen und der Wert verändert nicht seine Farbe.
Ist aber alles nicht schlimm, ich bin auf den "erweitert" Adapter und bin total im Glück.

Wenn man mal in der Materie ist, kommt man nicht mehr weg vom Monitor... 

Vielen Dank für den coolen Adapter!!!

![image](https://github.com/SKB-CGN/ioBroker.energiefluss/assets/104681809/722a0ed5-1525-44d8-894f-38c2bbde4a9f)

**Comment by SKB-CGN** [comment]
Richtig. Es werden alle Werte positiv behandelt.
Mit dem Minus ist nur als Erkennung, das etwas aus dem Netz kommt - wer die Laufrichtung der Striche nicht erkennt :)
