### ISSUE TITLE
 ioBroker.energiefluss startet/verbindet nicht

### ISSUE THREAD

**Issue by spunky1a** [SKB-CGN/ioBroker.energiefluss#315]
ich wollte den energiefluss anzeigen lassen (PV, Akku, Haus, Netz), habe alles Energieknoten eingegeben, aber es wird keine Verbindung aufgebaut

![image](https://github.com/SKB-CGN/ioBroker.energiefluss/assets/18560488/b0fb325f-9af1-4022-8292-fb4bd0f60594)

also log bekomme ich

![image](https://github.com/SKB-CGN/ioBroker.energiefluss/assets/18560488/bbd85e44-4ecd-40a9-92ee-d5bb51769558)

es fehlt wohl noch ein Adapter "web", was ist damit gemeint, welcher ist, wo finde ich den?

**Comment by SKB-CGN** [comment]
![2024-01-26 13_16_58-adapters - ioBroker-master – Mozilla Firefox](https://github.com/SKB-CGN/ioBroker.energiefluss/assets/58603329/fc9aa061-3ea6-4615-b84d-c8eedbd4470b)
