### ISSUE TITLE
Gleichstromverbraucher

### ISSUE THREAD

**Issue by Hektor54** [SKB-CGN/ioBroker.energiefluss#317]
Ich habe an meiner 48Volt-Batterie einen zweiten Shunt, an dem ein Gleichstromverbraucher angeschlossen ist und dessen Leistungsverbrauch gemessen wird.
Ist auch in Wohnmobilen (Motorhomes) häufig im Einsatz.
Gibt es eine Möglichkeit diese Gleichstromleistung direk an die Batterie zu "schalten"?

**Comment by SKB-CGN** [comment]
Das Layout für den Adapter ist "fix".

Für eigene Kreationen bitte den "Energiefluss-erweitert" nutzen.
