### ISSUE TITLE
Datenpunkt "Batterie entladen"

### ISSUE THREAD

**Issue by michiproep** [SKB-CGN/ioBroker.energiefluss#319]
Hi. Erstmal ein Lob: Richtig cooler Adapter.

Bei mir tritt ein kleines Problem auf im Zusammenhang mit "Batterie entladen" auf.
Ich habe 2 seperate Datenpunkte für Laden und Entladen, beide positive Werte. Ich habe auch alle Kombinationen der zugehörigen Checkboxen ausprobiert, aber ein Entlade-Vorgang erschein nie auf der UI. Die Anzeige bleibt maximal auf 0 sitzen.

Wenn ich die Werte meiner Datenpunkte anschaue, dann wird mir tatsächlich bis zu 10 W Beladung gleichzeitig zu einer zB 1,5 kw Entladung angezeigt.
Vielleicht hat es mit den Messungenauigkeiten zu tun?

Gleiches gilt übrigens für meine Erzeugung. Die zeigt auch manchmal mitten in der Nacht 15 Watt an.

Vielleicht sollten alle Werte unter x Watt ignoriert werden können?

**Comment by SKB-CGN** [comment]
Korrekt, eine Ladung oder Entladung wird nur angezeigt, wenn einer der beiden Werte 0 und der andere Wert höher oder niedriger ist.

Es gibt im letzten Tab die Möglichkeit einen Schwellenwert anzugeben.

Für bessere Darstellung kannst du auch auf den "Energiefluss-erweitert" wechseln - dort stehen dir mehr Einstellmöglichkeiten zur Verfügung.
