### ISSUE TITLE
Line between additional solar production and solar production does not take on color.

### ISSUE THREAD

**Issue by Gr33n93** [SKB-CGN/ioBroker.energiefluss#344]
Line between additional solar production and solar production does not take on color.

The line with the specification: Color of the line between additional solar production and solar production (default: empty)
always remains at the default yellow and cannot be adjusted

**Comment by SKB-CGN** [comment]
Works as expected:
![2024-04-28 14_40_34-Greenshot](https://github.com/SKB-CGN/ioBroker.energiefluss/assets/58603329/51698dd3-d718-4673-95e3-d783425d6dcc)
![2024-04-28 14_43_00-Greenshot](https://github.com/SKB-CGN/ioBroker.energiefluss/assets/58603329/f316275b-cf0a-408c-93df-8a08b1f2a016)

**Comment by Gr33n93** [comment]
![1](https://github.com/SKB-CGN/ioBroker.energiefluss/assets/97936996/47cd0a2f-bd1b-4da1-9ef7-1de58ace81ee)

![2](https://github.com/SKB-CGN/ioBroker.energiefluss/assets/97936996/91b1521f-b5ff-454c-bda0-ed49c32badc1)

Working here is not right.

Look at the pictures

**Comment by SKB-CGN** [comment]
Will have a look into that tomorrow and come back.
