### ISSUE TITLE
Font farbe 'battery Charge and discharge'

### ISSUE THREAD

**Issue by HB-Git** [SKB-CGN/ioBroker.energiefluss#356]
**Describe the bug**  
Wenn ich nur 'Charge accu:' eine Leistung darstellen lasse, kann ich die Farbe richtig einstellen unter dem Reiterblatt 'Color-settings'.
Wenn ich allerdings dann neben Leistung auch den SOC Werte zeigen lasse, gehen die Farben von Leistung und SOC in Orange und diese lässt sich nicht mehr ändern. Ich hatte eigentlich Schwarz für Text und Werte eingestellt.

**To Reproduce**  
1. Go to 'battery Charge and discharge'
2. Choose bothe discharge power and SOC datapoint
3. Selecting colors in the 'Color-settings' do not change the color in the displayed values.
4. If I remove the SOC datapoint again, so only charge power is shown, the color changes to the selected color.
If I change a different background instead of blue a green, the font also changes and can still not be turned to the one I choose

**Expected behavior**  
Normally color should always be changed also with more than one datapoint visible.

**Screenshots & Logfiles**  
Color correct (but no SOC visible):
![Screenshot 2024-06-09 205059](https://github.com/SKB-CGN/ioBroker.energiefluss/assets/38045061/c0acbeaa-f26a-4457-be97-3fc39c54bd4c)

Color incorrect:
![Screenshot 2024-06-09 204944](https://github.com/SKB-CGN/ioBroker.energiefluss/assets/38045061/64a08a2a-d0ba-4cbc-8daa-bdd49d3d6b45)

Different background:
![Screenshot 2024-06-09 210039](https://github.com/SKB-CGN/ioBroker.energiefluss/assets/38045061/e7166576-9cbb-4b90-9eee-827be193fddd)

**Versions:**  
 - Adapter version: v3.6.0
 - JS-Controller version: v20.14.0
 - Node version: <node-version> 
 - Operating system: IOBroker on Raspberry Pi4 Pi OS

**Additional context**

**Comment by SKB-CGN** [comment]
Die Farbe wird bei sich füllendem Element passend gewählt, damit man den Text erkennen kann.

Die Farbe ohne Füllung ist die, die du angegeben hast.

**Comment by HB-Git** [comment]
Verstehe, aber ich habe keinen weiteren Platz für den Farben als diese für 'Battery' gefunden:
![Screenshot 2024-06-10 064143](https://github.com/SKB-CGN/ioBroker.energiefluss/assets/38045061/e4f1568d-4c99-4249-a3a9-41d20050abcc)

Und damit kriege ich leider kein Schwarz:
![Screenshot 2024-06-10 064312](https://github.com/SKB-CGN/ioBroker.energiefluss/assets/38045061/24131fa2-143e-4dbc-9213-ffa10ca0bb28)

**Comment by SKB-CGN** [comment]
Habe ich doch erklärt - die Farbe ohne Füllung gibst Du an - schwarz.

Sobald das Element gefüllt wird, wird eine Farbe gewählt, die man erkennen kann.

Da schwarz auf blau zu dunkel ist, wird eine passende Farbe gewählt.

Gerne kannst du auch auf die 'erweitert' Version wechseln - diese ist vollkommen einstellbar.

**Comment by HB-Git** [comment]
Alles klar danke!
