### ISSUE TITLE
weiter PV Anlage

### ISSUE THREAD

**Issue by rowoy** [SKB-CGN/ioBroker.energiefluss#37]
Hallo, 

Erst einmal vielen Dank für den Klasse Adapter. Ein Traum. 
Einen Wunsch hätte ich aber noch wenn es andere auch Interessieren könnte.
Wie schaut es mit weiteren Einspreise Punkten aus? Im Moment geht ja nur ein Wechselrichter. Oder sehe ich da was falsch? 
Ich denke da in Richtung BKW´s. Eine Anlage in Nord, Ost oder Süd Ausrichtung. 
Oder vielleicht reicht ja auch eine Möglichkeit der Änderung der Animationsrichtung. Dann könnte man die Vorhanden "Kreise" nutzen.

**Comment by SKB-CGN** [comment]
Hallo,
es gibt derzeit den einen Erzeugungspunkt. Kann entweder ein Wechselrichter sein oder eine Batterie mit PV-Messeinrichtung. Diesen Datenpunkt könntest Du, wenn Du mehrere Anlagen (oder Teile hast), in einen Datenpunkt zusammenfassen - per Addition z.B. und diesen dann angeben. Solltest Du die Anlagen "trennen" wollen, so kannst Du mehrere Instanzen des Adapters anlegen und dort die einzelnen Anlagen angeben :)

**Comment by rowoy** [comment]
Na das ging ja fix mit der Antwort...  :-)

Ja die Idee ist so nicht schlecht mit den Datenpunkt.... werde mir das mal überlegen und umsetzen.
Wobei die Visuelle Darstellung der Jeweiligen PV Anlagen sicherlich auch nee Schicke Sache ist. 
Danke aber noch mal für den Super Adapter. Weiterhin Super Ideen

**Comment by SKB-CGN** [comment]
> Wobei die Visuelle Darstellung der Jeweiligen PV Anlagen sicherlich auch nee Schicke Sache ist. 

Wie gesagt, da würden mehrere Instanzen, die Du erstellst, helfen.

**Comment by SKB-CGN** [comment]
Hallo,
tut mir Leid, wenn der aktuelle "Energiefluss" Adapter deine Wünsche nicht berücksichtigen konnte.

Ich habe einen neuen Adapter, den "Energiefluss-erweitert", entwickelt, der möglicherweise Deinen Wünsche bereits berücksichtigt bzw. noch berücksichtigen wird.

Du kannst Ihn gerne ausprobieren.

Forum:
https://forum.iobroker.net/topic/64734/test-adapter-energiefluss-erweitert-v0-0-x-github-latest

Github Link:
https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert

Schau mal rein ;)
