### ISSUE TITLE
Umrechnung W in KW

### ISSUE THREAD

**Issue by fighterzg6** [SKB-CGN/ioBroker.energiefluss#38]
Hallo, 

Erstmal sehr feine Arbeit.

Habe nur ein kleines problem, 
wenn ich w in kw Umrechen anhake macht er das auch super, nur leider ist der wert von meinem
go-e charger schon in kw und da kommt dann keine anzeige mehr in der Auto Box. (also 0,00KW).

Mit freundlichen Grüßen

**Comment by SKB-CGN** [comment]
Dann lasse dir den Wert von der eBox doch in W umrechnen, in einen eigenen Datenpunkt schreiben und diesen dann im Adapter angeben.

Der Adapter rechnet entweder mit W oder kW.

**Comment by fighterzg6** [comment]
ja, das geht auch , aber es gibt vielleicht andere die das nicht hinbekommen, und für die wäre dann so eine implementierte Umrechnung einfacher.

Mit freundlichen Grüßen

**Comment by SKB-CGN** [comment]
Bisher haben dies alle hinbekommen ;)

Danke für den Hinweis.

**Comment by SKB-CGN** [comment]
Hallo,
tut mir Leid, wenn der aktuelle "Energiefluss" Adapter deine Wünsche nicht berücksichtigen konnte.

Ich habe einen neuen Adapter, den "Energiefluss-erweitert", entwickelt, der möglicherweise Deinen Wünsche bereits berücksichtigt bzw. noch berücksichtigen wird.

Du kannst Ihn gerne ausprobieren.

Forum:
https://forum.iobroker.net/topic/64734/test-adapter-energiefluss-erweitert-v0-0-x-github-latest

Github Link:
https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert

Schau mal rein ;)
