### ISSUE TITLE
Bitte:

### ISSUE THREAD

**Issue by DerDoubleD** [SKB-CGN/ioBroker.energiefluss#39]
Der Adapter ist super! Danke für die tolle Arbeit.
Bitte den Adapter in das offizielle Repo aufnehmen (lassen)

**Comment by SKB-CGN** [comment]
> Der Adapter ist super! Danke für die tolle Arbeit. Bitte den Adapter in das offizielle Repo aufnehmen (lassen)

Derzeit befindet er sich im Test unter: https://forum.iobroker.net/topic/55627/test-adapter-energiefluss-v1-2-x-github-latest/

Sobald der Adapter so gut wie alle Wünsche abdeckt, kommt die Anfrage für das offizielle Repo :)
