### ISSUE TITLE
Falsche Anzeige bis zur vollständigen Ladung, wenn der Akku gerade entladen wird

### ISSUE THREAD

**Issue by radebold** [SKB-CGN/ioBroker.energiefluss#44]
Ich lasse die Ladezeit mit einblenden, aber in dem Moment, wenn der Akku entladen wird, kommen da komische Zeiten zustande.
Vielleicht kann man das Umrechnen, wie lange der Akku noch hält, bei der aktuellen Entladung?

Oder ausblenden, denn so wie es aktuell angezeigt wird, ist es falsch.

**Comment by SKB-CGN** [comment]
Ich denke, du hast die Anzeige nicht verstanden.

Es wird angezeigt, wie lange der Akku hält, wenn er gerade lädt **oder** entlädt. Also beide Richtungen.
Ausblenden kannst Du die Anzeige natürlich auch!

**Comment by radebold** [comment]
Dankeschön
