### ISSUE TITLE
Einheit bei "solare Produktion" wird nicht korrekt von Datenpunkt übernommen

### ISSUE THREAD

**Issue by mrMuppet** [SKB-CGN/ioBroker.energiefluss#46]
Hi,
ich hab endlich mein erstes (Test-)Modul am Wechselrichter. Leider wird im Plugin die Leistung mit 2kW angezeigt, obwohl im Datenpunkt (und dort vermutlich korrekt) von 2W die Rede ist.

**Comment by SKB-CGN** [comment]
Hallo,
ein Blick in die Beschreibung bringt zum Vorschein, das es sich hier um Textfeld handelt, welches selbst definiert werden kann.

![2022-09-28 11_06_59-SKB-CGN_ioBroker energiefluss_ This ioBroker adapter allows to display an energy](https://user-images.githubusercontent.com/58603329/192738729-55925295-de36-408e-8a23-66f8eee2aef1.png)

Einheiten aus Datenpunkten können nicht übernommen werden. Die Einstellung wird im Adapter im Reiter "Sonstiges" vorgenommen.
