### ISSUE TITLE
Background color in lovelace

### ISSUE THREAD

**Issue by copystring** [SKB-CGN/ioBroker.energiefluss#53]
No matter what I do. When I add this via an iFrame to lovelace the background color is always white.
I tried to edit the code live via the inspect function in chrome to change the color of frame iFrame to test things out.
Only when I change the color of the <body> tag the background actually goes black.

I tried with this code: 
<iframe allowtransparency="true" style="background: #000000" 
src="http://iobroker:8082/energiefluss/" 
frameborder="0" height="450px" width="100%">
</iframe>

Where this code works just fine on it's on in an .html file it does not work in lovelace for whatever reason.

Can you please make the background color selectable?

**Comment by SKB-CGN** [comment]
Hi,
The background color of the html Page is transparent. So, it should adopt the color of the surrounding page, where the iframe is placed.

Therefore the error is with Lovelace - which I do not support.

**Comment by christoph-spielmann** [comment]
Same problem in Grafana. Background is always white.
