### ISSUE TITLE
Designanpassung Frage

### ISSUE THREAD

**Issue by tofrie** [SKB-CGN/ioBroker.energiefluss#89]
Hallo,

ich würde gerne die Elemente anders anordnen. Das PV soll oben sein, das Netz und Haus auf einer Höhe. Des Weiteren würde ich die Linien eckig und nicht abgerundet darstellen damit es wie folgt aussieht:

![FD8BBF10-BFF3-4933-991D-94AEB1FA93F2](https://user-images.githubusercontent.com/60553702/209221663-5dc55684-37b4-46b1-8990-8035fe6a3ef4.jpeg)

**Comment by SKB-CGN** [comment]
Hallo,
das Grund-Design des Adapters ist aktuell fix, wie es ist.
Eine Anpassung ist bisher auch nicht geplant, da es laut der Rückmeldungen zufriedenstellend und funktional ist.

**Comment by SKB-CGN** [comment]
Hallo,
tut mir Leid, wenn der aktuelle "Energiefluss" Adapter deine Wünsche nicht berücksichtigen konnte.

Ich habe einen neuen Adapter, den "Energiefluss-erweitert", entwickelt, der möglicherweise Deinen Wünsche bereits berücksichtigt bzw. noch berücksichtigen wird.

Du kannst Ihn gerne ausprobieren.

Forum:
https://forum.iobroker.net/topic/64734/test-adapter-energiefluss-erweitert-v0-0-x-github-latest

Github Link:
https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert

Schau mal rein ;)
