### ISSUE TITLE
Feature: Animationsgeschwindigkeit

### ISSUE THREAD

**Issue by BenAhrdt** [SKB-CGN/ioBroker.energiefluss#94]
Ist es möglich der Animierten Flüsse eine weitere Option hinzu zu fügen?
Idee:
Man wählt Verbräuche aus, welche zusammengezählt als 100% definiert sind.
Entsprechend der prozentualen Anteile der Verbräuche werden die Geschwindigkeiten dargestellt.
(Nicht ausgewählte Verbraucher und die Erzeugung, Netzbezug usw. werden mit 100% Geschwindigkeit dargestellt)

Idee 2:
Der Verbrauch sind 100% und jeder Wert wir entsprechenden angepasst.

**Comment by SKB-CGN** [comment]
Ist seit der aktuellen Version inkludiert.

**Comment by BenAhrdt** [comment]
Wie funktioniert denn die Berechnung? Bei mir bewegt sich ein 550W Verbraucher gleich schnell wie ein 100W oder 200W Verbraucher.
Wird jeder Verbraucher einzeln behandelt und die Geschwindigkeit anhand des Gesamtverbrauchs ausgegeben, oder werden Sie zusammen gezählt?

Habe bspw. einen Bereich, der wird gezählt, darin sind 2 Verbraucher gemessen und ich habe die DIfferenz noch.. also eigentlich mehr W als bezogen werden, aber eben eine Verbraucher rictige Angabe:  Bspw.

Haus 1A: 550W
Verbraucher 1: 50W
Verbraucher 2: 0W
Rest: 500W

macht ja in Summe genau das doppelte nämlich 550W + 50W + 0W + 500W = 1100W

Habe noch ein GIF angehangen. 1A und Rest1A Bspw. sind nah beieinander und geschwindigkeitsmäßig
von der Animation nicht nah beieinander.

![energiefluss-0-buanet-iobroker1-Google-Chrome-2023-01-27-19-26-39](https://user-images.githubusercontent.com/92173565/215166179-f7c94a44-42f9-4e9e-b567-dff9dda3bed8.gif)

**Comment by SKB-CGN** [comment]
Steht eigentlich in der Beschreibung. 

Der höchste Verbraucher bekommt die Geschwindigkeit, die für die gesamte Animation angegeben ist. Standard: 2000ms

Jeder Verbraucher bekommt anhand seines Verbrauchs + 1000ms und wird langsamer.

**Comment by BenAhrdt** [comment]
Ist aber leider nicht so zu erkennen, denn gibt es bspw. 500W, 499W, 10W und 9W
Dann hat man immer nur einen Sprung von der gleichen Zeitdifferenz?
(Man sieht ja im Video kaum einen Unterschied von Rest 1A zu Heizung 1B und dass sind 450W Unterschied.

wäre nicht eine prozentuale Aufteilung besser?

**Comment by SKB-CGN** [comment]
Ich kann bei deinen Werten genau das Erkennen, was Sache ist.

Jede Linie läuft jeweils 1 Sekunde langsamer.
Dabei ist es ja unerheblich, wieviel Watt Unterschied ist.

Es ist ja wichtig, so wie Deine Anfrage gestellt war, zu wissen welcher Verbraucher das Meiste verbraucht, ohne die Werte zu kennen.

**Comment by BenAhrdt** [comment]
Nicht nur den meisten, sondern generell den Verbrauch. Wenn der Unterschied zwischen bspw. 1000 und 900 der selbe ist als wäre es 1000 und 10 finde ich nicht sehr gut.
Denke wirklich % wären besser.
Bspw. Einfach den Verbrauch = 100% und dann die Verbraucher % berechnet und entsprechend verlangsamt.
Wäre doch dann gut zu erkennen. Oder ?

**Comment by BenAhrdt** [comment]
Also der Hintergrund ist dass wenn ich sagen wir 3 werte habe:
510W
500W
50W

dass dann die ersten beiden wesentlich schneller laufen als die 50W
Ist ja auch eindeutlixh höherer verbrauch.
Verständlich was ich meine?

**Comment by SKB-CGN** [comment]
Aktuell zeigt der Adapter dies Geschwindigkeit wie folgt an:
- höchster Verbrauch eingestellte Geschwindigkeit
- nächst kleinerer Verbrauch + 1000ms
- nächster wieder + 1000ms
- ...

Ich versuche gerade zu verstehen, wie Du das meinst.

Ist es eher so:

Gesamtverbrauch: 1000 Watt

1. Verbrauch 500W
2. Verbrauch 300W
3. Verbrauch 200W

Geschwindigkeit angenommen bei Einstellung von 2000ms:

1. 1000ms (50%)
2. 3400ms (30%)
3. 3600ms (20%)

**Comment by BenAhrdt** [comment]
Ja fast ist es so gemeint, denn Du hast einmal in deiner Rechnung die % abgezogen und einmal die Differenz drauf gerechnet.

Im Prinzip einfach Prozentual vom Gesamtverbrauch, also wenn man "Mehr Verbraucher" als Gesamt hat mit berücksichtigt.
Ist ja bei deinem Beispiel schon:
Um deine interne Anniation mit den 2000ms bestehen zu lassen, würde ich am einfachsten 20ms pro %, die von den 100% abweichen drauf rechnen.

Dein Beispiel:
Gesamt = 1000W

V1 = 500W => 50% => 100% + 50% = 2000ms + 1000ms = 3000ms
V2  = 300W => 30% => 100% + 70% = 2000ms + 1400ms = 3400ms
V3 = 200W => 20% => 100% + 80% = 2000ms + 1600ms = 3600ms


Noch ein Beispiel mit ausgelagerter Restwertberechnug => "Mehr Verbrauch" als Gesamt.

Gesamt: 1000W

V1 = 500W => 50% => 100% + 50% => 2000ms + 1000ms = 3000ms
V2 = 50W => 5% => 100% + 95% => 2000ms + 1900ms = 3900ms
V3 (Rest): 450W => 45% => 100% + 55% = 2000ms + 11000ms = 3100ms 

Ich hoffe das war Verständlich.
Ps. die ms pro % Könnte man noch höher nehmen, bzw. einstellbar machen, damit es eindeutiger wird.

**Comment by SKB-CGN** [comment]
Ich denke, wir nähern uns 😀

Ich werde es so rechnen:

Anzahl der Verbraucher * 2000ms (konfigurierbar)

Das ist die Gesamt Geschwindigkeit. 

Diese dann in prozentual pro Verbraucher.

Vom Beispiel oben:

3 * 2000 = 6000 -> 200%

1. Verbraucher = 6000 - 3000 = 3000
2. Verbraucher = 6000 - 1800 = 4200
3. Verbraucher = 6000 - 1200 = 4800

Je größer die Zahl, desto langsamer die Linie.

So ist Verbraucher 2 um fast 50% langsamer als 1.

**Comment by BenAhrdt** [comment]
Liest sich erst mal gut mit der max Zeit.
Hatte auch die Idee, aber wollte Dich nicht verwirren :-D
was sind die 3 * 2000? und wieso 200%? Stehe grad auf dem Schlauch.

**Comment by SKB-CGN** [comment]
Ich habe den Wertebereich verdoppelt, damit die Geschwindigkeit merklich anders werden. 

Ich rechne das später nochmal genauer aus - denn bei vielen Verbrauchern kann sich die Verdopplung auch negativ auswirken.

Schaue ich mir aber nochmal an.

**Comment by BenAhrdt** [comment]
OK, Du rechnest aber unten mit den 30% und 20% genauso, als wären die 6000 = 100%, also ist die Verdoppelung wieder weg.
Auch würde ich nicht nur die Anzahl nehmen, denn bei einem Hohen Verbraucher mit verbrauch gegen 100% ... sagen wir 98 oder 99, dann geht die Zeit gegen 0.
es sei denn diese Zeit rechnest Du auf die vorhandenen 2000ms standard drauf, dann passt es ;-)

**Comment by BenAhrdt** [comment]
Kann man schon was testen?

**Comment by SKB-CGN** [comment]
Ruhig, ruhig ;-)

Es ist Wochenende und ich habe frei.

Nächste Woche geht's weiter.

**Comment by BenAhrdt** [comment]
OK, alles klar.

**Comment by SKB-CGN** [comment]
Du kannst einfach nochmal die Version drüber installieren und einmal schauen, wie es bei Dir mit der Geschwindigkeit aussieht. Ich denke, es sieht ganz gut aus.

**Comment by BenAhrdt** [comment]
Mache ich spätestens morgen.
Bin gerade nicht zu Hause.

**Comment by BenAhrdt** [comment]
Was sagst Du hierzu?
Finde es schon ganz gut, aber finde auch, dass sich gerade unten die 560W, 360W und die 180W sich nicht großartig unterscheiden, oder wie siehst Du das?

![energiefluss-0-buanet-iobroker1-Google-Chrome-2023-01-30-21-26-49](https://user-images.githubusercontent.com/92173565/215588324-742136a3-f305-41e8-b146-c64c277bb749.gif)

**Comment by SKB-CGN** [comment]
Ich habe die Rechnung etwas verändert. 

Grundgeschwindigkeit / Gesamtverbrauch

Somit hat man für jedes Watt die Geschwindigkeit.

Dies wird mit dem Verbrauch multipliziert und zu der Grundgeschwindigkeit addiert.

So sind die Unterschiede größer als in der Rechnung oben.

**Comment by BenAhrdt** [comment]
Ja also addierst du die % auf die Grundgeschwindigkeit (Leistung/Gesamtleistung entspricht den %) das mit der grundgeschwindigkeit multipliziert und dann diese addiert nach eine Range von:
1-2 mal Grundgeschwindigkeit….
Also selbst bei 1% Verbrauch ist die Bewegung schneller als die Grundgeschwindigkeit.
Für mich aus Anwendersicht sieht man auf den ersten Blick nicht wirklich große Unterschiede.
Eventuell einen Multiplikationsfaktor dazu, bevor addiert wird, oder noch besser, gar nicht addieren. Dann bewegen sich rechts die Animationen nur noch von 0-1 mal Grundgeschwindigkeit…. Fände ich eventuell schöner und übersichtlicher…. Ps. Vielleicht auch eine Checkbox mit addieren, oder nicht. Das wäre doch klasse.
Hoffe war verständlich

**Comment by SKB-CGN** [comment]
Nicht ganz:

Als Beispiel:

Verbrauch: 1000 Watt
Geschwindigkeit: 2000ms

1. Verbraucher: 500 Watt
2. Verbraucher: 300 Watt
3. Verbraucher: 200 Watt

2000 / 1000 = 2

1. Verbraucher: 500 x 2 = 1000
2. Verbraucher: 300 x 2 = 600
3. Verbraucher: 200 x 2 = 400

Geschwindigkeit:
1. 2000 + (2000 - 500) = 3500
2. 2000 + (2000 - 300) = 3700
3. 2000 + (2000 - 200) = 3800

Wenn die Geschwindigkeit kleiner als 2000ms ist, "rasen" die Punkte über die Linie.

Das sähe sehr unschön aus.

Ich tüftel aktuell noch nach einer besseren Lösung.

**Comment by BenAhrdt** [comment]
Ja ich habe eben kurz falsch herum gedacht (in % und nicht in der Zeit für die Geschwindigkeit)
Komme trotzdem nicht auf deine Geschwindigkeiten….
Wäre das bei 1. nicht
2000ms + 500W * 2ms/W = 3000ms

anstatt die 3500ms ???

ne Idee wäre noch die Auflösung für den Gesamtverbrauch an zu geben und dann anhand des Verbrauche sowas zu berechnen….

bspw. Angabe Grundgeschwindigkeit = 2000ms
Zeit Gesamtverbrauch = 10000ms

Berechnung:
V= (1-Leistung/Gesamt) * 10000ms + 2000ms

messwerte: 
Gesamt: 1000W
V1: 800W
V2: 200W

geschw. 1: (1-0,8) *10000 + 2000 =
4000ms

geschw. 2: (1-0,2) * 10000 + 2000 =
10000ms

Habe jetzt extra die Werte so groß auseinander gewählt, damit man einen Effekt  sieht… wenn die Zeit statt 10000 auch 2000 ist, wird es eben enger.
So in die Richtung wäre eine Idee, oder?

**Comment by SKB-CGN** [comment]
Wo nimmst Du denn die Zeit für den Gesamtverbrauch her?

Die kann nicht statisch sein, da nicht jeder User alle Elemente verwendet.

**Comment by BenAhrdt** [comment]
Die Zeit für den Gesamtverbrauch habe ich auf die Grundgeschwindigkeit gesetzt.
Gesamt hat ja jeder. Dann heißt es halt nicht Grundgeschwindigkeit sondern Geschwindigkeit Gesamtverbrauch.
Aber die letzte Berechnung die ich rein geschrieben habe (edit) finde ich ganz gut und einfach. Oder?

**Comment by BenAhrdt** [comment]
Jeder hat einen Gesamtverbrauch und somit ist das doch einfach möglich:

50% von der Gesamtleistung dauern eben
Doppelt so lange wie 100% und 20% eben 5 mal so lang… das wäre doch ne einfach und gute Lösung

Also es bleibt bei den 2000ms (Gesetzt als Gesamtverbrauch)

Gesamt 1000W
V1: 500W
V2: 300W
V3: 200W

Geschw. 1: = 1000/500 *2000 = 4000ms
Geschw. 2: = 1000/300 * 2000 = 6666ms
Geschw. 3: = 1000/200 * 2000 = 10000ms

**Comment by SKB-CGN** [comment]
Ich baue es Dir mal ein, dann kannst Du es installieren und testen.

**Comment by BenAhrdt** [comment]
Top. Ich bin gespannt

**Comment by BenAhrdt** [comment]
Eine Frage noch… die 2000ms, ist das die Zeit für die ganze Linie zu Verbraucher?

**Comment by SKB-CGN** [comment]
2000ms ist die Zeit, die die 3 Punkte bei der Original Konfiguration brauchen, um sich mit dem Abstand einen Bereich weiter zu bewegen.

**Comment by BenAhrdt** [comment]
Das heißt von Anfang bis Ende der Linie?
Eine Geschwindigkeitsangabe der gelben Linie wäre sicher aufgrund der Verschiedenen Größen / Auflösung der Visualisierung schwierig.
Ok geht man davon aus, dass die Entfernungen gleich sind ist auch die Animation gleich lang bei gleichem Verbrauch.

**Comment by SKB-CGN** [comment]
Die Linie wird in Teilen animiert und wiederholt.

Eine Animation beinhaltet die Punkte und den Abstand (Leerraum) bis zum Beginn der nächsten Punkte. Das ist die Dauer.

Diese wird dann "aneinander gereiht", damit alle Animationen gleich schnell sind. Da jede Linie unterschiedlich lang ist, würden die Animationen nicht gleich schnell laufen.

**Comment by BenAhrdt** [comment]
Das meinte ich. Ok.
Ich warte gespannt auf deine Version.

**Comment by SKB-CGN** [comment]
Die Version liegt zum Installieren bereit.

Einfach nochmals über die Git-Katze installieren.

**Comment by BenAhrdt** [comment]
Finde ich schon ganz gut, nur die Animation ruckelt etwas beim neu laden der gelben Punkte.
Ps. hast Du auch die linke Seite daran geknüpft?
Wäre doch cool, dann Sieht man direkt auch was "schnell" aus dem Netz, dem Akku, oder der PV kommt.

![energiefluss-0-buanet-iobroker1-Google-Chrome-2023-01-31-08-34-42](https://user-images.githubusercontent.com/92173565/215696141-272a9f0c-2cc4-4118-ac53-0f89ddce96b5.gif)

**Comment by SKB-CGN** [comment]
Nein, die linke Seite bleibt so, wie sie ist. (Vorerst)

Bei mir ruckelt nichts.

**Comment by BenAhrdt** [comment]
komisch.. Siehst es ja in dem Gif...

**Comment by SKB-CGN** [comment]
Dann stell mal in den Optionen 1 Punkt weniger ein, dann schauen - wenns geht, wieder einen Punkt mehr.

**Comment by BenAhrdt** [comment]
Ändert nicht wirklich was

**Comment by SKB-CGN** [comment]
Zeig mir mal die Einstellungen der Animation

**Comment by BenAhrdt** [comment]
![image](https://user-images.githubusercontent.com/92173565/215709998-638f54ed-bbf7-4dd1-9966-8ecfdba44ec9.png)

**Comment by BenAhrdt** [comment]
Ich habe gerade mal die automatische  Animation deaktiviert, sodass die gleichmäßige Geschwindigkeit aktiv ist.... dann ruckelt es nicht.

**Comment by SKB-CGN** [comment]
Wenn zuviele Browser-Fenster auf sind, dann ruckelt es. Habe es gerade mit deinen Einstellungen probiert. Ruckelt nicht ;)

**Comment by BenAhrdt** [comment]
sehr komisch, ich habe nur eine Ansicht laufen

**Comment by SKB-CGN** [comment]
Die Punkte springen, wenn der Rechner nicht genug Power hat, um die Punkte darzustellen. Also, weniger Punkte einstellen, dann läuft es.

**Comment by BenAhrdt** [comment]
Habe es nun auf 3 gestellt. scheint zumindest grad etwas besser zu laufen.
ioBroker läuft auf ner Diskstation im Docker container (15%) cpu und 3% RAM Auslastung.
OK, wenn eine Hohe Leistung dabei ist stehe die Anderen fast... aber das Ist ein Anzeichen, dass die Leistung fast das Gesamte alleine ausmacht, oder meinst Du eine max. Zeit macht noch Sinn?
Keine Ahnung ob dann wieder andere Effekte kommen.
![energiefluss-0-buanet-iobroker1-Google-Chrome-2023-01-31-11-14-30](https://user-images.githubusercontent.com/92173565/215732507-b5e579cd-3bb3-4638-aac5-b4814e3c017e.gif)

**Comment by BenAhrdt** [comment]
Jetzt springt es wieder... immer nachdem der wert sic minimal ändert. :-(

**Comment by SKB-CGN** [comment]
Die Berechnung erfolgt im Client, sprich im Browser. Wenn dort zu wenig Ressourcen zur Verfügung stehen, dann springt es. Da kann ich leider nichts dran machen. Die Animation ist hungrig nach CPU - lässt sich aber nicht anders lösen.
Daher ist es unerheblich, ob ioBroker in einem Cisco USC Server mit 1TB Ram und 24 CPU's läuft - der Client stellt die Animation dar.

**Comment by BenAhrdt** [comment]
OK, aktuell schaue ich es mit meinem Arbeitsrechner an, der hat noch jede Menge Reserven. Naja weiß dann auch nicht weiter.
Machst u noch eine Max Zeit, oder lässt Du die Berechnung so?

**Comment by BenAhrdt** [comment]
Ich habe gerade mal die Datenpunkte fest auf einen Wert gesetzt und dann ruckelt nichts. es ruckelt wirklich NUR, wenn die Daten aktualisiert werden. (Bei mir alle 2s)

**Comment by SKB-CGN** [comment]
Habe das "Problem" gefunden. Muss nur noch schauen, wie man dies lösen kann.

**Comment by BenAhrdt** [comment]
OK, was ist es?

**Comment by SKB-CGN** [comment]
Du kannst Die Version nochmals installieren,

Wenn die Werte sich ändern, wird sich auch die Geschwindigkeit ändern, die neu zugewiesen wird.
Habe jetzt eine Entprellung eingebaut, die verhindert, das es springt, wenn die Werte unterhalb 10% Änderung sind.

**Comment by BenAhrdt** [comment]
Das scheint es zu sein.
Wäre der Wert noch einstellbar, oder auf sagen wir 25% abhebbar?

**Comment by SKB-CGN** [comment]
Warum sollte man alles anpassen müssen/sollen? Und, warum auf 25% statt auf 10%?

**Comment by BenAhrdt** [comment]
Naja war nur so ne Idee, weil die Lastsprünge Kundenabhängig sind.
Bei meinen Verbrauchern kommt eben schon mal 15-20% vor.

**Comment by SKB-CGN** [comment]
Also, ein Wasserkocher springt von 0W auf 2800W innerhalb einer Sekunde - somit wäre dies raus.
Eine Lampe geht meist auch an oder aus.
Eine Waschmaschine erhöht sich langsam - außer sie heizt.

Welche "speziellen" Verbraucher hast Du den, die 20% Last wechseln?

**Comment by BenAhrdt** [comment]
naja wenn ein Verbraucher einen Sprung von 100W hat, dann ist bei einem Vorherigen Verbrauch von 500W der Neue Verbrauch 600W => +20%.

**Comment by SKB-CGN** [comment]
Richtig, aber bevor er "springt", ist die Animation nicht sichtbar .... daher meine Frage, hast Du Wasserkocher, die während des Betriebs die Last um 20% ändern? Oder andere Geräte, die das tun? Wenn ja, welche?

**Comment by BenAhrdt** [comment]
Ist ja egal welche, auf jeden Fall wechselt die Gesamtleistung um den Betrag und dann springt es.
Weis nicht genau was es gerade war, aber das war der Bezug.
Eventuell gehen ja auch welche aus und dafür welche an und das sorgt eben für diese Schwankungen.

**Comment by SKB-CGN** [comment]
Es wird der Prozentwert je Verbraucher genommen. Nicht der der Produktion oder des Netzbezugs. Pro Verbraucher.

**Comment by BenAhrdt** [comment]
Ja, aber ich habe einen Punkt "Restverbrauch", der eben alle Verbraucher beinhaltet, die nicht separat gemessen werden.
Dadurch kommt eben genau dieser Effekt.

**Comment by SKB-CGN** [comment]
Gut, dann schau es Dir bitte einen Tag lang an und berichte, wie es aussieht. Wenn es von Nöten ist, kann man den Entprellwert als Option hinzufügen.

**Comment by BenAhrdt** [comment]
ok

**Comment by BenAhrdt** [comment]
Also ich habe es jetzt 15 min beobachtet.
Der Verbrauch war um 350W rum und da springt e bei 10% schon sehr oft.

**Comment by BenAhrdt** [comment]
Was spricht eigentlich dagegen die "Entprellung" immer aktiv zu haben und nicht von der Änderung abhängig zu machen?

**Comment by SKB-CGN** [comment]
Weil eben nicht JEDER die automatische Geschwindigkeit nutzt. Daher gab es sie vorher nicht, wie dir sicherlich aufgefallen ist ;)

Weiterhin: Was soll die Entprellung denn bringen, wenn sonst alle Linien bei einer definierten Geschwindigkeit laufen?

**Comment by BenAhrdt** [comment]
Mann kann diese ja nur aktivieren, wenn die automatische Geschwindigkeit genutzt wird.
Das war der Gedanke dahinter.

**Comment by SKB-CGN** [comment]
Ich glaube, Du sprichst an dir selbst vorbei. Die Entprellung ansich ist mit 10% aktiv, wenn die automatische Geschwindigkeit genutzt wird.
Dies reicht Dir leider nicht aus, also muss man den Prozentsatz noch konfigurierbar machen - somit ist sie auch dann aktiv, wenn sie genutzt wird - mit den Prozenten, die Du definierst.

**Comment by SKB-CGN** [comment]
So, die neue Version ist verfügbar. Bitte testen.

**Comment by BenAhrdt** [comment]
Ich habe es getestet.... mit der Neuen Version springt es nicht wal wirklich bei der Einstellung 1%, obwohl die Änderung größer ist.

**Comment by BenAhrdt** [comment]
> Ich glaube, Du sprichst an dir selbst vorbei. Die Entprellung ansich ist mit 10% aktiv, wenn die automatische Geschwindigkeit genutzt wird. Dies reicht Dir leider nicht aus, also muss man den Prozentsatz noch konfigurierbar machen - somit ist sie auch dann aktiv, wenn sie genutzt wird - mit den Prozenten, die Du definierst.

Ich habe damit gemeint, die Daten nur wenn die automatische Geschwindigkeit aktiv ist generell zu entpressen... egal bei welcher Änderung. ist sie nicht aktiv dann eben nicht.

**Comment by BenAhrdt** [comment]
Jetzt springt es weider... habe die daten wieder eingefroren und einen Datenpunkt im Sekundentakt von 500W auf 600W geändert. Egal ob Einstellung 1 oder 25, das springen ist gleich.

**Comment by BenAhrdt** [comment]
Sorry, war wohl ein refresh Problem des Browsers...
Scheint zu gehen.

**Comment by SKB-CGN** [comment]
Das  sollte man immer tun. Browser refresh - denn auch da wird etwas angepasst.

Bei mir geht es nämlich :)

**Comment by BenAhrdt** [comment]
Ja denke so ist es schon ganz gut. Bei hohen Verbräuchen bewegen sich zwar die kleinen kaum, aber das ist halt so und ja auch prozentual Richtig.

**Comment by SKB-CGN** [comment]
Dann wäre eine Ausgliederung sinnvoll.

Ganz gut klingt noch nicht zufrieden?!

**Comment by BenAhrdt** [comment]
Ja denke so kann man es lassen.
Zumindest fällt mir grad nichts ein ;-)

was ausgliedern?

**Comment by SKB-CGN** [comment]
Was möchtest Du ausgliedern?

Wenn es Dich zufriedenstellt, dann mache ich das Issue zu.

**Comment by BenAhrdt** [comment]
Ich mache es mal zu. vielleicht braucht es noch ein Minimal % satz für die Geschwindigkeit.
