### ISSUE TITLE
Anzeigefehler bei Safari Browser

### ISSUE THREAD

**Issue by ThorstenBoettler** [SKB-CGN/ioBroker.energiefluss#95]
**Describe the bug**  
Im Batterie "Kästchen" wird das Batterie Symbol nicht angezeigt.
Die Restlaufzeit ist komplett an einer falschen Stelle im Diagramm

**To Reproduce**  
Problem kan ich nur bei "Safari" beobachten, unter Firefox sieht alles ganz normal aus

**Expected behavior**  
Das es in Safari genauso wie in Firefox funktioniert ;-)

**Screenshots & Logfiles**  
<img width="554" alt="image" src="https://user-images.githubusercontent.com/57589233/215324223-a5440730-920a-410d-94de-90faa915e609.png">

**Versions:**  
 - Adapter version: 3.2.0
 - JS-Controller version: 4.0.24 
 - Node version: 16.19.0 
 - Operating system: Debian

**Comment by SKB-CGN** [comment]
Danke für die Beschreibung. Safari wird aktuell nicht unterstützt, da der Marktanteil bei weitem sehr gering ist.

Lösung:
Firefox, Edge, Chrome, Opera, FullyBrowser und viele weitere.
