### ISSUE TITLE
Eingang als String

### ISSUE THREAD

**Issue by Matty0688** [SKB-CGN/ioBroker.energiefluss#98]
Hallo,

der Senec Adapter liefert defaultmäßig strings statt numbers.
Wir haben ewig gesucht warum der Adapter nicht funktioniert, bis wir auf die Idee kamen die Werte per Script in Number umzurechnen.

Das Problem ist, es gibt seitens des Adapters keinen Fehler.
Das Protokoll ist fehlerfrei, die Seite des Energieflusses bleibt aber einfach nur weiß, ohne irgendeine Rückmeldung.

Vorschlag: der Adapter prüft intern den Eingang, und wandelt automatisch strings in Numbers.

Alternativ sollte es wenigstens eine Fehlermeldung im Protokoll geben, der den Fehler erläutert. 🙂

**Comment by SKB-CGN** [comment]
Hallo,
wenn man Berechnungen mit Werten durchführt, sollten diese dann schon als Wert (Nummer/Zahl) vorliegen.
Dem Adapter ist es egal, was er liest und was nicht. Wenn der Wert nicht "berechenbar" ist, läuft der Adapter ansich weiter, ohne das Log vollzumüllen.

Wie sieht denn der Datenpunkt ansich aus?

**Comment by Matty0688** [comment]
Hi, 

anbei ein paar Screenshots.

Die Seite bleibt tatsächlich weiß, nachdem kurz das übliche Loading kam.

![A16E1C74-8181-480F-A4A6-1B85C759ACB0](https://user-images.githubusercontent.com/118753301/216334809-a70f059b-fb6b-4207-bb8e-eba8f95a1cec.jpeg)
![7F715096-6828-4B26-B8E0-F9726B26E396](https://user-images.githubusercontent.com/118753301/216334815-bf4d45bf-48a9-4aee-84ae-aa4f81d409cc.jpeg)
![DDD04349-D2FC-4B36-ADB3-89AE47B2B877](https://user-images.githubusercontent.com/118753301/216334816-35232701-f75c-4f74-9964-04aad87e5911.jpeg)

**Comment by Matty0688** [comment]
Wie gesagt, sobald der String mit einem Script in ein Integer gewandelt wird und in einen neuen Objekt gespeichert wird läuft es

**Comment by Matty0688** [comment]
Vielen Dank für die schnelle Umsetzung. Der Adapter ist echt der Knüller. 👍🏻

**Comment by SKB-CGN** [comment]
Gerne mal die neue Version einfach drüber installieren und schauen, ob es nun klappt, wie gewünscht!
