### ISSUE TITLE
Vorzeichen Einspeisung nicht korrekt angezeigt

### ISSUE THREAD

**Issue by ScumbagSteve** [SKB-CGN/ioBroker.energiefluss#99]
Mir ist aufgefallen, dass bei Netzeinspeisung das Vorzeichen scheinbar nicht korrekt angezeigt wird.

PV EG: 192W
PV HP: 452W
Netz: -368W
Die Werte werden korrekt verarbeitet, denn es werden für den Hausverbrauch insgesamt 276W berechnet.
Seltsamer weise wird das negative Vorzeichen beim Netzbezug (eigentlich Netzeinspeisung in diesem Fall) nicht angezeigt.
Netzbezug und Einspeisung laufen über einen gemeinsamen Datenpunkt. Positiv = Bezug, Negativ = Einspeisung.
Hab schon bisschen mit der Konfig gespielt, aber konnte es nicht fixen. Liegt ein Programmfehler vor?

<img width="450" alt="ScreenCapture at Sat Feb 4 11:21:11 CET 2023" src="https://user-images.githubusercontent.com/8447146/216762065-ec2c5a9a-36c7-4546-a744-201395e7cf32.png">

**Comment by SKB-CGN** [comment]
Danke für die Rückmeldung. 

Die Werte werden immer positiv angezeigt.
Nur dir Flussrichtung der Animation ändert sich.

**Comment by ScumbagSteve** [comment]
Bedeutet das, dass die "Schwelle" für Farbänderungen beim Netz niemals geändert wird?
Ich habe die Schwelle auf 0 (default) und hätte erwartet, dass die Farbänderung bei Einspeisung erfolgt.

**Comment by SKB-CGN** [comment]
Die Farbe zeigt den Wert anders an, wenn die eingestellte Schwelle erreicht ist.

Netzbezug und Netzeinspeisung ändern nur die jeweilige Richtung der Animation.

**Comment by Mutanten** [comment]
Sehr schade, dass der Wert für die Netzeinspeißung nur positiv angezeigt wird, das gilt auch für die Batterieentladung. Vielleicht könntest du das noch optional integrieren?

**Comment by SKB-CGN** [comment]
Was ist daran Schade? Verstehe ich nicht?!

Energie ist immer positiv.

Die Entnahme siehst Du doch an der Flussrichtung. Daher sind alle Werte positiv, um zu unterscheiden.

**Comment by Mutanten** [comment]
über das Vorzeichen kann man es sofort identifizieren ohne die Richtung anzusehen. In der der VIS ist das eben so, daran bin ich gewöhnt. Sonst super Arbeit!

**Comment by SKB-CGN** [comment]
Der Mensch arbeitet visuell.

Du wirst es eher über die Linie bzw. Animation sehen, als über ein Vorzeichen.

Ein Computer würde dies mit dem Vorzeichen eher sehen ;)

**Comment by ScumbagSteve** [comment]
> über das Vorzeichen kann man es sofort identifizieren ohne die Richtung anzusehen. In der der VIS ist das eben so, daran bin ich gewöhnt. Sonst super Arbeit!

Ich finde auch, dass man es mit einem Vorzeichen sofort auf einen Blick sieht, während man mit den Linien erst mal schauen muss, in welche Richtung sie gehen. Energie ist vielleicht immer Positiv, aber ein Netzbezug ist es eben nicht.
Vielleicht kannst du es ja optional implementieren. Für mich wäre es auch praktisch

**Comment by SKB-CGN** [comment]
Auch der Netzbezug ist immer positiv. Daher gibt es ja meistens auch 2 Zählwerke :)

**Comment by ScumbagSteve** [comment]
Solange du Netzbezug und Verbrauch dann auch mit zwei Datenpunkten / Zählwerken darstellen würdest, würde ich dir zustimmen. Nur einen Datenpunkt zu zeigen, der dann manchmal Netzbezug und manchmal Netzeinspeisung darstellt empfinde ich als nicht konsequent.

**Comment by SKB-CGN** [comment]
Ist anhand der Linien-Animation konsequent.

Ich kann ja nichts für die Datenpunkte, die positiv oder negativ sind.

**Comment by Homeworker11** [comment]
Auch ich würde mir eine Negative Anzeige bei der Netzeinspeisung wünschen wenn die Solarproduktion höher ist als der Verbrauch.
Ich habe schon stunden nach dem Fehler gesucht. 😥

**Comment by SKB-CGN** [comment]
Wenns Euch glücklich macht, baue ich irgendwann mal eine Checkbox ein, wo das Vorzeichen negativ sein kann.

**Comment by SKB-CGN** [comment]
Bitte die neue Version einmal ausprobieren. Das geforderte Thema Deines Beitrags wurde hier berücksichtigt!

**Comment by Homeworker11** [comment]
Perfekt ! ✅😀

 

Danke

 

Von: SKB-CGN ***@***.***> 
Gesendet: Freitag, 24. Februar 2023 16:46
An: SKB-CGN/ioBroker.energiefluss ***@***.***>
Cc: Homeworker11 ***@***.***>; Comment ***@***.***>
Betreff: Re: [SKB-CGN/ioBroker.energiefluss] Vorzeichen Einspeisung nicht korrekt angezeigt (Issue #99)

 

Bitte die neue Version einmal ausprobieren. Das geforderte Thema Deines Beitrags wurde hier berücksichtigt!

**Comment by SKB-CGN** [comment]
Hallo,
tut mir Leid, wenn der aktuelle "Energiefluss" Adapter deine Wünsche nicht berücksichtigen konnte.

Ich habe einen neuen Adapter, den "Energiefluss-erweitert", entwickelt, der möglicherweise Deinen Wünsche bereits berücksichtigt bzw. noch berücksichtigen wird.

Du kannst Ihn gerne ausprobieren.

Forum:
https://forum.iobroker.net/topic/64734/test-adapter-energiefluss-erweitert-v0-0-x-github-latest

Github Link:
https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert

Schau mal rein ;)
